### ISSUE TITLE
Brochure review: remove justified alignment from description text

### ISSUE THREAD

**Issue by manuel489** [metanorma/bipm-si-brochure#100]
*In relation to https://github.com/metanorma/bipm-si-brochure/issues/87*

In *mep-candela-rapport-en.pdf*, there is justified alignment applied on description text, making it look ugly:

*Generated:*
![issue4-generated](https://user-images.githubusercontent.com/33627611/111411443-f6540680-86b0-11eb-873f-de1e4f101258.PNG)

*Original:*
![issue4-original](https://user-images.githubusercontent.com/33627611/111411451-f9e78d80-86b0-11eb-9fb7-bfeaa4b422fc.PNG)

(*This issue wasn't there before.*)

Files related: 
[mep-candela-rapport-en.zip](https://github.com/metanorma/bipm-si-brochure/files/6153606/mep-candela-rapport-en.zip)

**Comment by Intelligent2013** [comment]
Fixed (issue was side effect of https://github.com/metanorma/bipm-si-brochure/issues/94)
![изображение](https://user-images.githubusercontent.com/5559926/111457976-ee847880-8729-11eb-954b-45d29fd86b04.png)

**Comment by manuel489** [comment]
This is fixed. Thanks!
Closing.
