### ISSUE TITLE
Brochure review: right separation in Delta symbol

### ISSUE THREAD

**Issue by manuel489** [metanorma/bipm-si-brochure#103]
*In relation to https://github.com/metanorma/bipm-si-brochure/issues/87*

I find the separation between `Delta` symbol and whatever other symbol at its right is longer than normal.

For example, from *mep-metre-definition-en.pdf*

*Generated:*
![issue-delta-generated](https://user-images.githubusercontent.com/33627611/111492132-cc333080-8712-11eb-88fc-4a5999773ef8.PNG)

*Original:*
![issue-delta-original](https://user-images.githubusercontent.com/33627611/111492143-cdfcf400-8712-11eb-956d-a1bb59938faa.PNG)

Files related: [mep-metre-definition-en.zip](https://github.com/metanorma/bipm-si-brochure/files/6157493/mep-metre-definition-en.zip)

**Comment by Intelligent2013** [comment]
Delta encoded in `mo` tag:
```xml
<math xmlns="http://www.w3.org/1998/Math/MathML"><mo>&#916;</mo><mi>z</mi></math>
```

To decrease a distance between Delta and char at right, I need to add an attribute `rspace="0.25em"` on-fly via xslt.

**Comment by Intelligent2013** [comment]
Fixed:
![изображение](https://user-images.githubusercontent.com/5559926/111523324-33c99a00-876c-11eb-93fd-4e087f29ead6.png)

**Comment by manuel489** [comment]
Excellent, thank you.
Closing.
