### ISSUE TITLE
Brochure review: prepended "Chapter" word in equation references

### ISSUE THREAD

**Issue by manuel489** [metanorma/bipm-si-brochure#104]
*In relation to https://github.com/metanorma/bipm-si-brochure/issues/87*

From *mep-mole-definition-en.pdf*,
The word "Chapter" is prepended to equation cross-references

![issue-prepended-chapter](https://user-images.githubusercontent.com/33627611/111616041-cf342c80-87b7-11eb-91fd-6740f1345ff2.PNG)

**Comment by opoudjis** [comment]
Container-based cross-reference of formulas (identifying them with containing clause) is default, inherited from ISO style; overriding in BIPM.
