### ISSUE TITLE
Generating brackets in PDF

### ISSUE THREAD

**Issue by anermina** [metanorma/bipm-si-brochure#107]
Brackets are not generated in PDF for the following type of expression: `stem:[2.3 ("unitsml(cm)")^3]`.

In HTML, there is a regular `mfenced` expression, but it seems to be ignored in PDF:
```
<mo>=</mo><mn>2.3</mn><msup><mrow><mfenced open="(" close=")"><mrow><mrow xref="U_cm"><mi mathvariant="normal">cm</mi></mrow>
</mrow></mfenced>
```
Original (left) vs. generated (right) PDF:
![image](https://user-images.githubusercontent.com/55683568/111869527-474d4e80-8980-11eb-9544-4b9b4ee595cb.png) 

HTML output:
![image](https://user-images.githubusercontent.com/55683568/111869499-30a6f780-8980-11eb-9afa-660a3bad3883.png)

**Comment by Intelligent2013** [comment]
@anermina could you attach a file si-brochure-fr.presentation.xml, please?

**Comment by anermina** [comment]
Sure, it is attached. The same happens in EN version, so I'm attaching English and collection presentation XMLs as well.
[presentation-xml.zip](https://github.com/metanorma/bipm-si-brochure/files/6175756/presentation-xml.zip)

**Comment by Intelligent2013** [comment]
This issue is a side effect of solution for issue https://github.com/metanorma/bipm-si-brochure/issues/69.
I'll try to find more robust solution.

**Comment by Intelligent2013** [comment]
Fixed:
![изображение](https://user-images.githubusercontent.com/5559926/111877282-a8424a00-89b3-11eb-8345-c7ca39007067.png)

**Comment by anermina** [comment]
Looks good now! Thanks @Intelligent2013 .
