### ISSUE TITLE
Generating BIPM SI brochure title in PDF

### ISSUE THREAD

**Issue by anermina** [metanorma/bipm-si-brochure#108]
Document title looks different (in terms of boldfaced items) when opened on MAC and Windows OS.

Original (left) vs. generated (right, Windows OS) PDF:
![image](https://user-images.githubusercontent.com/55683568/111870489-571b6180-8985-11eb-90e3-99111f6a083c.png)

Generated (MAC OS):
![image](https://user-images.githubusercontent.com/55683568/111870482-4c60cc80-8985-11eb-828b-fe2ce278043c.png)

**Comment by Intelligent2013** [comment]
@anermina It seems that WorkSans fonts didn't embedded into PDF. Could check it? (by press CTRL-D in Adobe Reader,or via menu File->Properties, tab Fonts)

Should be:
![изображение](https://user-images.githubusercontent.com/5559926/111871344-740e5f80-899a-11eb-9a0d-a41a751a5f8f.png)

But I assume that in your case font SourceSansPro is using instead of WorkSans:
![изображение](https://user-images.githubusercontent.com/5559926/111871384-c485bd00-899a-11eb-9415-ff55f2032d28.png)

**Comment by anermina** [comment]
Yes, I don't see WorkSans. I have these:
![image](https://user-images.githubusercontent.com/55683568/111871468-84b6d980-898a-11eb-9a72-1ae4f9a7c134.png)
![image](https://user-images.githubusercontent.com/55683568/111871479-95674f80-898a-11eb-87d3-ceb4c0a26116.png)
![image](https://user-images.githubusercontent.com/55683568/111871487-a0ba7b00-898a-11eb-9d86-297bcb7be53e.png)
![image](https://user-images.githubusercontent.com/55683568/111871495-aa43e300-898a-11eb-9f5f-5dfbc402dcdc.png)

If it's just up to my settings, then this ticket can be ignored. :)

**Comment by Intelligent2013** [comment]
It seems this issue relates to https://github.com/metanorma/mn-samples-iso/issues/58.

**Comment by ronaldtse** [comment]
Agree with @Intelligent2013 , likely.

**Comment by ronaldtse** [comment]
I'm still seeing this problem even on my local generation:
<img width="654" alt="Screenshot 2021-04-09 at 4 34 20 PM" src="https://user-images.githubusercontent.com/11865/114152968-6e7cb780-9951-11eb-9373-a27454deb2d8.png">

**Comment by CAMOBAP** [comment]
Yep looks like it's the same issue metanorma/mn-samples-iso#58 waiting for https://github.com/metanorma/isodoc/commit/5fa434cd7af682f804cee96b88cfd1c8bfa9b653 release

**Comment by ronaldtse** [comment]
@CAMOBAP it's a different problem here. I have changed to using Git gems but the same problem appears:

```ruby
gem "metanorma-cli", git: "https://github.com/metanorma/metanorma-cli"
gem "metanorma-iso", git: "https://github.com/metanorma/metanorma-iso", branch: "fix/scripts-html"
gem "metanorma-standoc", git: "https://github.com/metanorma/metanorma-standoc"
gem "metanorma", git: "https://github.com/metanorma/metanorma", branch: "fix/css-override"
gem "isodoc", git: "https://github.com/metanorma/isodoc"
```

In addition, `fontist list` tells me that all Work Sans fonts are installed:

```sh
$ fontist list 'Work Sans'
work_sans
 Work Sans
  Black (installed)
  Black Italic (installed)
  Bold (installed)
  Bold Italic (installed)
  ExtraBold (installed)
  ExtraBold Italic (installed)
  ExtraLight (installed)
  ExtraLight Italic (installed)
  Italic (installed)
  Light (installed)
  Light Italic (installed)
  Medium (installed)
  Medium Italic (installed)
  Regular (installed)
  SemiBold (installed)
  SemiBold Italic (installed)
  Thin (installed)
  Thin Italic (installed)
```

@Intelligent2013 @CAMOBAP can you help here? Thanks.

**Comment by ronaldtse** [comment]
@CAMOBAP FYI that *each line* in the title uses a *different font style*.

**Comment by ronaldtse** [comment]
@CAMOBAP has a solution and apparently this is a bug.

**Comment by Intelligent2013** [comment]
@ronaldtse could you attach a log for mn2pdf? In log should be exact warning about font's file name which can't be found.

**Comment by CAMOBAP** [comment]
@Intelligent2013 @ronaldtse I already found the issue missing font-mainfest argument PR on the way

**Comment by CAMOBAP** [comment]
@ronaldtse @anermina can you confirm that the attached sample use the correct fonts?

 - [collection_en.pdf](https://github.com/metanorma/bipm-si-brochure/files/6284811/collection_en.pdf)
 - [collection_fr.pdf](https://github.com/metanorma/bipm-si-brochure/files/6284813/collection_fr.pdf)
 - [collection.pdf](https://github.com/metanorma/bipm-si-brochure/files/6284814/collection.pdf)


Fonts:
```
pdffonts bilingual-brochure/collection.pdf
name                                 type              encoding         emb sub uni object ID
------------------------------------ ----------------- ---------------- --- --- --- ---------
EAAAAA+SourceSansPro-Regular         CID TrueType      Identity-H       yes yes yes  48833  0
EAAAAB+TimesNewRomanPSMT             CID TrueType      Identity-H       yes yes yes  48842  0
EAAAAC+SourceSansPro-Bold            CID TrueType      Identity-H       yes yes yes  48851  0
EAAAAD+SourceSansPro-Regular         CID TrueType      Identity-H       yes yes yes  48860  0
EAAAAE+SourceSansPro-Regular         CID TrueType      Identity-H       yes yes yes  48869  0
EAAAAF+TimesNewRomanPS-BoldItalicMT  CID TrueType      Identity-H       yes yes yes  48878  0
EAAAAG+SourceSansPro-Regular         CID TrueType      Identity-H       yes yes yes  48887  0
EAAAAH+TimesNewRomanPS-BoldMT        CID TrueType      Identity-H       yes yes yes  48896  0
EAAAAI+SourceSansPro-Regular         CID TrueType      Identity-H       yes yes yes  48905  0
EAAAAJ+TimesNewRomanPS-ItalicMT      CID TrueType      Identity-H       yes yes yes  48914  0
EAAABA+ArialMT                       CID TrueType      Identity-H       yes yes yes  48923  0
EAAABB+Arial-BoldItalicMT            CID TrueType      Identity-H       yes yes yes  48932  0
EAAABC+Arial-BoldMT                  CID TrueType      Identity-H       yes yes yes  48941  0
EAAABD+Arial-ItalicMT                CID TrueType      Identity-H       yes yes yes  48950  0
EAAABE+SourceSansPro-Regular         CID TrueType      Identity-H       yes yes yes  48959  0
EAAABF+SourceSansPro-Regular         CID TrueType      Identity-H       yes yes yes  48968  0
```

**Comment by CAMOBAP** [comment]
PRs:
 - https://github.com/metanorma/isodoc/pull/286
 - https://github.com/metanorma/metanorma-bipm/pull/134

I need to add some tests to prevent in future

**Comment by CAMOBAP** [comment]
@Intelligent2013 @ronaldtse maybe you can suggest where I can take a minimal XML to be used as input for `mn2pdf`. I have checked https://github.com/metanorma/mn2pdf/tree/master/src/test/resources but all of them are ~200kb or more

**Comment by ronaldtse** [comment]
@Intelligent2013 here's the trace for manually executing mn2pdf via JAR:

```sh
$ java -jar /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/mn2pdf-1.29/lib/../bin/mn2pdf.jar --xml-file "bilingual-brochure/collection.presentation.xml" --xsl-file "/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-bipm-1.0.7/lib/isodoc/bipm/bipm.brochure.xsl" --pdf-file "bilingual-brochure/collection.pdf" --split-by-language
mn2pdf 


Preparing...
Input: Fonts path (~/.metanorma/fonts)
Input: XML (bilingual-brochure/collection.presentation.xml)
Input: XSL (/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-bipm-1.0.7/lib/isodoc/bipm/bipm.brochure.xsl)
Output: PDF (bilingual-brochure/collection.pdf)

[INFO] XSL-FO file preparation...
WARNING: Font file '/Users/me/.metanorma/fonts/WorkSans-Thin.ttf' (font name 'Work Sans', font style 'normal', font weight '100') doesn't exist. Replaced by '/Users/me/.metanorma/fonts/SourceSansPro-Regular.ttf'.
WARNING: Font file '/Users/me/.metanorma/fonts/WorkSans-ThinItalic.ttf' (font name 'Work Sans', font style 'italic', font weight '100') doesn't exist. Replaced by '/Users/me/.metanorma/fonts/SourceSansPro-It.ttf'.
WARNING: Font file '/Users/me/.metanorma/fonts/WorkSans-ExtraLight.ttf' (font name 'Work Sans', font style 'normal', font weight '200') doesn't exist. Replaced by '/Users/me/.metanorma/fonts/SourceSansPro-Regular.ttf'.
WARNING: Font file '/Users/me/.metanorma/fonts/WorkSans-ExtraLightItalic.ttf' (font name 'Work Sans', font style 'italic', font weight '200') doesn't exist. Replaced by '/Users/me/.metanorma/fonts/SourceSansPro-It.ttf'.
WARNING: Font file '/Users/me/.metanorma/fonts/WorkSans-Light.ttf' (font name 'Work Sans', font style 'normal', font weight '300') doesn't exist. Replaced by '/Users/me/.metanorma/fonts/SourceSansPro-Regular.ttf'.
WARNING: Font file '/Users/me/.metanorma/fonts/WorkSans-LightItalic.ttf' (font name 'Work Sans', font style 'italic', font weight '300') doesn't exist. Replaced by '/Users/me/.metanorma/fonts/SourceSansPro-It.ttf'.
WARNING: Font file '/Users/me/.metanorma/fonts/WorkSans-Regular.ttf' (font name 'Work Sans', font style 'normal', font weight 'normal') doesn't exist. Replaced by '/Users/me/.metanorma/fonts/SourceSansPro-Regular.ttf'.
WARNING: Font file '/Users/me/.metanorma/fonts/WorkSans-Italic.ttf' (font name 'Work Sans', font style 'italic', font weight 'normal') doesn't exist. Replaced by '/Users/me/.metanorma/fonts/SourceSansPro-It.ttf'.
WARNING: Font file '/Users/me/.metanorma/fonts/WorkSans-Medium.ttf' (font name 'Work Sans', font style 'normal', font weight '500') doesn't exist. Replaced by '/Users/me/.metanorma/fonts/SourceSansPro-Regular.ttf'.
WARNING: Font file '/Users/me/.metanorma/fonts/WorkSans-MediumItalic.ttf' (font name 'Work Sans', font style 'italic', font weight '500') doesn't exist. Replaced by '/Users/me/.metanorma/fonts/SourceSansPro-It.ttf'.
WARNING: Font file '/Users/me/.metanorma/fonts/WorkSans-SemiBold.ttf' (font name 'Work Sans', font style 'normal', font weight '600') doesn't exist. Replaced by '/Users/me/.metanorma/fonts/SourceSansPro-Regular.ttf'.
WARNING: Font file '/Users/me/.metanorma/fonts/WorkSans-SemiBoldItalic.ttf' (font name 'Work Sans', font style 'italic', font weight '600') doesn't exist. Replaced by '/Users/me/.metanorma/fonts/SourceSansPro-It.ttf'.
WARNING: Font file '/Users/me/.metanorma/fonts/WorkSans-Bold.ttf' (font name 'Work Sans', font style 'normal', font weight 'bold') doesn't exist. Replaced by '/Users/me/.metanorma/fonts/SourceSansPro-Bold.ttf'.
WARNING: Font file '/Users/me/.metanorma/fonts/WorkSans-BoldItalic.ttf' (font name 'Work Sans', font style 'italic', font weight 'bold') doesn't exist. Replaced by '/Users/me/.metanorma/fonts/SourceSansPro-BoldIt.ttf'.
WARNING: Font file '/Users/me/.metanorma/fonts/WorkSans-ExtraBold.ttf' (font name 'Work Sans', font style 'normal', font weight '800') doesn't exist. Replaced by '/Users/me/.metanorma/fonts/SourceSansPro-Regular.ttf'.
WARNING: Font file '/Users/me/.metanorma/fonts/WorkSans-ExtraBoldItalic.ttf' (font name 'Work Sans', font style 'italic', font weight '800') doesn't exist. Replaced by '/Users/me/.metanorma/fonts/SourceSansPro-It.ttf'.
WARNING: Font file '/Users/me/.metanorma/fonts/WorkSans-Black.ttf' (font name 'Work Sans', font style 'normal', font weight '900') doesn't exist. Replaced by '/Users/me/.metanorma/fonts/SourceSansPro-Regular.ttf'.
WARNING: Font file '/Users/me/.metanorma/fonts/WorkSans-BlackItalic.ttf' (font name 'Work Sans', font style 'italic', font weight '900') doesn't exist. Replaced by '/Users/me/.metanorma/fonts/SourceSansPro-It.ttf'.

java.awt.FontFormatException: bad pfa font
	at java.desktop/sun.font.Type1Font.verifyPFA(Type1Font.java:321)
	at java.desktop/sun.font.Type1Font.verify(Type1Font.java:299)
	at java.desktop/sun.font.Type1Font.<init>(Type1Font.java:172)
	at java.desktop/sun.font.SunFontManager.createFont2D(SunFontManager.java:2258)
	at java.desktop/java.awt.Font.<init>(Font.java:615)
	at java.desktop/java.awt.Font.createFont(Font.java:1219)
	at com.metanorma.fop.fontConfig.updateFontsForGraphicsEnvironment(fontConfig.java:687)
	at com.metanorma.fop.fontConfig.updateConfig(fontConfig.java:361)
	at com.metanorma.fop.fontConfig.getConfig(fontConfig.java:649)
	at com.metanorma.fop.mn2pdf.runSecondPass(mn2pdf.java:625)
	at com.metanorma.fop.mn2pdf.convertmn2pdf(mn2pdf.java:231)
	at com.metanorma.fop.mn2pdf.main(mn2pdf.java:522)
Apr 09, 2021 6:05:30 PM org.apache.fop.apps.FopConfParser configure
INFO: Default page-height set to: 11.00in
Apr 09, 2021 6:05:30 PM org.apache.fop.apps.FopConfParser configure
INFO: Default page-width set to: 8.50in
[INFO] Rendering into intermediate format for index preparation...
[INFO] Intermediate format. Rendered page #1.
[INFO] Intermediate format. Rendered page #2.
[INFO] Intermediate format. Rendered page #3.
[INFO] Intermediate format. Rendered page #4.
[INFO] Intermediate format. Rendered page #5.
[INFO] Intermediate format. Rendered page #6.
[INFO] Intermediate format. Rendered page #7.
[INFO] Intermediate format. Rendered page #8.
[INFO] Intermediate format. Rendered page #9.
[INFO] Intermediate format. Rendered page #10.
...
```

**Comment by CAMOBAP** [comment]
@Intelligent2013 if I understand it correctly if we will change `~/.metanorma/fonts` to `~/.fontist/fonts`, `--font-manifest` will be not required, right?

**Comment by ronaldtse** [comment]
But @CAMOBAP we will still want to namespace the fonts used by Metanorma in case? Not everyone uses Fontist.

**Comment by CAMOBAP** [comment]
@ronaldtse got you in this case PRs above should solve the problem https://github.com/metanorma/bipm-si-brochure/issues/108#issuecomment-816568801 - feel free to review

**Comment by Intelligent2013** [comment]
> @Intelligent2013 @ronaldtse maybe you can suggest where I can take a minimal XML to be used as input for `mn2pdf`. I have checked https://github.com/metanorma/mn2pdf/tree/master/src/test/resources but all of them are ~200kb or more

@CAMOBAP for testing purpose you can use this xml: 
[collection.mintest.presentation.zip](https://github.com/metanorma/bipm-si-brochure/files/6284947/collection.mintest.presentation.zip)

**Comment by Intelligent2013** [comment]
> @Intelligent2013 here's the trace for manually executing mn2pdf via JAR:

@ronaldtse 
In
```$ java -jar /Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/mn2pdf-1.29/lib/../bin/mn2pdf.jar --xml-file "bilingual-brochure/collection.presentation.xml" --xsl-file "/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-bipm-1.0.7/lib/isodoc/bipm/bipm.brochure.xsl" --pdf-file "bilingual-brochure/collection.pdf" --split-by-language
```

there isn't parameter `--font-manifest <file>` for fontist manifest file.
If `--font-manifest` is not specified, then mn2pdf will find fonts in the folder ~/.metanorma/fonts, and will download Source* and Stix2Math fonts.
If `--font-manifest` specified, then mn2pdf uses all fonts in paths specified in manifest file.


@ronaldtse I don't know what does mean `java.awt.FontFormatException: bad pfa font` error.

**Comment by Intelligent2013** [comment]
> 
> 
> @Intelligent2013 if I understand it correctly if we will change `~/.metanorma/fonts` to `~/.fontist/fonts`, `--font-manifest` will be not required, right?

Fontist installs al required fonts for concrete flafor. We should inform to mn2pdf about these fonts (font name, style and file path). mn2pdf has some default config with fonts, but it's not robust in some case.

**Comment by ronaldtse** [comment]
@CAMOBAP 
> can you confirm that the attached sample use the correct fonts?

Nope, they are not using the correct fonts. 

As @anermina posted, the left is correct, right is incorrect. The files you listed have the display of the right side.

![](https://user-images.githubusercontent.com/55683568/111870489-571b6180-8985-11eb-90e3-99111f6a083c.png)

**Comment by ronaldtse** [comment]
I was able to generate with the correct fonts by adding `-f ~/.fontist/fonts` to the mn2pdf.jar call, which confirms that the fonts and the PDF work (just a matter of not finding the fonts).

<img width="552" alt="Screenshot 2021-04-10 at 3 03 34 AM" src="https://user-images.githubusercontent.com/11865/114228653-56d11d80-99a9-11eb-87d9-02ed76fb1cab.png">

@CAMOBAP 's fixes to isodoc and metanorma-bipm should correctly pass the font manifests to mn2pdf.

**Comment by CAMOBAP** [comment]
@ronaldtse one more part is missing here https://github.com/metanorma/metanorma/blob/master/lib/metanorma/collection_renderer.rb#L74 we don't pass font manifest for collection.pdf, I will take care of it

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP !

**Comment by CAMOBAP** [comment]
- metanorma/isodoc#286
    - metanorma/metanorma-standoc#456
       - metanorma PR on the way (updating unit tests)
 - metanorma/metanorma-bipm#134

Local [collection.pdf](https://github.com/metanorma/bipm-si-brochure/files/6289696/collection.pdf) now looks correct

**Comment by ronaldtse** [comment]
Looks correct! @CAMOBAP is the GHA generated version also correct?

**Comment by CAMOBAP** [comment]
> is the GHA generated version also correct?

The fix still on PR "stage"

@ronaldtse @opoudjis could you please review those PRs together, I feel like I can missing something

**Comment by ronaldtse** [comment]
Closing since this is done.
