### ISSUE TITLE
Split off individual issues from BIPM publishing department comment files

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#112]
We’ve received feedback from BIPM’s English version, their publishing department gave over 1,100 comments. 

They recognize most of these being repetitive comments on a few minor issues, but there are some real ones. 

There are two copies of the commented document:
1. With all 1,100 comments including minor and repetitive issues 
2. A cut-down version with repetitive issues removed. 

I will post the files shortly.

**Comment by ronaldtse** [comment]
Full comments (1,100 comments):
[si-brochure-enfr_rs_030621.pdf](https://github.com/metanorma/bipm-si-brochure/files/6645205/si-brochure-enfr_rs_030621.pdf)

Only important comments (480 comments):
[si-brochure-enfr_rs_030621 - essentiel comments.pdf](https://github.com/metanorma/bipm-si-brochure/files/6645207/si-brochure-enfr_rs_030621.-.essentiel.comments.pdf)

Many comments originate from the following general issues:

> 1. Use of the solidus (/), which according to ISO 80000-1 shall not have spaces on both sides: “J/K” but not “J / K” .

RT: This is a math issue, we can fix this in either the MathML or the PDF.

> 2. Grouping of decimals by three. At present the spaces which are inserted between the groups of three are very small and in most cases indistinct.

RT: This is a also math issue, we can insert extra spaces in between the decimal groups in MathML.

> There are also comments on the numbering of bullet points in lists. [...] we already had some discussions on this. There might be some differences from the original Brochure due to the stricter layout rules in the generation of the pdf from the XML. Please have a look and decide what could be done, taking into account our earlier agreements. I understand that not all details of the present Brochure can be reproduced identically, but at least the reproductions of the historical CGPM and CIPM decision in Appendix 1 should be as close as possible.

Need help from @manuel489 to see how we can resolve these.

@manuel489 can you help create issues for related tasks? I think we might have around 100 real issues to deal with. From what I see, they are mostly presentational but there are also some encoding issues.

Thanks!

cc: @opoudjis @Intelligent2013

**Comment by manuel489** [comment]
Ok @ronaldtse

**Comment by ronaldtse** [comment]
@manuel489 I've created #157 to track the last issues. Can we close this issue now? Thanks.

**Comment by manuel489** [comment]
Ok
