### ISSUE TITLE
BIPM review: no gaps between solidus symbol `/`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#114]
This is a general comment that applies to many locations.

No gaps should exist in around the solidus `/` symbol as according to ISO 80000. This is seen in both units and math rendering.

It seems to be resolvable via adding extra spaces in MathML or tweaking the PDF rendering.

<img width="611" alt="Screenshot 2021-06-14 at 10 34 39 AM" src="https://user-images.githubusercontent.com/11865/121832210-23d63d80-ccfc-11eb-8be6-661be5f1124b.png">

**Comment by Intelligent2013** [comment]
Xslt updated. Gaps reduced before and after `/`:
![image](https://user-images.githubusercontent.com/5559926/121893361-8d6b4180-cd26-11eb-80e3-b08696a5e3e2.png)
