### ISSUE TITLE
BIPM review: numbers grouped in decimal groups have indistinct spaces in between

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#115]
The spacing between decimal groups are occasionally indistinct, perhaps due to the rendering. This can be fixed either in MathML (by adding extra spaces) or in PDF rendering (by preventing the compression of formulas to a certain extent).

<img width="622" alt="image" src="https://user-images.githubusercontent.com/11865/121832354-6d268d00-ccfc-11eb-8047-04ba7a406276.png">

**Comment by Intelligent2013** [comment]
I can't repeat this issue. PDF looks ok:
![image](https://user-images.githubusercontent.com/5559926/121849039-87a83880-ccf3-11eb-911b-22cdc9e71ab3.png)

**Comment by ronaldtse** [comment]
@Intelligent2013 the review says that the spacing is not notable enough.

I see this issue in macOS Preview:

<img width="806" alt="Screenshot 2021-06-14 at 3 00 14 PM" src="https://user-images.githubusercontent.com/11865/121851864-3d3db080-cd21-11eb-8f21-cba41dd3b2b5.png">

Also in macOS Acrobat Reader:

<img width="1003" alt="Screenshot 2021-06-14 at 3 02 11 PM" src="https://user-images.githubusercontent.com/11865/121852058-84c43c80-cd21-11eb-8055-c6de7c12f6be.png">

**Comment by Intelligent2013** [comment]
In the source xml there are 'narrow non-break spaces` between decimal groups:
```xml
<math xmlns="http://www.w3.org/1998/Math/MathML">
	<mi>c</mi>
	<mo>=</mo>
	<mn>299&#8239;792&#8239;458</mn>
	<mo rspace="thickmathspace">&#8290;</mo>
	<mrow xref="U_m/s">
		<mi mathvariant="normal">m</mi>
		<mo>/</mo>
		<mi mathvariant="normal">s</mi>
	</mrow>
</math>
```
 Source PDF has simple spaces. I've modified xslt to replace `&#8290;` chars by spaces in `mn` elements. Resulted PDF:
 
![image](https://user-images.githubusercontent.com/5559926/121892785-d8388980-cd25-11eb-9f9a-0dacff4525dc.png)

**Comment by opoudjis** [comment]
Sigh...

The use of U+202F in the XML reflects correct French typographical practice, of using the Narrow No-Break Space (NNBSP), U+202F (&#8239;  not &#8290;) to separate blocks of numbers. twitter-cldr does this explicitly, and it is also noted in https://en.wikipedia.org/wiki/Non-breaking_space

> Also starting from release 34 of Unicode Common Locale Data Repository (CLDR) the NNBSP is used in numbers as thousands group separator for French locale.

BIPM is clearly following French typographical practice in how it treats numbers.

Their use of normal space, disappointingly, also shows that BIPM are unaware of correct French typographical practice.

This is in effect correct typography, being uncorrected to match the PDF. Well, so be it; the XML and HTML are still correct. Nothing for me to do.

**Comment by opoudjis** [comment]
@Intelligent2013 , just realised:

> I've modified xslt to replace &#8290; chars by spaces

&#8290; is a narrow non-breaking space. Could you please replace it with a normal non-breaking space? We don't want numbers line-breaking across two lines.

**Comment by ronaldtse** [comment]
Justification:

From Unicode CLDR v38 onwards, the French locale is shown to use `U+202F` for the "group separator". In v33 at least, French was considered identical to English in the default group which uses `U+00A0`. Now it is separated.

https://unicode-org.github.io/cldr-staging/charts/38/by_type/numbers.symbols.html

<img width="943" alt="Screenshot 2021-07-27 at 11 17 05 AM" src="https://user-images.githubusercontent.com/11865/127089818-d0cd2cd9-2718-4e0d-afa1-ec45a40b5460.png">

**Comment by ronaldtse** [comment]
As per discussion with @opoudjis this is more complex.

I have sought guidance from BIPM as follows.

> In the previous review there were many comments that the spacing between number groups were too narrow.
> 
> This problem stemmed from a recent (a few months ago) change in Unicode where the “group separator” symbol has changed.
> 
> Previously, both the French and English locales used the `U+00A0` (non-breaking space) symbol for the "group separator”.
> 
> Since Unicode CLDR v38 (Dec 2020), the French locale has been updated to use code point `U+202F` (narrow no-break space), while English still uses `U+00A0`. This caused the difference in presentation space width between number groups.
> 
> Interestingly yet, this change was actually made in response to address a recommendation from the SI Brochure!
> 
> > The primary use of NNBSP (narrow no-break-space) is as a group separator in numbers for locales grouping digits into triads using space, listed in L2/19-112. These locales actually implement a recommendation from the International System of Units (BIPM). The requirement is that the group separator space be always narrower than a digit, not only by default, but always in display. Therefore, that use case should be mentioned first.
> (https://www.unicode.org/L2/L2020/20008-core-text.pdf)
> 
> This was why the French locale uses NNBSP instead of NBSP.
> 
> The rationale was proposed by a Marcel Schneider (charupdate@orange.fr) to Unicode in 2019. He referred to the SI Brochure edition 8 (2006):
> 
> SI Brochure e8 5.3.4 states:
> > Following the 9th CGPM (1948, Resolution 7) and the 22nd CGPM (2003, Resolution 10), for numbers with many digits the digits may be divided into groups of three by a thin space, in order to facilitate reading. Neither dots nor commas are inserted in the spaces between groups of three. However, when there are only four digits before or after the decimal marker, it is customary not to use a space to isolate a single digit. The practice of grouping digits in this way is a matter of choice; it is not always followed in certain specialized applications such as engineering drawings, financial statements, and scripts to be read by a computer.
> 
> SI Brochure e9 5.4.4 says:
> > Following the 9th CGPM (1948, Resolution 7) and the 22nd CGPM (2003, Resolution 10), for numbers with many digits the digits may be divided into groups of three by a space, in order to facilitate reading. Neither dots nor commas are inserted in the spaces between groups of three. However, when there are only four digits before or after the decimal marker, it is customary not to use a space to isolate a single digit. The practice of grouping digits in this way is a matter of choice; it is not always followed in certain specialized applications such as engineering drawings, financial statements and scripts to be read by a computer.
> 
> So this is a case of an outdated recommendation being implemented, and coming back to haunt the authoritative document itself :-)
> 
> In the meantime, we will render the full non-breaking space (U+00A0) as the “group separator”, but will await your guidance for what to encode in the XML (thin space or normal space).
> 
> (This is a subject of ongoing debate at Unicode here: https://unicode-org.atlassian.net/browse/CLDR-11423)
>

**Comment by ronaldtse** [comment]
In any case, the BIPM SI Brochure wants to have a full non-breaking space for group separation. So we have to do that.

**Comment by opoudjis** [comment]
With the added issue that nnbsp is in fact official French practice, so it is not impossible that the BIPM SI Brochure would diverge based on language.

But @Intelligent2013 this becomes a Presentation XML issue; I'll change the nnbsp to nbsp, for English, and if they confirm, also for French.

**Comment by Intelligent2013** [comment]
> `&#8290;` is a narrow non-breaking space. Could you please replace it with a normal non-breaking space? We don't want numbers line-breaking across two lines

> But @Intelligent2013 this becomes a Presentation XML issue; I'll change the nnbsp to nbsp, for English, and if they confirm, also for French.

@opoudjis ok. Just for information, jEuclid generates SVG image for mathml in the one line, it doesn't breaks the line to fit into some area.

**Comment by ronaldtse** [comment]
We have clarification from Michael Stock from the BIPM:

> Please use the normal space for the encoding in XML.
>  
> The thin space was indeed mentioned in the English text of the 8th edition of the SI brochure. Interestingly, the French text only mentions “espace” = “space”. In the 9th edition both language version only use “space”. The CGPM resolutions from 1948 and 2003 which are referred to in both editions of the SI brochure also don’t mention a “thin space”.

This means that the Unicode change is based on faulty information and is **wrong**. @opoudjis can you point the Unicode people to this clarified information from BIPM?

The separator will stay as a normal space.

**Comment by opoudjis** [comment]
No further action within metanorma

**Comment by ronaldtse** [comment]
Thanks @opoudjis !

**Comment by opoudjis** [comment]
I am disgusted at the typographic cluelessness that is replacing nnbsp with nbsp globally, but if SDOs want to enshrine bad typography officially, it's not my job to tell them they are wrong, it's the Imprimerie Nationale's.

**Comment by opoudjis** [comment]
> This means that the Unicode change is based on faulty information and is wrong. @opoudjis can you point the Unicode people to this clarified information from BIPM?

Inasmuch as Unicode is replicating for French the practice of the French National Printer, which takes priority over whatever BIPM thinks French national norms are: No, I will not.
