### ISSUE TITLE
BIPM review: should have extra spacing around multiplication `x` sign

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#116]
> the spaces either side of the multiplication signs are less distinct than in the PDF

<img width="462" alt="Screenshot 2021-06-14 at 10 38 31 AM" src="https://user-images.githubusercontent.com/11865/121832472-af4fce80-ccfc-11eb-9aba-6c19ed322b17.png">

**Comment by Intelligent2013** [comment]
Xslt updated. Extra spacing added around `x` sign:
![image](https://user-images.githubusercontent.com/5559926/121893017-28175080-cd26-11eb-8927-6860628982d4.png)

**Comment by opoudjis** [comment]
Nothing for me to do, this is rendering issue purely.
