### ISSUE TITLE
BIPM review: is it possible to keep a table on the same page?

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#117]
Question for @Intelligent2013 

<img width="754" alt="Screenshot 2021-06-14 at 10 39 39 AM" src="https://user-images.githubusercontent.com/11865/121832526-d7d7c880-ccfc-11eb-8e25-04f5adb2fc43.png">

**Comment by Intelligent2013** [comment]
@ronaldtse in xsl-fo there is a property `keep-together.within-column` that allows to achieve this behavior. There is a few cases:
1. we can set `keep-together.within-column` globally for each BIPM table. It allows to solve this concrete issue:
![image](https://user-images.githubusercontent.com/5559926/121890104-a5d95d00-cd22-11eb-8473-4237635ad77d.png)

but it has a side-effect, when there is enough space on page, but the table starts on the next page:
![image](https://user-images.githubusercontent.com/5559926/121890621-3879fc00-cd23-11eb-998b-b0901cbee72f.png)

2. if it would be possible to set property `keep-together` for concrete table in adoc, then xslt could be support it.
3. the most simple solution - put pagebreak instruction `<<<` in adoc before table:
```adoc

<<<

[[table2]]
.SI base units
```

**Comment by ronaldtse** [comment]
> the most simple solution - put pagebreak instruction <<< in adoc before table:

@Intelligent2013 can we do this and close the task? Thanks!

**Comment by Intelligent2013** [comment]
Done.
