### ISSUE TITLE
BIPM review: check units encoding

### ISSUE THREAD

**Issue by manuel489** [metanorma/bipm-si-brochure#119]
*In relation to https://github.com/metanorma/bipm-si-brochure/issues/112*

From BIPM:

![issue1](https://user-images.githubusercontent.com/33627611/121900689-ad354200-ccf3-11eb-9fd8-0ee80dd0abe8.PNG)

I don't see the problem in these cases.
The markup looks correct:

````
... and candela(((candela (stem:["unitsml(cd)"])))), with unit symbols stem:["unitsml(s)"], 
stem:["unitsml(m)"], stem:["unitsml(kg)"], stem:["unitsml(A)"], stem:["unitsml(K)"], stem:["unitsml(mol)"], and stem:["unitsml(cd)"], 
respectively, according to stem:["unitsml(Hz)" = "unitsml(s^(-1))"], stem:["unitsml(J)" = "unitsml(kg*m^2*s^(-2))"], 
stem:["unitsml(C)" = "unitsml(A*s)"], stem:["unitsml(lm)" = "unitsml(cd*m^2*m^(-2))" = "unitsml(cd*sr)"], and 
stem:["unitsml(W)" = "unitsml(kg*m^2*s^(-3))"].
````

Maybe in mac OS looks different?

**Comment by ronaldtse** [comment]
The encoding is correct in UnitsML. This may be related to one of their comments that a reader can't copy / paste units, which is a separate problem with copying math in general. Closing.
