### ISSUE TITLE
BIPM review: different size parentheses

### ISSUE THREAD

**Issue by manuel489** [metanorma/bipm-si-brochure#120]
*In relation https://github.com/metanorma/bipm-si-brochure/issues/112*

From BIPM:

![issue2-3](https://user-images.githubusercontent.com/33627611/121903635-7f9dc800-ccf6-11eb-9420-a29094abdef5.PNG)

Parentheses at denominator are in different sizes.

Here's another case:

![issue2-4](https://user-images.githubusercontent.com/33627611/121904230-02268780-ccf7-11eb-869c-54664272b9fd.PNG)

**Comment by Intelligent2013** [comment]
jEuclid automatically sets the height of `mfenced` element depends on own content, but not neighboring elements.
Now, the height increased by adding `<mspace height="1.15em"/>` if there is preceding or following `mfenced` with superscript.

![image](https://user-images.githubusercontent.com/5559926/122202993-4441fb80-cea6-11eb-8eeb-b86559c1fabe.png)

![image](https://user-images.githubusercontent.com/5559926/122203035-4f952700-cea6-11eb-9cd1-ac1e45610589.png)

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 !
