### ISSUE TITLE
BIPM review: sans-serif fonts shown as serif fonts for dimension symbols

### ISSUE THREAD

**Issue by manuel489** [metanorma/bipm-si-brochure#121]
*In relation to https://github.com/metanorma/bipm-si-brochure/issues/112*

Original:
<img width="621" alt="Screenshot 2021-06-17 at 9 44 25 PM" src="https://user-images.githubusercontent.com/11865/122408779-362ed080-cfb5-11eb-9805-c79ee0345f22.png">

Rendered:

![issue3](https://user-images.githubusercontent.com/33627611/121906622-474bb900-ccf9-11eb-896e-32ceb10fffb6.PNG)

`stem:[sf "I"]` and `stem:[sf "J"]` are showing up with serif.

**Comment by ronaldtse** [comment]
I will seek clarification from BIPM.

In any case, we do not want `stem:[sf "I"]` but with UnitsML encoding.

**Comment by ronaldtse** [comment]
Anyway the point is that the unicode points 1D5A8 and 1D5A9 are correct. The display aberration is a font-specific issue.

<img width="984" alt="Screenshot 2021-06-17 at 9 38 25 PM" src="https://user-images.githubusercontent.com/11865/122407655-5f029600-cfb4-11eb-9de0-c037f6e7572f.png">

**Comment by Intelligent2013** [comment]
Some investigation about how jEuclid works.
In jEuclid there are a list a predefined fonts for 'sans-serif', 'serif', 'monospaced', 'script', 'fraktur' and 'doublestruck'.
Example for `sans-serif`:
```
        final List<String> fontsSanserif = new ArrayList<String>(12);
        fontsSanserif.add("Verdana");
        fontsSanserif.add("Helvetica");
        fontsSanserif.add("Arial");
        fontsSanserif.add("Arial Unicode MS");
        fontsSanserif.add("Lucida Sans Unicode");
        fontsSanserif.add("Lucida Sans");
        fontsSanserif.add("Lucida Grande");
        fontsSanserif.add("DejaVu Sans");
        fontsSanserif.add("DejaVuSans");
        fontsSanserif.add("Bitstream Vera Sans");
        fontsSanserif.add("Luxi Sans");
        fontsSanserif.add("FreeSans");
        fontsSanserif.add("sansserif");

```
When we specify `mathvariant="sans-serif"`:
```xml
<mstyle mathvariant="sans-serif">
  <mtext>I</mtext>
</mstyle>
```
it means, that first found font from the list will be used for displaying text inside `<mstyle mathvariant="sans-serif">`. But not main font 'STIX Two Math`.
We've modified similar list for "script" here https://github.com/metanorma/mn-native-pdf/issues/289.
May be we need to move 'Arial' font at first place...

But I can't figure out yet why char '1D5A8' displays identical to 49. Will investigate...

**Comment by ronaldtse** [comment]
@Intelligent2013 we need to ensure STIX Two Math is really used as the first font for jEuclid...

**Comment by Intelligent2013** [comment]
From jEuclid sources (`jeuclid\jeuclid-core\src\main\resources\net\sourceforge\jeuclid\UnicodeData.txt`):
```
1D5A8;MATHEMATICAL SANS-SERIF CAPITAL I;Lu;0;L;<font> 0049;;;;N;;;;;
```
`jeuclid\jeuclid-core\src\main\java\net\sourceforge\jeuclid\elements\support\text\CharacterMapping.java`:
```
...
private static final int HIGHPLANE_MATH_CHARS_START = 0x1D400;
...
final boolean force = (codepoint >= CharacterMapping.HIGHPLANE_MATH_CHARS_START)
        && ((FontFamily.SANSSERIF.equals(fam)) || (FontFamily.SERIF
                .equals(fam)));
if (force) {
    this.forceSet.add(codepoint);
}


final CodePointAndVariant cpav = new CodePointAndVariant(mapsTo,
        new MathVariant(awtStyle, fam));
this.extractAttrs.put(codepoint, cpav);
final Map<Integer, Integer[]> ffmap = this.getFFMap(fam);
final Integer[] ia = this.getMapsTo(mapsTo, ffmap);
ia[awtStyle] = codepoint;
...
```

It means that character '1D5A8'  (> 0x1D400) displays as 49 but with sans-serif font.

**Comment by Intelligent2013** [comment]
As workaround solution we can use:
```xml
<math>
 <mglyph fontfamily="STIX Two Math" index="120232"/> 
</math>
```
then resulted PDF:
![image](https://user-images.githubusercontent.com/5559926/122431276-f9ef7600-cf9c-11eb-93a2-b6d14ac4045b.png)
...
![image](https://user-images.githubusercontent.com/5559926/122431319-05db3800-cf9d-11eb-8207-954c3a4c67f4.png)

**Comment by Intelligent2013** [comment]
Or turn-off codepoint checking in the module `CharacterMapping.java`. But I don't know about side-effect.

**Comment by ronaldtse** [comment]
@Intelligent2013 jEuclid is probably doing that for char compatibility, in case the font doesn't support a particular code point. With the current situation, It shouldn't replace the code points when the font supports that code point.

**Comment by ronaldtse** [comment]
Experimentation was done at https://github.com/metanorma/bipm-si-brochure/issues/144 , and BIPM has provided their feedback.

From Michael Stock of BIPM:

> Although the two references which you cited, ISO 80000-1 and BIPM JCGM 200:2012 do not mention anything about bolding of symbols for dimensions, it is quite unusual to use bold letters as symbols for dimensions. In fact, bold letters are usually used for matrices.
>
> I would prefer your last table, for the reason that visually it gives the best result. In my opinion the risk that someone would copy the sans serif theta from this table and get a serif theta is acceptable.

The symbols that BIPM wants to use is provided in the last table, i.e.:

```adoc
[%unnumbered]
[[table3_4]]
.all "Dimensions" symbols use Latin “plain” capital characters, except theta uses Greek “normal” capital character (U+03F4)
[cols="<,<,<"]
|===
| Base quantity | Typical symbol for quantity | Symbol for dimension

| time | stem:[t] | stem:[sf "&#x1D5B3;"]
| length | stem:[l, x, r], etc. | stem:[sf "&#x1D5AB;"]
| mass | stem:[m] | stem:[sf "&#x1D5AC;"]
| electric current | stem:[ii(I), i] | stem:[sf "&#x1D5A8;"]
| thermodynamic temperature | stem:[ii(T)] | stem:[sf "&#x03F4;"]
| amount of substance | stem:[n] | stem:[sf "&#x1D5AD;"]
| luminous intensity | stem:[ii(I)_("v")] | stem:[sf "&#x1D5A9;"]
|===
```


![](https://user-images.githubusercontent.com/5559926/124644932-7a6a0e00-de9b-11eb-867d-9e3dae9d6745.png)

@Intelligent2013 can you help update the ADoc source and ensure the output is correct? Thanks!

**Comment by Intelligent2013** [comment]
Done.
En:
![image](https://user-images.githubusercontent.com/5559926/125769131-0b66b3d1-35cf-4f97-8956-b37e43d44a8b.png)
Fr:
![image](https://user-images.githubusercontent.com/5559926/125769487-2f9eb365-0137-45bc-a0fc-08c22c64c865.png)

**Comment by ronaldtse** [comment]
Thanks!
