### ISSUE TITLE
BIPM review: some quantity symbol fonts show differently to original version

### ISSUE THREAD

**Issue by manuel489** [metanorma/bipm-si-brochure#122]
*In relation to https://github.com/metanorma/bipm-si-brochure/issues/112*

Some fonts are shown different to original version.

From BIPM:

![issue4-1](https://user-images.githubusercontent.com/33627611/121920719-4cfbcb80-cd06-11eb-9cb9-50bdeb7c422e.PNG)

Original version:

![issue4-2](https://user-images.githubusercontent.com/33627611/121920809-64d34f80-cd06-11eb-85e1-5a248d46b09a.PNG)

For *"speed, velocity"* and *"specific volume"*, I think I can write `stem:[upsilon]` and `stem:[nu]` respectively for better matching:

![issue4-3](https://user-images.githubusercontent.com/33627611/121921613-27bb8d00-cd07-11eb-93db-f727c5ea0d8b.PNG)
![issue4-4](https://user-images.githubusercontent.com/33627611/121921620-2a1de700-cd07-11eb-989b-5029c294f13c.PNG)

But, for *"acceleration"*,  I'm not sure.

**Comment by ronaldtse** [comment]
@manuel489 we had this same question before, and the specific guidance from Michael Stock (Director of Physics at BIPM) was to write "v", not "upsilon" or "nu".

Can you find the original ticket and link it here?

**Comment by opoudjis** [comment]
https://github.com/metanorma/metanorma-bipm/issues/2#issuecomment-688231121

**Comment by ronaldtse** [comment]
Thanks @opoudjis , the specific comment is this: https://github.com/metanorma/metanorma-bipm/issues/2#issuecomment-692057111 . Closing this issue as resolved.
