### ISSUE TITLE
BIPM review: indent line after line-break in table environment.

### ISSUE THREAD

**Issue by manuel489** [metanorma/bipm-si-brochure#123]
From BIPM:

![issue5](https://user-images.githubusercontent.com/33627611/121922529-0d35e380-cd08-11eb-9ea6-013d9954e0f7.PNG)

BIPM is requesting to indent lines after line break so that it doesn't look like two separate derived quantities.

**Comment by Intelligent2013** [comment]
XSLT updated. Now, it adds hanging indent for first table cell in a row.
![image](https://user-images.githubusercontent.com/5559926/122241831-87629580-cecb-11eb-9e37-9c48dc05a892.png)

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 !
