### ISSUE TITLE
BIPM review: remove sentence part in header

### ISSUE THREAD

**Issue by manuel489** [metanorma/bipm-si-brochure#124]
*In relation to https://github.com/metanorma/bipm-si-brochure/issues/112*

From BIPM:

![issue7](https://user-images.githubusercontent.com/33627611/121942295-52651000-cd1e-11eb-806c-a1e65f88cd97.PNG)

Original version:

![issue7-2](https://user-images.githubusercontent.com/33627611/121942403-6f99de80-cd1e-11eb-8a70-15c9b128b70b.PNG)

**Comment by manuel489** [comment]
Also this part:

![issue9-1](https://user-images.githubusercontent.com/33627611/121944852-226b3c00-cd21-11eb-83bd-1eab38c42646.PNG)

Original:
![issue9-2](https://user-images.githubusercontent.com/33627611/121944883-28f9b380-cd21-11eb-9d8e-6bbbc315dd05.PNG)

**Comment by Intelligent2013** [comment]
Xslt displays 1st level clause's titles in the page's header. But BIPM in original PDF displays a short form, e.g.:

3. `Decimal multiples and sub-multiples of SI units` -> `Decimal multiples and sub-multiples`
4. `Non-SI units that are accepted for use with the SI`-> `Non-SI units`
5. `Writing unit symbols and names, and expressing the values of quantities` -> `Writing unit symbols and names`

I propose workaround solution (actually bad, but I don't figure out what we can do more here) - put the character `zero-width space` as `divider` into the title:
```adoc
== Non-SI units&#x200b; that are accepted for use with the SI`
```

I've updated xslt and now it display title in header before zero-width space:
![image](https://user-images.githubusercontent.com/5559926/122252599-28554e80-ced4-11eb-9a66-e98b0681e7a9.png)

![image](https://user-images.githubusercontent.com/5559926/122252764-4458f000-ced4-11eb-9c02-e35948fd7e20.png)

**Comment by ronaldtse** [comment]
I'm not convinced this is the correct solution. We will seek clarification.

**Comment by ronaldtse** [comment]
From Michael Stock of BIPM:

> I agree to use the full section headings.

So there is nothing to be done here, @Intelligent2013 can you revert the last "attempt fix"? Thanks.

**Comment by Intelligent2013** [comment]
@ronaldtse actually code reverted back (commented) earlier in https://github.com/metanorma/mn-native-pdf/commit/33ea370c15ce0c6a08e267e59f38777792dd2a3e, now it deleted at all.
