### ISSUE TITLE
BIPM review: remove space between comma and math symbol

### ISSUE THREAD

**Issue by manuel489** [metanorma/bipm-si-brochure#125]
*In relation to https://github.com/metanorma/bipm-si-brochure/issues/112*

From BIPM:
![issue10](https://user-images.githubusercontent.com/33627611/121946496-fd77c880-cd22-11eb-9c1d-0ec1efa15d82.PNG)

Original:
![issue10-2](https://user-images.githubusercontent.com/33627611/121947253-d8378a00-cd23-11eb-93ac-ce2401d41a00.PNG)

I remember that we had previously aggreged on introducing a space by default after a comma in math environment.
But maybe we can make an exception for prefixes?

Ping @ronaldtse

**Comment by Intelligent2013** [comment]
Space was added for https://github.com/metanorma/mn2pdf/issues/61. Xslt adds small space after `mi` (if not next mtext=non-break space).

For example, this mathml:
```xml
<math xmlns="http://www.w3.org/1998/Math/MathML">
	<msub>
		<mrow>
			<mi>c</mi>
		</mrow>
		<mrow>
			<mrow>
				<mtext>m</mtext>
				<mi>,</mi>
				<mi>p</mi>
			</mrow>
		</mrow>
	</msub>
</math>
```
becomes:
```xml
<math xmlns="http://www.w3.org/1998/Math/MathML">
	<mstyle scriptminsize="6pt">
		<msub>
			<mrow>
				<mi>c</mi>
			</mrow>
			<mrow>
				<mrow>
					<mtext>m</mtext>
					<mi>,</mi>
					<mspace width="0.5ex"/>
					<mi>p</mi>
				</mrow>
			</mrow>
		</msub>
	</mstyle>
</math>
```

Now, I've modified xslt to dismiss cases, when `mi=,` in `msub`. PDF renders so:
![image](https://user-images.githubusercontent.com/5559926/122259763-2b077200-cedb-11eb-9d6f-2489f5f6b725.png)

This modification affects only for these two cases mentioned in first post, so @manuel489 if BIPM mentioned another cases, please inform me about them.

**Comment by ronaldtse** [comment]
@Intelligent2013 we shouldn't do case-by-case fixes but only general ones. Can we either insert spaces or not insert spaces between `<mi>` items?

**Comment by Intelligent2013** [comment]
> @Intelligent2013 we shouldn't do case-by-case fixes but only general ones. Can we either insert spaces or not insert spaces between `<mi>` items?

No, in some case we need to insert space, in another no.
For example, left column - without space, right column - with space.
![image](https://user-images.githubusercontent.com/5559926/122594384-9d10c000-d06f-11eb-8b33-2433c9e2f582.png)
![image](https://user-images.githubusercontent.com/5559926/122594421-a7cb5500-d06f-11eb-8653-29f64080bd58.png)
![image](https://user-images.githubusercontent.com/5559926/122594461-b3b71700-d06f-11eb-9496-1d0afe5c1451.png)
![image](https://user-images.githubusercontent.com/5559926/122594487-bdd91580-d06f-11eb-918d-ce1beed304a5.png)
![image](https://user-images.githubusercontent.com/5559926/122594518-c893aa80-d06f-11eb-9b1f-44364a31948a.png)
![image](https://user-images.githubusercontent.com/5559926/122594536-ce898b80-d06f-11eb-9815-7cf29cd1b070.png)

If we'll remove space, then this source PDF fragment:
![image](https://user-images.githubusercontent.com/5559926/122594660-fd076680-d06f-11eb-9bce-fe977b6ed10d.png)
will render wrong:
![image](https://user-images.githubusercontent.com/5559926/122595226-d0a01a00-d070-11eb-9fe5-9a952ac8e214.png)

**Comment by ronaldtse** [comment]
I think there are two types of spaces here. 
- space in normal text, in between formulas
- space inside a math formula

Some of the examples I see can use space in normal text, eg in the table above listing "l, r, x", these are enumerations of variables i.e. multiple formulas. So there shouldn't be a problem here. 

In the first example, the space to remove is within the formula. 

Lets consider the following:
- By default, within a formula, there is no space after a comma. 
- If a "space inside a formula" is necessary, the user should encode that within the formula as a presentational directive.

**Comment by Intelligent2013** [comment]
Ok, I've removed space adding in the on-fly mathml pre-processing in the xslt.

**Comment by ronaldtse** [comment]
@manuel489 can you please help review the instances where the "spacing is too close" and find out where we want to split the formulas for normal spacing? Thanks.

**Comment by manuel489** [comment]
@ronaldtse I understand that white space inside math environment has been removed, right?
I'm not seeing this changes in my builds though:

![Capture](https://user-images.githubusercontent.com/33627611/129577823-e1b67357-22df-42b7-9087-5c7a8c048de6.PNG)

Markup:
````
[stem%unnumbered]
++++
ab, a b, a * b, a xx b, a //b, a/b, a  b^(−1).
++++
````

I'm using the latest metanorma-bipm (1.1.7) and isodoc (1.7.3) released a couple of hours ago.

**Comment by manuel489** [comment]
On the other hand, I note that the issue I've described in the description above has been solved:
![cap2](https://user-images.githubusercontent.com/33627611/129579917-726ba43c-16c9-4db0-a036-eba4765984d8.PNG)

**Comment by Intelligent2013** [comment]
> I'm not seeing this changes in my builds though:

@manuel489 stem markup contains white spaces and they converted to &#160; (non-break space), and mathml markup looks correct:

```xml
<math xmlns="http://www.w3.org/1998/Math/MathML">
	<mi>a</mi>
	<mi>b</mi>
	<mo>,</mo>
	<mtext>&#160;</mtext>
	<mi>a</mi>
	<mtext>&#160;</mtext>
	<mi>b</mi>
	<mo>,</mo>
	<mtext>&#160;</mtext>
	<mi>a</mi>
	<mo>&#8901;</mo>
	<mi>b</mi>
	<mo>,</mo>
	<mtext>&#160;</mtext>
	<mi>a</mi>
	<mo>&#215;</mo>
	<mi>b</mi>
	<mo>,</mo>
	<mtext>&#160;</mtext>
	<mi>a</mi>
	<mo>/</mo>
	<mi>b</mi>
	<mo>,</mo>
	<mtext>&#160;</mtext>
	<mfrac>
		<mrow>
			<mi>a</mi>
		</mrow>
		<mrow>
			<mi>b</mi>
		</mrow>
	</mfrac>
	<mo>,</mo>
	<mtext>&#160;</mtext>
	<mi>a</mi>
	<mtext>&#160;</mtext>
	<msup>
		<mrow>
			<mi>b</mi>
		</mrow>
		<mrow>
			<mrow>
				<mo>&#8722;</mo>
				<mn>1</mn>
			</mrow>
		</mrow>
	</msup>
	<mo>.</mo>
</math>
```

**Comment by Intelligent2013** [comment]
> On the other hand, I note that the issue I've described in the description above has been solved:

this issue solved automatically by two reasons:
- in old xml `<mi>,</mi>`, in new xml `<mo>,</mo>`, i.e. my previous changes in xslt don't have effect (it added space after `mi` with comma)
- but even in case of `<mi>,</mi>`, I've remove adding space after `mi` with command.

**Comment by manuel489** [comment]
>@manuel489 stem markup contains white spaces and they converted to   (non-break space), and mathml markup looks correct...

@Intelligent2013 yes, you are right. I had noticed that in the markup already. So I removed those spaces in the markup to see if the white spaces were gone in output, but they weren't, and that confuses me.

But ok, I'm just going to compare *generated PDF* vs *original* and see where there is need for white space to add.

**Comment by Intelligent2013** [comment]
I've checked the difference between two markups.
Adoc
1. 
```adoc
[stem%unnumbered]
++++
ab," " a " " b," " a * b," " a xx b," " a //b," " a/b," " a " " b^(−1).
++++
````
2.
```adoc
[stem%unnumbered]
++++
ab, a b, a * b, a xx b, a //b, a/b, a  b^(−1).
++++
```

xml:
```xml
<math><mi>a</mi><mi>b</mi><mo>,</mo><mtext>&#160;</mtext><mi>a</mi><mtext>&#160;</mtext><mi>b</mi><mo>,</mo><mtext>&#160;</mtext><mi>a</mi><mo>&#8901;</mo><mi>b</mi><mo>,</mo><mtext>&#160;</mtext><mi>a</mi><mo>&#215;</mo><mi>b</mi><mo>,</mo><mtext>&#160;</mtext><mi>a</mi><mo>/</mo><mi>b</mi><mo>,</mo><mtext>&#160;</mtext><mfrac><mrow><mi>a</mi></mrow><mrow><mi>b</mi></mrow></mfrac><mo>,</mo><mtext>&#160;</mtext><mi>a</mi><mtext>&#160;</mtext><msup><mrow><mi>b</mi></mrow><mrow><mrow><mo>&#8722;</mo><mn>1</mn></mrow></mrow></msup><mo>.</mo></math>
```
```xml
<math><mi>a</mi><mi>b</mi><mo>,</mo><mi>a</mi><mi>b</mi><mo>,</mo><mi>a</mi><mo>&#8901;</mo><mi>b</mi><mo>,</mo><mi>a</mi><mo>&#215;</mo><mi>b</mi><mo>,</mo><mi>a</mi><mo>/</mo><mi>b</mi><mo>,</mo><mfrac><mrow><mi>a</mi></mrow><mrow><mi>b</mi></mrow></mfrac><mo>,</mo><mi>a</mi><msup><mrow><mi>b</mi></mrow><mrow><mrow><mo>&#8722;</mo><mn>1</mn></mrow></mrow></msup><mo>.</mo></math>
```

PDF:
1. 
![image](https://user-images.githubusercontent.com/5559926/129587242-1db01432-1b3a-420c-99fe-ac16efa0654c.png)

2. 
![image](https://user-images.githubusercontent.com/5559926/129587280-ec4c5e27-4356-44d0-888a-af994371d037.png)

As you can see in the case `2.`, in xml there isn't space, but in PDF there is one. This is internal behavior of jEuclid - it adds the space after `<mo>,</mo>`. (previous version of bipm metanorma  generated `<mi>,</mi>`, therefore I had to add space via xslt, because jEuclid don't add the space after `<mi>,</mi>`).

**Comment by manuel489** [comment]
Ahh, so that explains it! We can close the subject then 😃.
Thanks @Intelligent2013!

**Comment by manuel489** [comment]
Ok, I have just found to instances where white space was needed: https://github.com/metanorma/bipm-si-brochure/commit/0376101e9272a344ccba3c45352821821ed6e46e

I think we can now close this issue @ronaldtse

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 @manuel489 !
