### ISSUE TITLE
BIPM review: minor signs look like dashes and spaces after commas

### ISSUE THREAD

**Issue by manuel489** [metanorma/bipm-si-brochure#127]
*In relation to https://github.com/metanorma/bipm-si-brochure/issues/112*

![issue12](https://user-images.githubusercontent.com/33627611/121961152-0a9db300-cd35-11eb-825b-daf017d4c6a2.PNG)

According to BIPM, there are two issues in this part:

1. *Minor signs look like dashes and there should be no space between the minus sign and the digits.*
2. *There should be no spaces after the commas*

**Comment by ronaldtse** [comment]
I'm not sure if this is an XML or PDF error.

**Comment by Intelligent2013** [comment]
2nd issue is a side-effect of https://github.com/metanorma/mn2pdf/issues/61.
All fixed, xslt updated:
![image](https://user-images.githubusercontent.com/5559926/122276581-99edc680-ceed-11eb-95cc-d4b40f3c93ca.png)

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 !
