### ISSUE TITLE
BIPM review: replace example block for side note block?

### ISSUE THREAD

**Issue by manuel489** [metanorma/bipm-si-brochure#129]
*In relation to https://github.com/metanorma/bipm-si-brochure/issues/112*

BIPM has requested to change the presentation of an example block to side note
in order to avoid breaking across pages:

![issue14-1](https://user-images.githubusercontent.com/33627611/121969966-79820880-cd43-11eb-802f-61e85ef93a39.PNG)

Original version:
![issue14-2](https://user-images.githubusercontent.com/33627611/121969997-9585aa00-cd43-11eb-9278-51687fc950d0.PNG)

Making respective changes in the markup, this would be the result:
![issue14-3](https://user-images.githubusercontent.com/33627611/121970018-a3d3c600-cd43-11eb-87b5-56e42b158d00.PNG)

Is this good enough?

**Comment by ronaldtse** [comment]
@manuel489 this is a layout issue, not an encoding issue. The updated layout looks fine.

In fact, this is the only instance of a properly encoded EXAMPLE in this document! So there are no side effects when we move this to the sidebar.

@Intelligent2013 can you help move EXAMPLEs to the sidebar?

**Comment by Intelligent2013** [comment]
@ronaldtse I can move all examples (similar to notes) to the sidebar, but in the original document there is one more example:

![image](https://user-images.githubusercontent.com/5559926/122446220-15fa1400-cfab-11eb-951a-5dd882c340f0.png)

If we move it to the sidebar, then math equation should be divided into several parts (for line breaks), and again there will be a difference between generated and resulted PDF.

We can avoid page breaks by adding `keep-together.within-column="1"` for example block:
![image](https://user-images.githubusercontent.com/5559926/122448024-0380da00-cfad-11eb-8a26-ec224228a390.png)

**Comment by ronaldtse** [comment]
In this case let us seek BIPM clarification. Are these the only 2 examples in the document?

**Comment by Intelligent2013** [comment]
> Are these the only 2 examples in the document?

yes.

**Comment by ronaldtse** [comment]
From Michael Stock of BIPM:

> I agree that the example in 5.4.6 can go for the sake of consistency in the normal text flow. Although the different examples are related to the three paragraphs on 5.4.6, I recommend that all examples should be inserted at the end of section 5.4.6 since the section is quite short.

So we can move these examples to the end of 5.4.6 as proper Examples.

> In fact, there are more examples: all the side notes in sections 5.4.2, 5.4.3, 5.4.4, 5.4.6 and 5.4.7 are examples, although most of them do not start with the word “example”. Since this has not caused a problem, leave them as side notes?

Pending decision, we prefer encoding those as proper examples, of course.

**Comment by ronaldtse** [comment]
From Michael Stock of BIPM

> I agree that the sides notes in sections 5.4.2, 5.4.3, 5.4.4, 5.4.6 and 5.4.7 could be treated as examples (within the body of the text instead as side notes), as it is already the case in 5.4.6 in the last version of the PDF you sent in April. In this case the examples should be preceded by the word ‘Example’ as in 5.4.6. In 5.4.7 this applies only to the first side note. The second on the terms billion and trillion is not an example and should remain a side note.

**Comment by ronaldtse** [comment]
@manuel489 can you help action this and provide a screenshot of the completed copy? Thanks.

**Comment by ronaldtse** [comment]
@manuel489 I've just done the changes in #151, but don't merge it yet since I couldn't generate the PDF properly.

**Comment by ronaldtse** [comment]
5.4.2

<img width="529" alt="Screenshot 2021-09-07 at 5 07 25 PM" src="https://user-images.githubusercontent.com/11865/132317667-a84fd006-1608-4903-9c1d-2523971a9625.png">

5.4.3
<img width="549" alt="Screenshot 2021-09-07 at 5 07 32 PM" src="https://user-images.githubusercontent.com/11865/132317706-78c7861f-9337-40c9-b7e5-7a87e93fa7c0.png">

5.4.4
<img width="565" alt="Screenshot 2021-09-07 at 5 07 52 PM" src="https://user-images.githubusercontent.com/11865/132317753-eb9f834a-6f1c-403f-8ca6-0d338dff0a41.png">

5.4.6
<img width="530" alt="Screenshot 2021-09-07 at 5 08 09 PM" src="https://user-images.githubusercontent.com/11865/132317800-23a3be00-11cc-4d05-8df9-e583b1bb807d.png">

5.4.7
<img width="626" alt="Screenshot 2021-09-07 at 5 08 20 PM" src="https://user-images.githubusercontent.com/11865/132317833-04244429-cbb6-4f41-9683-01cf763e5636.png">

**Comment by ronaldtse** [comment]
Going to merge this first.

**Comment by ronaldtse** [comment]
From Michael Stock of BIPM:

> In example 1 of 5.4.3, the second “m” should also be in italics.
>  
> In the example of 5.4.6, the lines 1 and 2, 3 and 4 and the lines 5 to 7 belong together, which is not very clear from the structure. Could they be printed on one line or the different examples separated vertically? This is not a major issue, but it would improve the readability.
>  
> There is a similar issue in 5.4.2, but it is less problematic there.
>

**Comment by ronaldtse** [comment]
To BIPM:

> For the lines in 5.4.6, would you consider having them as separate examples? i.e. lines 1,2; lines 3,4; lines 5-7 as 3 different examples.
>
> Similarly for 5.4.2 as 2 examples.

**Comment by ronaldtse** [comment]
From BIPM:

> Yes, this would work. Similar as examples 2 and 3 in 5.4.4.

**Comment by ronaldtse** [comment]
From Michael Stock of BIPM:

> the second “m” in the first line of example 1 should also be in italics since it stands for a quantity. Symbols for quantities are always in italics, those for units in upright font.

<img width="640" alt="Screenshot 2021-09-12 at 4 25 23 PM" src="https://user-images.githubusercontent.com/11865/132979507-b7217f0a-bc76-4f8b-86e1-77b0a75ac92d.png">

Fixed.
