### ISSUE TITLE
BIPM review: wrong right double quote

### ISSUE THREAD

**Issue by manuel489** [metanorma/bipm-si-brochure#130]
*In relation to https://github.com/metanorma/bipm-si-brochure/issues/112*

From BIPM:
![issue15](https://user-images.githubusercontent.com/33627611/121970530-c1555f80-cd44-11eb-9a1b-fe582db4eed9.PNG)

(I think this is a known issue already.)

**Comment by Intelligent2013** [comment]
@opoudjis this issue occurs due char comma after quote.
MN xml:
```xml
&#8220;ppb<bookmark id="..."/>&#8221; and &#8220;ppt<bookmark id="..."/>&#8220;,
```
If we add space after quote and before comma (just for experiment)
adoc:
```
"((ppb))" and "((ppt))" ,
```
then last quote is ok:
```xml
&#8220;ppb<bookmark id="_..."/>&#8221; and &#8220;ppt<bookmark id="..."/>&#8221; ,
```

**Comment by ronaldtse** [comment]
I feel that "ppb" and "ppt" can be encoded in UnitsML. 

Sounds like this is a Metanorma problem.

**Comment by opoudjis** [comment]
It is, but it's nothing to do with UnitsML: it would occur regardless.

**Comment by opoudjis** [comment]
Fixed in standoc; pending confirmation from @manuel489

**Comment by manuel489** [comment]
Shoot! Forgot to confirm this. Sorry.
Yes, the issue is fixed. Thanks @opoudjis! 
Closing.
