### ISSUE TITLE
BIPM review: font size and font style in ToC of Appendix 1

### ISSUE THREAD

**Issue by manuel489** [metanorma/bipm-si-brochure#132]
*In relation to https://github.com/metanorma/bipm-si-brochure/issues/112*

From BIPM:
![issue17](https://user-images.githubusercontent.com/33627611/122116797-0b494e80-cdf4-11eb-8fa8-d03731aa6a84.PNG)

Original version:
![issue17-2](https://user-images.githubusercontent.com/33627611/122117012-54999e00-cdf4-11eb-9bfb-20eefb5daa50.PNG)

According to BIPM:

1. *"Table of Contents of Appendix 1"* text has larger font size in original version.
2. ToC subtitles like *"Decisions relating to the establishment of the SI"*, *"page"* and page numbers text must be in Arial.

**Comment by ronaldtse** [comment]
I wonder if this is more of an issue about the non-standard ToC we have here, this is a fake ToC.

As long as the main ToC and this "Resolutions ToC" are identical in style, I don't see an issue.

**Comment by Intelligent2013** [comment]
This ToC encoded as text:
```adoc
== Table of Contents of Appendix 1

[cols="3",options="unnumbered,header"]
|===

| | h| *page*
```

```xml
<clause id="_table_of_contents_of_appendix_1" obligation="normative">
  <title depth="2">1.1.<tab/>Table of Contents of Appendix 1</title>
  <table id="_13c93075-4e86-4c24-ad6e-1bfccf944573" unnumbered="true">
    <thead>
      <tr>
        <th valign="top" align="left"/>
        <th valign="top" align="left"/>
        <th valign="top" align="left">
          <strong>page</strong>
        </th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td colspan="3" valign="top" align="left">
          <strong>Decisions relating to the establishment of the SI</strong>
...
        </td>
      </tr>
      <tr>
```
Xslt can't set special styles without any additional indication in markup. So I can't do anything here.

**Comment by ronaldtse** [comment]
Clarification sought from BIPM:

> Appendix 1 TOC contains titles that are arbitrarily named, differing from the cited resolution title.
>
> e.g. the first entry 9th CGPM is listed of having a title “decision to establish the SI”, but the actual resolution title is “Proposal for establishing a practical system of units of measurement”. (see attached screenshots)
> 
> There is a review note from your colleague that the styling of the TOC of Appendix 1 vs the TOC of the main document differs. One way to “align” the styling is to automatically generate the TOC here.
> 
> However, these arbitrary “descriptions of resolution titles” make auto generation difficult — in this sense, the current TOC of Appendix 1 is not really a TOC because they don’t reflect the actual title name. This can cause confusion to the reader — when the reader finds a title in the TOC, the reader will try to find the exact same wording on the indicated page. Currently, a reader won’t be able to find that text because it is not the title but text that “describes the title”.

TOC:
<img width="644" alt="125015856-e8345680-e0a2-11eb-8a46-4f4415d592a9" src="https://user-images.githubusercontent.com/11865/125537101-5f11e40c-018b-45da-8fce-eb173faf8d5f.png">

Actual title:
<img width="544" alt="125015992-292c6b00-e0a3-11eb-82d7-e4d9089813c1" src="https://user-images.githubusercontent.com/11865/125537107-03ac94b8-9909-4997-990d-d597756ec84a.png">

**Comment by ronaldtse** [comment]
Michael Stock of BIPM stated:

> The entries in the TOC of Appendix 1 have been chosen differently from the titles of the resolutions, because the latter are quite often very general and do not give a hint of what is actually included in the text.
> 
> For example on page 165, Resolution 12 of the 11th CGPM has the title ‘Système  International d’Unités’. The entry in the TOC shows that this
>  
> 11th CGPM, 1960:             confirms the name and the abbreviation “SI”
> names prefixes from tera to pico
> establishes the supplementary units rad and sr
> lists some derived units
>  
> This is much more informative than just
>  
> 11th CGPM, 1960:             Système  International d’Unités
>  
> This way of describing the contents of the resolutions is helpful for those readers who are looking for specific information.
>  
> We should therefore leave the titles in the TOC as they are.

**Comment by opoudjis** [comment]
I have just implemented https://github.com/metanorma/metanorma-bipm/issues/148

And I don't see how this will help this quite absurd approach to ToC at all.

The ToC I have implemented allows a sequence of titles to be identified by XPath, and it allows alternate titles to be given to them for the purposes of the ToC. So:

````
toc:["//annex[@id = 'appendix1']/clause/title"]

....

[[cgpm9th1948]]
== 9th CGPM, 1948

[.variant-title,type=toc]
9th CGPM, 1948 pass:[<tab/>]decision to establish the SI
````

But the ToC entry is a laundry list in random order. The only way to generate it is:

````
toc:["//clause[@id = 'cgpm9th1948r6']/title","//clause[@id = 'cgpm10th1954r6']/title","//clause[@id = 'cipm1956r3']/title","//clause[@id = 'cgpm11th1960r12']/title","//clause[@id = 'cipm1969r1']/title","//clause[@id = 'cipm-si-units']/title","//clause[@id = 'cgpm23rd2007r12']/title","//clause[@id = 'cgpm24th2011r1']/title","//clause[@id = 'cgpm25th2014r1']/title","//clause[@id = 'cgpm26th2018r1']/title",]
````

And you'll need to include a separate ToC variant title under each subtitle indexed. (If a section is indexed twice in the ToC with different variant titles, you are out of luck.)

I'm not at all convinced it's worth it, but you're welcome to try it out now...

**Comment by Intelligent2013** [comment]
Example:
```adoc
== Table of Contents of Appendix 1

toc:["//clause[@id = 'cgpm9th1948r6'\]/title"]

...

[[cgpm9th1948]]
== 9th CGPM, 1948

...

[[cgpm9th1948r6]]
=== Proposal for establishing a practical system of units of measurement (CR, 64)

[.variant-title,type=toc]
<<cgpm9th1948,9th CGPM, 1948>> pass:[<tab/>]decision to establish the SI

```

Generated xml:
```xml
<toc>
	<ul id="_b89d1b74-7515-4f10-981c-0a3058883b1f">
		<li>
			<xref target="cgpm9th1948r6">1.6.3<tab/>
				<xref target="cgpm9th1948">1.6<tab/>9th CGPM, 1948</xref>
				<tab/>decision to establish the SI</xref>
		</li>
	</ul>
</toc>```
```

It should be rendered in PDF so:
![image](https://user-images.githubusercontent.com/5559926/131395825-c6bfcb91-09b7-48f7-a976-2a32b9f4e8c6.png)

@opoudjis can we specify something in markup to ignore sections number `1.6.3` `1.6` in xref? (i,e. not generate it in xml)

**Comment by Intelligent2013** [comment]
And unclear for me how can we encode the headers/sub-headers `Table of Contents of Appendix 1`, `Decisions relating to the establishment of the SI`, `Decisions relating to the base units of the SI`, `Length`, ... as part of TOC:
![image](https://user-images.githubusercontent.com/5559926/131401233-a4e8cbd5-e74c-4688-be4f-7e3e4818e63b.png)
to solve the issues from initial post:
1. *"Table of Contents of Appendix 1"* text has larger font size in original version.
2. ToC subtitles like *"Decisions relating to the establishment of the SI"*, *"page"* and page numbers text must be in Arial.

**Comment by opoudjis** [comment]
The markup changes requested in https://github.com/metanorma/bipm-si-brochure/issues/136, which insert these subheadings explicitly inside a <clause type="toc">, may help you address this, @Intelligent2013

**Comment by Intelligent2013** [comment]
Done.
