### ISSUE TITLE
BIPM review: CI-2013 NOTE block location

### ISSUE THREAD

**Issue by manuel489** [metanorma/bipm-si-brochure#134]
*In relation to https://github.com/metanorma/bipm-si-brochure/issues/112*

From BIPM:
![issue20-1](https://user-images.githubusercontent.com/33627611/122153489-1d95ad80-ce31-11eb-9719-884c970e9eac.PNG)

Original version:
![issue20-2](https://user-images.githubusercontent.com/33627611/122153417-f048ff80-ce30-11eb-99e5-2efff27150da.PNG)

I tried to fix this by markup but got odd results.

**Comment by manuel489** [comment]
In order to fix the issue, I tried to pass from this:

````
** the unperturbed optical transition stem:[1"S" - 2"S"] of the
^1^H neutral atom with a frequency of stem:[1233030706593518 "unitsml(Hz)"]
and an estimated relative standard uncertainty of stem:[1.2 xx 10^(-14)];
+
--
NOTE: This frequency corresponds to half of the energy difference
between the stem:[1"S"] and stem:[2"S"] states;
--
````

to this:

````
** the unperturbed optical transition stem:[1"S" - 2"S"] of the ^1^H
neutral atom with a frequency of stem:[1233030706593518 "unitsml(Hz)"]
and an estimated relative standard uncertainty of stem:[1.2 xx 10^(-14)];

NOTE: This frequency corresponds to half of the energy difference
between the stem:[1"S"] and stem:[2"S"] states;
````

But I got an odd result: the note was misplaced.

**Comment by ronaldtse** [comment]
@manuel489 I'm not convinced that this markup change is correct, but the BIPM did indicate that they wanted to see the resolutions in a similar placement as before.

Full screenshot:
<img width="540" alt="Screenshot 2021-06-16 at 11 58 58 AM" src="https://user-images.githubusercontent.com/11865/122155767-41410e00-ce9a-11eb-988a-567d516d39d3.png">

**Comment by manuel489** [comment]
Well, if we want to remove such indentation, I think the change that I proposed would serve.
But, the thing is, if I do so, the note block gets positioned in an odd place.

I mean, this:

Markup,
````
* that the following transition frequency be added to the list: 

** the unperturbed optical transition stem:[6"s"^2" "text()^1S_0 - 6"s " 6"p " text()^3"P"_0]
of the ^199^Hg neutral atom with a frequency of stem:[1128575290808162 "unitsml(Hz)"]
and an estimated relative standard uncertainty of stem:[1.7 xx 10^(-14)];

* that the following transition frequencies be updated in the list: 
** the unperturbed optical transition
stem:[4"s " text()^2"S"_(1//2) - 3"d " text()^2"D"_(5//2)]
of the ^40^Ca^+^ ion with a frequency of stem:[411042129776395 "unitsml(Hz)"]
and an estimated relative standard uncertainty of stem:[1.5 xx 10^(-14)]; 
** the unperturbed optical transition stem:[1"S" - 2"S"] of the ^1^H
neutral atom with a frequency of stem:[1233030706593518 "unitsml(Hz)"]
and an estimated relative standard uncertainty of stem:[1.2 xx 10^(-14)];


NOTE: This frequency corresponds to half of the energy difference between the stem:[1"S"] and stem:[2"S"] states;
````

Result:
![issue-a1](https://user-images.githubusercontent.com/33627611/122156624-56d11c00-ce37-11eb-8087-3431546933fb.PNG)


The note block should be placed where the red arrow indicates.

**Comment by ronaldtse** [comment]
This is the original recommendation:

https://webcache.googleusercontent.com/search?q=cache:5mCuh7CxW68J:https://www.bipm.org/utils/en/pdf/CIPM/CIPM2013-EN.pdf

<img width="613" alt="Screenshot 2021-06-17 at 2 29 43 PM" src="https://user-images.githubusercontent.com/11865/122343620-7ae84680-cf78-11eb-8de8-26ea5e515acb.png">

As long as we find a way to place the NOTE at that level it would work.

This is the method to attach a block to a parent list:
https://docs.asciidoctor.org/asciidoc/latest/lists/continuation/#attaching-to-an-ancestor-list

**Comment by ronaldtse** [comment]
Actually let me clarify with BIPM on this.

**Comment by ronaldtse** [comment]
From Michael Stock of BIPM:

> The note belongs to the second item, which it directly follows.

Therefore the original encoding is correct:

```adoc
** the unperturbed optical transition stem:[1"S" - 2"S"] of the
^1^H neutral atom with a frequency of stem:[1233030706593518 "unitsml(Hz)"]
and an estimated relative standard uncertainty of stem:[1.2 xx 10^(-14)];
+
--
NOTE: This frequency corresponds to half of the energy difference
between the stem:[1"S"] and stem:[2"S"] states;
--
```

In this case no change in encoding is necessary.

On the other hand, @Intelligent2013 would you be able to provide some better spacing between the list item and the note?

**Comment by ronaldtse** [comment]
I am asking for further clarification from BIPM of the indent of the Note.

**Comment by Intelligent2013** [comment]
I've updated xslt. Now:
- 'Note' displays under list item label (-), not under list item text
- spacing between list item and the note increased
![image](https://user-images.githubusercontent.com/5559926/124494402-75d02780-ddbf-11eb-97e8-c71604506398.png)

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 ! Closing this for now until further instruction from BIPM.

**Comment by ronaldtse** [comment]
@Intelligent2013 received BIPM clarification that the original indent is actually *better* to clarify the relationship of the Note. Let’s indent it back and we can close this. Thanks!

**Comment by Intelligent2013** [comment]
Done:
![image](https://user-images.githubusercontent.com/5559926/124897651-2cfab780-dfe7-11eb-9489-8636905c4b99.png)

**Comment by ronaldtse** [comment]
Thank you @Intelligent2013 !
