### ISSUE TITLE
BIPM review: correct indentation and font style in Appendix 1

### ISSUE THREAD

**Issue by manuel489** [metanorma/bipm-si-brochure#135]
*In relation to #112*

From BIPM:
![issue21-1](https://user-images.githubusercontent.com/33627611/122155486-11abea80-ce35-11eb-801c-4325ad4000eb.PNG)

Original version:
![issue21-2](https://user-images.githubusercontent.com/33627611/122155493-14a6db00-ce35-11eb-98d6-57291dd5c064.PNG)

(Same with *Appendix 2* and *Appendix 3*.)

**Comment by ronaldtse** [comment]
@manuel489 Our style is correct.

1. In this document, serif text is used for content body, sans serif text is used for "quoted text". This was confirmed acceptable by Michael Stock of BIPM.
2. The indentation is not an issue here. 

I don't think we need to fix this, but will report back to BIPM.

**Comment by Intelligent2013** [comment]
Xslt displays 2nd level clause's title with indentation, and can't differentiate one from another:
```xml
<clause id="cgpm26th2018" obligation="normative">
  <title depth="2">1.43.<tab/>26th CGPM, 2018</title>
  ....
<clause id="_appendix_1_abrogation_of_former_definitions_of_the_base_units_base_units" obligation="normative">
  <title depth="2">1.44.<tab/>Appendix 1. Abrogation of former definitions of the base units: ...
  </title>
```
![image](https://user-images.githubusercontent.com/5559926/122449385-78084880-cfae-11eb-8423-d7a36536af94.png)
...
![image](https://user-images.githubusercontent.com/5559926/122449422-822a4700-cfae-11eb-8f6a-0c83c308b15c.png)

**Comment by ronaldtse** [comment]
From Michael Stock of BIPM:

> The titles “Appendix 1” “Appendix 2” and “Appendix 3” are not independent subsections, they are part of Resolution 1 of the 26th CGPM. I agree with Robert that they should not be indented to the left. They should be aligned with the rest of the body of Resolution 1.
> 
> Since the three appendices are part of the quoted content of Resolution 1, they should be printed in the same font, that is ‘sans serif’.

This means that the current encoding is wrong. I will push a PR that addresses this, but @manuel489 (and @Intelligent2013 ) can you help with ensuring the rendered output is correct?

**Comment by ronaldtse** [comment]
PR is at #141 now.

**Comment by Intelligent2013** [comment]
BIPM xslt updated for 5 level depth title in annex. Now it renders:
![image](https://user-images.githubusercontent.com/5559926/124468776-37783f80-dda2-11eb-816c-1dc3c8bc513b.png)
...
![image](https://user-images.githubusercontent.com/5559926/124468806-3fd07a80-dda2-11eb-81a3-be6b32fefebe.png)
...
![image](https://user-images.githubusercontent.com/5559926/124468830-46f78880-dda2-11eb-8370-38605a28974f.png)
...
![image](https://user-images.githubusercontent.com/5559926/124468853-4eb72d00-dda2-11eb-9841-2e68b49bfd9b.png)
...
![image](https://user-images.githubusercontent.com/5559926/124468873-5676d180-dda2-11eb-96bb-cf4a8a138128.png)
...
![image](https://user-images.githubusercontent.com/5559926/124468892-5c6cb280-dda2-11eb-8639-c816036d2db9.png)

**Comment by ronaldtse** [comment]
Thank you @Intelligent2013 !
