### ISSUE TITLE
BIPM review: remove square bullet on sub-clause title

### ISSUE THREAD

**Issue by manuel489** [metanorma/bipm-si-brochure#136]
*In relation to #112*

From BIPM:
![issue22-1](https://user-images.githubusercontent.com/33627611/122155923-eece0600-ce35-11eb-9733-975a1a231c44.PNG)

Original version:
![issue22-2](https://user-images.githubusercontent.com/33627611/122157100-42d9ea00-ce38-11eb-95ba-efa4bc65e26e.PNG)

**Comment by manuel489** [comment]
Also in this part:
![issue23-1](https://user-images.githubusercontent.com/33627611/122158012-e37cd980-ce39-11eb-8445-19740c3220a0.PNG)

Original version:
![issue23-2](https://user-images.githubusercontent.com/33627611/122158028-ed064180-ce39-11eb-996a-7b3bc6066d18.PNG)

**Comment by Intelligent2013** [comment]
Xslt puts 'quad' marker for 3rd level titles in appendices. It was made specially for Appendix 1.
Original PDF:
![image](https://user-images.githubusercontent.com/5559926/122395475-afabcc00-cf7f-11eb-919a-d11e20a6bc41.png)

Resulted PDF:
![image](https://user-images.githubusercontent.com/5559926/122395533-c2260580-cf7f-11eb-962e-60d6ba56c473.png)

I can't distinguish titles in the appendices and use different styles for them.
In the xml there isn't difference between them:
```xml
<!-- Appendix 1-->
 <clause id="cgpm1st1889" obligation="normative">
  <title depth="2">1.2.<tab/>1st CGPM, 1889</title>
  <clause id="cgpm1st1889sanction" obligation="normative">
    <title depth="3">1.2.1.<tab/>Sanction of the international prototypes of the metre and the kilogram<bookmark id="_f6f7464d-46ae-4a2f-9b37-dccb0c0089cd"/> (CR, 34-38)<bookmark id="_044aa91e-d71d-4c41-8f20-d67fd6fbc553"/>
    </title>
...        
<!-- Appendix 4 -->      
<clause id="_part_3_historical_perspective_on_the_base_unitsbase_units" obligation="normative">
  <title depth="2">4.3.<tab/>Part 3. Historical perspective on the base units<bookmark id="_93c7af2c-82d3-4ce2-b72c-41596f4d01c4"/>
  </title>
  <clause id="_unit_of_time_second_second_unitsmls_time_duration" obligation="normative">
    <title depth="3">4.3.1.<tab/>Unit of time, second <bookmark to="second_s" id="_93fd53f9-f9fc-4728-9775-a8722b668676"/>
      <bookmark to="time_duration" id="_34c7914d-76f2-4b51-b34d-f224bad59172"/>
    </title>
```

**Comment by ronaldtse** [comment]
I've moved the issue about acronyms section to #148.

**Comment by ronaldtse** [comment]
I have contacted BIPM for clarification.

> We have an issue reported by your colleague last time where there is an inconsistency between the rendering of level 3 sections.
> 
> Case 1. In Appendix 1, the 3rd level section header uses a “square bullet”. (“Sanction of the international prototypes…”)
> ![122395475-afabcc00-cf7f-11eb-919a-d11e20a6bc41](https://user-images.githubusercontent.com/11865/129712909-3ab105c5-1c6f-407e-8ba3-14828611ff29.png)
> 
> Case 2. In Appendix 4 however, the 3rd level section header does not use the “square bullet”. (“Unit of time, second”)
> ![122157100-42d9ea00-ce38-11eb-95ba-efa4bc65e26e](https://user-images.githubusercontent.com/11865/129712920-09903510-f6ba-4e0a-b32e-b7268b598f96.PNG)
> 
> In the document structure, we do not currently have a way to distinguish these two cases as they are both “level 3 titles”. They are not semantically differentiated.
> 
> We wonder if there is a semantic difference between these two level 3 sections?
> 
> Is the Case 1 section header actually a “quotation” from the original resolution? However, the "original resolution title” is not identical with this one (in the Case 1 example) used here. This displayed title is more of a “reinterpretation” of the original resolution title. (and if you remember, it also differs from the TOC one)
> 
> To illustrate what I mean I’ve annotated the follow example to explain. The blue and yellow blocks are what the “current document” has added. The question is — is the quotation the one in the red or the green box?
> 
> It would be great if some light can be shed here…
> <img width="929" alt="Screenshot 2021-08-17 at 5 25 07 PM" src="https://user-images.githubusercontent.com/11865/129712962-c090695c-cd2b-4a78-9ef3-df16dc0039fe.png">
> 
> Whether the “square bullet" should:
> - apply to all level 3 sections
> - not apply to any level 3 section
> - apply to selective level 3 sections, for which we need some semantic differentiation

**Comment by ronaldtse** [comment]
From Michael Stock of BIPM:

> I see a difference between the level 3 titles in Appendix 1 and in Part 3 of Appendix 4. In Appendix 4 these titles are for sections of text written for the SI brochure. In Appendix 1, the titles are (in most cases) for reproductions of CIPM recommendations of CGPM resolutions. I would consider these titles as part of the recommendations and resolutions, even if they are in some cases somewhat different from the original titles and in other cases did not even exist in the original documents. Does taking them as part of the official text allow you to semantically differentiate between the titles in Appendices 1 and 4?

**Comment by opoudjis** [comment]
````
=== {blank}

[alt-title,type=quoted]
*Definition of the metre* (CR, 85)
````

**Comment by ronaldtse** [comment]
Why not:

```adoc
=== {blank}

[quote]
____
== Definition of the metre <<a CR citation>>

text
____

[quote]
____
== another one

text
____
```

**Comment by opoudjis** [comment]
Because 

````
[quote]
____
== Definition of the metre <<a CR citation>>

text
____
```

is illegal Asciidoctor, and it is CORRECT that it is illegal Asciidoctor. A quote is a block, you cannot override the hierarchy of sections using quotes. And `===` is a section delimiter, not a title marker.

**Comment by ronaldtse** [comment]
How about using the default `[quote]` syntax like this?

```adoc
[quote,Definition of the metre <<a CR citation>>]
```

**Comment by ronaldtse** [comment]
Actually the green part is not the source document title. Since AsciiDoc can't deal with quoted titles, we have to accept whatever syntax that works. Ugh.

**Comment by opoudjis** [comment]
My syntax works. So. @Intelligent2013 I will need to adjust markup, and I will resolve this title for you in PresentationXML, I will put in the black bullet there myself.

**Comment by Intelligent2013** [comment]
> My syntax works. So. @Intelligent2013 I will need to adjust markup, and I will resolve this title for you in PresentationXML, I will put in the black bullet there myself.

@opoudjis currently, xslt displays black bullet (box) as svg:
```xml
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xml:space="preserve" viewBox="0 0 2 2">
	<rect x="0" y="0" width="2" height="2" fill="black"/>
</svg>
```
The reasons of it:
1. some fonts don't contain 'Black Square` (U+25A0) glyph
2. glyph size looks smaller and baseline shifted down:
![image](https://user-images.githubusercontent.com/5559926/132343653-1c02e1ed-33a0-4e64-85e4-2c13e603d46b.png)
vs. original PDF:
![image](https://user-images.githubusercontent.com/5559926/132343779-efff5070-1fc2-4991-a713-08ebcbe266ac.png)

If title the xml will contain black box, then xslt needs to cut it, make some transformation (add font-size, shift-baseline, or just replace by svg), for ToC this should be removed. Therefore, could you put tag instead of char? For example, `<quad/>`, `<blacksquare/>` or something another?
Example:
```xml
<title depth="3">1.2.1.<tab/><quad/>Sanction of the international prototypes of the metre...
```

**Comment by Intelligent2013** [comment]
But in any case I can process the black box as char.

**Comment by opoudjis** [comment]
Huh. OK, I'll do `<blacksquare/>`, since `<quad/>` can also be a blank space.

**Comment by opoudjis** [comment]
So reiterating for the editors: all the subtitles in Annex with a black square bullet are to be marked up as:

````
=== {blank}

[alt-title,type=quoted]
*Definition of the metre* (CR, 85)
````

**Comment by opoudjis** [comment]
@Intelligent2013 Sorry: please change `<alt-title>` to `<variant-title>`

**Comment by manuel489** [comment]
> So reiterating for the editors: all the subtitles in Annex with a black square bullet are to be marked up as:

Changes applied.

**Comment by opoudjis** [comment]
Documentation lost, resubmitting
