### ISSUE TITLE
BIPM review: sans serif math symbols looking too separate in between

### ISSUE THREAD

**Issue by manuel489** [metanorma/bipm-si-brochure#137]
*In relation to #112*

BIPM is requesting to use sans serif font style in certain math symbols.
From BIPM:
![issue25-1](https://user-images.githubusercontent.com/33627611/122265786-1b6e3600-cea7-11eb-84b8-deccf5abb2c3.PNG)

However, if the symbol has more than one letter, these look kind of separate
in comparison with original version.

For example:
![issue25-3](https://user-images.githubusercontent.com/33627611/122266199-91729d00-cea7-11eb-9b3a-ec40a14acbb8.PNG)

Original version:
![issue25-4](https://user-images.githubusercontent.com/33627611/122266335-b23af280-cea7-11eb-882a-1dbcb38e2e49.PNG)

Considering how rigid BIPM is when it comes to symbols (and pretty much everything else),
I think they could complain about this.
So, a workaround in the markup would be to apply sans serif (`sf` attribute) to each letter independently.
I mean for example, to pass from this:

````
stem:[sf "cd"]
````

to this:

````
stem:[sf "c" sf "d"]
````

which renders:
![issue25-5](https://user-images.githubusercontent.com/33627611/122267424-dc40e480-cea8-11eb-95e5-234f72c361c2.PNG)

So, my question is:
Can I follow with this approach?

**Comment by manuel489** [comment]
Also notice that I'll have to discard `"unitsml(...)"` attribute.

**Comment by ronaldtse** [comment]
@manuel489 we clearly have to keep UnitsML.

> However, if the symbol has more than one letter, these look kind of separate in comparison with original version.

This is probably a UnitsML rendering bug (@opoudjis )

> Considering how rigid BIPM is when it comes to symbols (and pretty much everything else),

These comments come from the BIPM publication department instead of the scientific departments (whom we are accountable to), so their opinions can be different. 

We will clarify with the scientific departments on the font usage of these units.

**Comment by opoudjis** [comment]
Well be aware of what is happening with `stem:[sf "unitsml(cd)"]`

The "unitsml(cd)" is generating a very big chunk of XML, which includes embedded within it a proper rendering of the unit in MathML.

The "stem:[sf ... ]" is wrapping formatting around that chunk of XML.

I'm not surprised things are going wrong. The embedded MathML is not necessarily interacting nicely with any surrounding MathML. I'll have to investigate what is being generated, and I may be forced to devise some workaround.

**Comment by opoudjis** [comment]
The MathML being generated is:

````
<span class="stem"><math xmlns="http://www.w3.org/1998/Math/MathML">
  <mstyle mathvariant="sans-serif"><mrow xref="U_NISTu7"><mi mathvariant="normal">&#x1D5BC;&#x1D5BD;</mi></mrow>
</mstyle>
</math></span>
````

So I am converting ANY sans-serif in MathML into Mathetmatics Alphanumeric symbols; and Metanorma is smart enough to detect that the UnitsML markup is being embedded in sans-serif. That was a deliberate decision taken in light of the difficulties Word was having with fonts in MathML, and it was intended to safeguard MathML from font peculiarities.

As far as I'm concerned, this generated markup is legal and proper, and it looks fine in HTML:

Safari:
<img width="178" alt="Στιγμιότυπο 2021-08-01, 23 04 28" src="https://user-images.githubusercontent.com/1911039/127771887-148abddb-8799-4e33-a03b-b10c9a06406c.png">

Chrome:
<img width="178" alt="Στιγμιότυπο 2021-08-01, 23 05 58" src="https://user-images.githubusercontent.com/1911039/127771920-064717e3-e468-4a09-a83b-598b51f67c2e.png">

@Intelligent2013 You won't like me saying this, but I think this is a jEuclid issue, not a MathML output issue. You should be able to manipulate the MathML here...

**Comment by Intelligent2013** [comment]
1. `<mi mathvariant="normal">cd</mi>`
```xml
<stem type="MathML">
	<math xmlns="http://www.w3.org/1998/Math/MathML">
		<mstyle mathvariant="sans-serif">
			<mrow xref="U_NISTu7">
				<mi mathvariant="normal">cd</mi>
			</mrow>
		</mstyle>
	</math>
</stem>
```
renders in PDF: 
![image](https://user-images.githubusercontent.com/5559926/128037059-d4cb288b-260b-40a4-b121-fcfc1f00a8d3.png)

2. `<mi mathvariant="normal">&#x1D5BC;&#x1D5BD;</mi>`
```xml
<stem type="MathML">
	<math xmlns="http://www.w3.org/1998/Math/MathML">
		<mstyle mathvariant="sans-serif">
			<mrow xref="U_NISTu7">
				<mi mathvariant="normal">&#x1D5BC;&#x1D5BD;</mi>
			</mrow>
		</mstyle>
	</math>
</stem>
```
renders in PDF:
![image](https://user-images.githubusercontent.com/5559926/128037241-1447692e-b8ff-4a2e-9a9e-6ee2c966ed90.png)



>  The MathML being generated is:
```
<span class="stem"><math xmlns="http://www.w3.org/1998/Math/MathML">
  <mstyle mathvariant="sans-serif"><mrow xref="U_NISTu7"><mi mathvariant="normal">&#x1D5BC;&#x1D5BD;</mi></mrow>
</mstyle>
</math></span>
```

@opoudjis I've just generated xml for BIPM brochure (metanorma-bipm 1.1.6, the command `bundle exec metanorma -t bipm -x pdf sources/si-brochure-en.adoc`), and for
```
stem:[sf "unitsml(cd)"
```
it generates `cd`, not `&#x1D5BC;&#x1D5BD;`:
```xml
<stem type="MathML">
	<math xmlns="http://www.w3.org/1998/Math/MathML">
		<mstyle mathvariant="sans-serif">
			<mrow xref="U_NISTu7">
				<mi mathvariant="normal">cd</mi>
			</mrow>
		</mstyle>
	</math>
</stem>
```
It's ok?

**Comment by opoudjis** [comment]
So, nested mathvariant attributes are being confused by jEuclid: the closest to the text is being prioritised, rather than the furthest.

The simplest way of addressing this then is for me in PresentationXML to resolve styles embedding other styles by stripping them, rather than letting them be cumulative and trusting the renderer.

**Comment by opoudjis** [comment]
Now generating:

````
             <stem type='MathML'>
               <math xmlns='http://www.w3.org/1998/Math/MathML'>
                 <mstyle mathvariant='sans-serif'>
                   <mrow xref='U_NISTu7'>
                     <mi mathvariant='sans-serif'>cd</mi>
                   </mrow>
                 </mstyle>
               </math>
             </stem>
````

If there is an outer and an inner instance of `@mathvariant`, I am now merging them in the inner instance.
