### ISSUE TITLE
BIPM review: indent certain unordered list to right

### ISSUE THREAD

**Issue by manuel489** [metanorma/bipm-si-brochure#138]
*In relation to #112*

BIPM is requesting to indent certain unordered lists to right:
![issue26-1](https://user-images.githubusercontent.com/33627611/122271866-e7e2da00-cead-11eb-999a-3a202506b06f.PNG)

Original version:
![issue26-2](https://user-images.githubusercontent.com/33627611/122271890-efa27e80-cead-11eb-80fb-7a14b7bae7fb.PNG)

**Comment by ronaldtse** [comment]
@Intelligent2013 this may be a generic unordered list indentation issue. Can we indent all unordered list items?

**Comment by ronaldtse** [comment]
@Intelligent2013 actually upon re-reading this, we shouldn't do this. This is not semantically sane.

**Comment by ronaldtse** [comment]
From Michael Stock of BIPM:

> I agree. As you observed, the indentation in the original PDF is not uniform.

So there's nothing to be done here. Thanks.
