### ISSUE TITLE
Provide multiple table renderings to choose fonts for "dimensions"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#144]
Original question:

> We have run into an issue with Table 3 of the SI Brochure. Not a presentational issue but a semantic issue with regards to the symbols for dimensions.
> 
> This is the original Table 3 from the SI Brochure Ed 9. Notice that the "Symbol for dimension” column contains a mix of Latin (L, J doesn’t exist in Greek) and Greek characters (theta doesn’t exist in Latin).
> <img width="621" alt="image001" src="https://user-images.githubusercontent.com/11865/124604018-16e0e000-de9d-11eb-8c4f-791cfe73feb9.png"> 
> 
> There was a comment raised where the font representation for I and J were not identical to the original, so we tried to find a semantic solution to this.
> 
> Unicode contains a special block called “Mathematical Alphanumeric Symbols” which contains math symbols. In this case, the “Symbol for dimension” symbols are all sans-serif, so the Latin characters for math exist in 1D5A0 to 1D5B9. To our surprise, the Greek characters for math are only given in “bold” or “italics”, (bold: 1D756 to 1D76f). (full block: https://www.compart.com/en/unicode/block/U+1D400)
> 
> While there is a “normal capital theta” in the “Greek plane”, that symbol is not necessarily sans serif and is not intended to be used in math.
> 
> There are two potential solutions:
> 1. Use Latin “plain” capital characters for all symbols except theta, which we use the Greek “bold” capital character
> 2. Use Latin “bold” capital characters and Greek “bold" capital characters
> 
> What is the preferred solution?

From Michael Stock of BIPM:

In the original Word file of the SI brochure, the theta is probably Unicode character U+03F4. The font is Arial 10 point.

Would it be possible to produce a version of the table with the different options for the theta so that we can look what fits best: bold and italics from the “Mathematical Alphanumeric Symbols”, “normal capital theta” from the “Greek plane” and the one given above?

## Mathematical Sans Serif (Latin only)

<img width="827" alt="image002" src="https://user-images.githubusercontent.com/11865/124604038-1c3e2a80-de9d-11eb-8854-b25837f2dafc.png">

## Mathematical Sans Serif Bold (Greek)

<img width="826" alt="Screenshot 2021-06-17 at 9 55 50 PM" src="https://user-images.githubusercontent.com/11865/124604456-89ea5680-de9d-11eb-8994-ca244aa3ceb9.png">

## Available "Capital Theta" symbols

<img width="835" alt="Screenshot 2021-07-06 at 9 15 34 PM" src="https://user-images.githubusercontent.com/11865/124606315-5ad4e480-de9f-11eb-846a-f2ca1ecba5c5.png">

(We can only use sans-serif ones)

## Deliverable

Produce rendering of 4 tables based on the original one with these different fonts:

* all "Dimensions" symbols use Mathematical Sans Serif Bold codes (Latin + Greek) (theta is U+1D6AF)
* all "Dimensions" symbols use Latin “plain” capital characters, except theta uses Greek “bold” capital character (U+1D6AF)
* all "Dimensions" symbols use Latin “italics bold” capital characters, except theta uses Greek “italics bold” capital character (U+1D797)
* all "Dimensions" symbols use Latin “plain” capital characters, except theta uses Greek “normal” capital character (U+03F4)

**Comment by Intelligent2013** [comment]
I did it:
1. added tables for four cases:
```adoc
[%unnumbered]
[[table3_1]]
.all "Dimensions" symbols use Mathematical Sans Serif Bold codes (Latin + Greek) (theta is U+1D6AF)
[cols="<,<,<,<"]
|===
| Base quantity | Typical symbol for quantity | Symbol for dimension (latin) |  Symbol for dimension (greek) 

| time | stem:[t] | stem:[sf "&#x1D5E7;"] | stem:[sf "&#x1D769;"]
| length | stem:[l, x, r], etc. | stem:[sf "&#x1D5DF;"] | 
| mass | stem:[m] | stem:[sf "&#x1D5E0;"] | stem:[sf "&#x1D761;"]
| electric current | stem:[ii(I), i] | stem:[sf "&#x1D5DC;"] | stem:[sf "&#x1D75E;"]
| thermodynamic temperature | stem:[ii(T)] | | stem:[sf "&#x1D6AF;"]
| amount of substance | stem:[n] | stem:[sf "&#x1D5E1;"] | stem:[sf "&#x1D762;"]
| luminous intensity | stem:[ii(I)_("v")] | stem:[sf "&#x1D5DD;"] | 
|===
```
```xml
[%unnumbered]
[[table3_2]]
.all "Dimensions" symbols use Latin “plain” capital characters, except theta uses Greek “bold” capital character (U+1D6AF)
[cols="<,<,<"]
|===
| Base quantity | Typical symbol for quantity | Symbol for dimension

| time | stem:[t] | stem:[sf "&#x1D5B3;"]
| length | stem:[l, x, r], etc. | stem:[sf "&#x1D5AB;"]
| mass | stem:[m] | stem:[sf "&#x1D5AC;"]
| electric current | stem:[ii(I), i] | stem:[sf "&#x1D5A8;"]
| thermodynamic temperature | stem:[ii(T)] | stem:[sf "&#x1D6AF;"]
| amount of substance | stem:[n] | stem:[sf "&#x1D5AD;"]
| luminous intensity | stem:[ii(I)_("v")] | stem:[sf "&#x1D5A9;"]
|===
```
```xml
[%unnumbered]
[[table3_3]]
.all "Dimensions" symbols use Latin “italics bold” capital characters, except theta uses Greek “italics bold” capital character (U+1D797)
[cols="<,<,<"]
|===
| Base quantity | Typical symbol for quantity | Symbol for dimension

| time | stem:[t] | stem:[sf "&#x1D64F;"]
| length | stem:[l, x, r], etc. | stem:[sf "&#x1D647;"]
| mass | stem:[m] | stem:[sf "&#x1D648;"]
| electric current | stem:[ii(I), i] | stem:[sf "&#x1D644;"]
| thermodynamic temperature | stem:[ii(T)] | stem:[sf "&#x1D797;"]
| amount of substance | stem:[n] | stem:[sf "&#x1D649;"]
| luminous intensity | stem:[ii(I)_("v")] | stem:[sf "&#x1D645;"]
|===
```
```xml
[%unnumbered]
[[table3_4]]
.all "Dimensions" symbols use Latin “plain” capital characters, except theta uses Greek “normal” capital character (U+03F4)
[cols="<,<,<"]
|===
| Base quantity | Typical symbol for quantity | Symbol for dimension

| time | stem:[t] | stem:[sf "&#x1D5B3;"]
| length | stem:[l, x, r], etc. | stem:[sf "&#x1D5AB;"]
| mass | stem:[m] | stem:[sf "&#x1D5AC;"]
| electric current | stem:[ii(I), i] | stem:[sf "&#x1D5A8;"]
| thermodynamic temperature | stem:[ii(T)] | stem:[sf "&#x03F4;"]
| amount of substance | stem:[n] | stem:[sf "&#x1D5AD;"]
| luminous intensity | stem:[ii(I)_("v")] | stem:[sf "&#x1D5A9;"]
|===
```

2. in the resulted mn xml, replaced manually all sequences like this:
```xml
<mstyle mathvariant="sans-serif"><mtext>&#120388;</mtext></mstyle>
```
to
```xml
<mglyph fontfamily="STIX Two Math" index="120388"/>
```
as workaround solution, because I didn't solve the issue https://github.com/metanorma/bipm-si-brochure/issues/121 yet.
This allows to turn-off jEuclid font replacement mechanism for sans-serif style and glyphs > 0x1D400.

3. Rendered pdf [si-brochure-en.presentation.pdf](https://github.com/metanorma/bipm-si-brochure/files/6771831/si-brochure-en.presentation.pdf):
![image](https://user-images.githubusercontent.com/5559926/124644852-5f979980-de9b-11eb-810c-7de7601a03b8.png)

![image](https://user-images.githubusercontent.com/5559926/124644882-69b99800-de9b-11eb-8830-44a904275494.png)

![image](https://user-images.githubusercontent.com/5559926/124644909-7211d300-de9b-11eb-8d43-4b00da112a0a.png)

![image](https://user-images.githubusercontent.com/5559926/124644932-7a6a0e00-de9b-11eb-867d-9e3dae9d6745.png)

**Comment by ronaldtse** [comment]
@Intelligent2013 I made a mistake -- the proper theta is 1D767, not 1D6AF. I've re-generated and edited your message to show the correct table and code.

**Comment by ronaldtse** [comment]
I have provided feedback to BIPM, closing this. Thanks @Intelligent2013 !
