### ISSUE TITLE
PV, CR, Metrologia citations

### ISSUE THREAD

**Issue by opoudjis** [metanorma/bipm-si-brochure#145]
How are they to be formulated, and rendered, in BIPM?

Comes from https://github.com/metanorma/bipm-si-brochure/issues/133

**Comment by ronaldtse** [comment]
<img width="571" alt="Screenshot 2021-07-13 at 3 40 27 PM" src="https://user-images.githubusercontent.com/11865/125411665-b7308a80-e3f0-11eb-8432-8d78e243d2eb.png">

<img width="562" alt="Screenshot 2021-07-13 at 3 39 20 PM" src="https://user-images.githubusercontent.com/11865/125411493-8ea89080-e3f0-11eb-8f7e-60935b985c2d.png">
<img width="504" alt="Screenshot 2021-07-13 at 3 39 25 PM" src="https://user-images.githubusercontent.com/11865/125411509-910aea80-e3f0-11eb-8310-978f8d998d35.png">
<img width="572" alt="Screenshot 2021-07-13 at 3 39 42 PM" src="https://user-images.githubusercontent.com/11865/125411556-9bc57f80-e3f0-11eb-8411-c495fc6451ba.png">
<img width="580" alt="Screenshot 2021-07-13 at 3 40 51 PM" src="https://user-images.githubusercontent.com/11865/125411743-c7486a00-e3f0-11eb-9eaf-af25722c7946.png">
<img width="505" alt="Screenshot 2021-07-13 at 3 41 08 PM" src="https://user-images.githubusercontent.com/11865/125411768-cf080e80-e3f0-11eb-967c-c3eac2a1878e.png">

**Comment by ronaldtse** [comment]
PV: https://github.com/relaton/relaton-bipm/issues/4
CR: https://github.com/relaton/relaton-bipm/issues/3

**Comment by opoudjis** [comment]
Pending implementation of relaton-bipm tickets.

**Comment by opoudjis** [comment]
So representative citation renderings are:

* CR, 78
* _Metrologia_, 1972, *8*, 36
* PV, *48*, 24

The PV are Proceedings of the CIPM, and those are cited by volume and page number. So PV, *48*, 24 is `BIPM CIPM48`, p. 24.

Metrologia is cited by year, volume, and page. So _Metrologia_, 1972, *8*, 36 is `BIPM Metrologia 8`, p. 36.

CR are the Proceedings of the CPGM, and in the BIPM they are cited only by page number: 

* CR, 104 is Resolution 5 of the 13th CPGM.
* CR, 100 is Resolution 3 of the 16th CPGM.

And that is because, horrifically, the "CR" volume number is given either in preceding prose, or implicitly. So:

> *1st CGPM, 1889*
> * *Sanction of the international prototypes of the metre and the kilogram* (CR, 34 - 38)

That "(CR, 34 - 38)" is actually `<<ref,page=34-38>>`, where `ref` is `BIPM CGPM01` (or possibly `BIPM CGPM01 34` to `BIPM CGPM01 38`, if the citations in relaton are by page. The problem is, that the rendering of the volume number is left out in the current rendering.

Similarly, "the 16th CGPM (1979, Resolution 3, CR, 100 and _Metrologia_, 1980, *16*, 56)" has "CR, 100" as the citation, but what is actually cited is `BIPM CGPM16 100`. Again, the volume is outside of the citation: "the 16th CGPM (1979,...". 

In reality, the citation is of the Resolution, and not of the page. But this citation convention is so discursive, I'm not convinced it can be maintained.

**Comment by opoudjis** [comment]
We have an additional problem with the current encoding of references in relaton-bipm:

BIPM CIPM, CIPM CPGM, and BIPM Metrologia all require parts in their references: "BIPM Metrologia 29 6 373", "BIPM CGPM01 1", "BIPM CIPM101 1".

We do not know those parts from the citations: the citations all go straight from volume number to page. Requiring the parts in the citations is simply not going to work. We need to be able to make citations without the part numbers, and (presumably) have the relaton-bipm database work out which file corresponds to a given page number.

**Comment by opoudjis** [comment]
If we are going to have machine parsed citations, we are going to have machine processed renderings of citations. I am not going to indulge the pointless abbreviation of dropping volume numbers.

Implementing CR and PV rendering, boldfacing the volume. We don't have Metrologia citations yet.

**Comment by ronaldtse** [comment]
Instead of "volume" I think you mean dropping "tomb" numbers, because that number is not available in the data? The point of dropping that number is to make referencing possible, not "pointless" dropping. If you have it, use it. If not, skip it.

**Comment by opoudjis** [comment]
By "tomb", you mean "tome", which is French for "volume", I'm assuming. :)

When the proceedings of the first conference are discussed in the BIPM brochure appendix, the citation to the proceedings is given as CR, pagenumber. The reason the volume number is skipped is, it is implicit in the context --- this is the first conference, so it is supposed to be obvious to the reader that the page number is volume 1.

What I am saying is, (a) we are going to have to add the volume number in to the crossreference anyway, to make any machine readable reference work, and (b) I don't think we should be then suppressing the volume number from rendering, because I think the BIPM convention of dropping volume numbers when they should be obvious from context is counterproductive. It's the kind of thing you would see in the 19th century, in the world of "op. cit." We shouldn't perpetuate it.

**Comment by ronaldtse** [comment]
Thanks for the correction, which is better than my phone's autocorrect... 

The point of dropping tome is that the resolutions/decisions are supposed to be individually referencable as resolutions/decisions, not as part of proceeding volumes. These objects will be directly available on the internet without any indication of which "tome" they were originally from.

i.e. in the digital age we don't care about tome -- these resolutions/decisions will be directly linked to the number of the meeting/conference.

**Comment by opoudjis** [comment]
Well we don't support that yet anyway. The references right now only work to the level of volumes: we have page numbers in the citations, we don't have the means to map those to resolutions.

If you want to reference resolutions and not pages in the underlying machine readable encoding, and just display the page numbers in the rendering, that... is different again. But right now, we can't support what you're saying.

**Comment by ronaldtse** [comment]
@metanorma/editors now all the PV and CR can be cited via Relaton. Can you please help update them soon? Thanks.

**Comment by anermina** [comment]
After citations were added for PV and CR, @manuel489 helped generate the output with the latest release of relaton-bipm (1.11.0). Example is shown below. Is this expected output?
![image](https://user-images.githubusercontent.com/55683568/166126066-704e5921-5086-4362-97ea-013c7fcac2cd.png)

**Comment by ronaldtse** [comment]
@opoudjis are we waiting for something here? BIPM is eager to finish this work. Thanks.

**Comment by opoudjis** [comment]
Hiding the CR, PV citations. Should be straightforward.

**Comment by opoudjis** [comment]
As enhancement: enforce implicit_reference at Presentation XML level, current code is not doing so.

**Comment by opoudjis** [comment]
Implemented now the editors have to look up the individual CGPM Resolution and CIPM Decision reference tags, but the hiding references tag is done, so all necessary infrastructure should be in place. Ticket to close when they're done with it.

**Comment by ronaldtse** [comment]
Related to Related to https://github.com/metanorma/metanorma-bipm/issues/164

**Comment by opoudjis** [comment]
Superseded by https://github.com/metanorma/bipm-si-brochure/issues/169
