### ISSUE TITLE
PDF: Question on tag structure tree

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#149]
The W3C samples for PDF tags use a `<P>` element for a block of text, but seems that in the Brochure we use 1 `<P>` element per line. Is this something we can fix?

I noticed that in Acrobat Pro when I perform an "edit" on one of the P elements in the Brochure, it automatically joins the next few lines (within the same paragraph) into a single P element.

<img width="782" alt="Screenshot 2021-08-18 at 2 54 12 PM" src="https://user-images.githubusercontent.com/11865/129851870-6d567833-1e91-4dca-afde-dd24210f3e30.png">

**Comment by ronaldtse** [comment]
Also, we don't seem to be making tags for headings like `H`, `H2`, and the List and List Items.

**Comment by Intelligent2013** [comment]
> The W3C samples for PDF tags use a <P> element for a block of text, but seems that in the Brochure we use 1 <P> element per line. Is this something we can fix?

@ronaldtse I think no, this behavior is how Apache FOP works. Internally, it create a text block for each line of text. For example, 

Source metanorma xml:
```xml
<p id="_f7837ba3-1ea1-4c6a-9ce4-6df97be49081">The International Bureau of Weights and Measures (BIPM) was set up by the Metre Convention signed in Paris on 20 May 1875 by seventeen States during the final session of the diplomatic Conference of the Metre. This Convention was amended in 1921.</p>
```
resulted PDF:
![image](https://user-images.githubusercontent.com/5559926/130081957-535854ca-9f05-4908-ba7b-b07448edb998.png)

Apache FOP intermediate format:
```xml
<g transform="translate(0,104800)">
 <id name="_f7837ba3-1ea1-4c6a-9ce4-6df97be49081"/>
 <text x="0" y="9597" next-is-space="true" word-spacing="2798" dp="29 Z114 -840 0" foi:struct-ref="67">The International Bureau of Weights and Measures (BIPM) was set up by the Metre</text>
 <text x="0" y="23772" next-is-space="true" word-spacing="458" foi:struct-ref="67">Convention signed in Paris on 20 May 1875 by seventeen States during the final session of</text>
 <text x="0" y="37947" foi:struct-ref="67">the diplomatic Conference of the Metre. This Convention was amended in 1921.</text>
</g>
```


> I noticed that in Acrobat Pro when I perform an "edit" on one of the P elements in the Brochure, it automatically joins the next few lines (within the same paragraph) into a single P element.

I think that Acrobat Pro is so smarty, that combines nearby positioned block into one. But sometimes this feature is not working as user expect:
https://community.adobe.com/t5/acrobat/prevent-multiple-text-boxes-from-merging-into-one-large-text-box/m-p/9148816
https://acrobat.uservoice.com/forums/590923-acrobat-for-windows-and-mac/suggestions/33070945-stop-text-boxes-from-combining

**Comment by ronaldtse** [comment]
Got it, makes sense indeed. Thanks!

**Comment by Intelligent2013** [comment]
> Also, we don't seem to be making tags for headings like H, H2, and the List and List Items.

Done in https://github.com/metanorma/mn-native-pdf/issues/326. Closing.
