### ISSUE TITLE
Fix GHA workflows

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#153]

**Comment by ronaldtse** [comment]
Looks like something to do with packed-mn?

**Comment by CAMOBAP** [comment]
@ronaldtse docker have the same issue, looks like the issue in the gem by itself, I will check

**Comment by CAMOBAP** [comment]
The same root as https://github.com/metanorma/bipm-si-brochure/issues/142

In progress

**Comment by CAMOBAP** [comment]
Triggering re-run

**Comment by CAMOBAP** [comment]
Done
