### ISSUE TITLE
Considering section numbering in Appendices

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#156]
Sent to BIPM for clarification:

> There is one further issue about “section numbering” for Appendix 4 and 5:
> 
> - In Appendix 4, “Part N” is the pattern used for numbering
> - In Appendix 5, “N” (just the number) is used for numbering
> 
> In other standards organizations, e.g. ISO, they use something like “B.1” to indicate it is “Annex B section 1”. In our case, it could be “A5.1” to indicate “Appendix 5, section 1”.
> 
> Questions:
> 1. Should all Appendix sections be numbered in a consistent way? (i.e. sections in Appendix 4 and Appendix 5 should follow the same numbering pattern)
> 2. Do we need to update the numbering of sections within Appendices?

**Comment by ronaldtse** [comment]
From Michael Stock of BIPM:

> Since you explained that it is possible to use the numbering scheme only for A4 and A5, we would recommend the following:
>  
> Appendix 4 Historical notes on the development of the International System of Units and its base units
>  
> A4.1 The historical development of the realization of SI units
> A4.2 The historical development of the International System
> A4.3 Historical perspective on the base units
>  
> Appendix 5 List of acronyms used in the present volume
>  
> A5.1 Acronyms for laboratories, committees and conferences
> A5.2 Acronyms for scientific terms
>  
> Adding an “A” to the numbering and removing the “Part 1” etc. from the section titles of A4 and the numbers from the section titles of A5.

**Comment by ronaldtse** [comment]
@Intelligent2013 notice that the bookmarks looked like this before:
<img width="236" alt="image001" src="https://user-images.githubusercontent.com/11865/133072786-4b333296-ef43-4ea1-b116-690ea22e38a4.png">

**Comment by opoudjis** [comment]
> Since you explained that it is possible to use the numbering scheme only for A4 and A5, we would recommend the following:

... I'm not sure that's true at all, but... I have to assume from this that the numbering of appendix subclauses in BIPM is henceforth A_m.n_

**Comment by opoudjis** [comment]
The index will now hence look like A4.1, A5.1, etc.

@Intelligent2013 I will generate and send you updated Presentation XML.

**Comment by Intelligent2013** [comment]
```adoc
== Part 1. The historical development of the realization of SI units index-range:realization_unit-3...
```

```xml
<title depth="2">A4.1.<tab/>Part 1. The historical development of the realization of SI units <bookmark to=.."/>
```
![image](https://user-images.githubusercontent.com/5559926/133270321-d2643778-6da5-4550-9672-8b1f54c72601.png)

To do:
- remove `Part X.` from adoc
- BIPM xslt: display section number before `tab`

```adoc
=== 1. Acronyms for laboratories, committees and conferences
```

```xml
<title depth="2">A5.1.<tab/>1. Acronyms for laboratories, committees and conferences</title>
```
![image](https://user-images.githubusercontent.com/5559926/133270378-59f5ccb6-0ef0-43cd-9416-d770f128c994.png)

To do:
- remove `1.` `2.` from adoc
- BIPM xslt: display section number before `tab`

**Comment by Intelligent2013** [comment]
But I have to hide sections numbers from Annex 1, but don't figure out yet how to do this...
```
<title depth="2">A1.2.<tab/>1st CGPM, 1889</title>
<clause id="cgpm1st1889sanction_si-brochure-en" obligation="normative">
	<title depth="3">A1.2.1.<tab/>Sanction of the international prototypes of the metre and the kilogram<bookmark id="_31939130-c86b-4e0c-ac65-3ba80883154e"/> (CR, 34-38)<bookmark id="_f825aef2-9394-4641-b860-4b5b081f15c1"/>
	</title>
```

**Comment by ronaldtse** [comment]
> But I have to hide sections numbers from Annex 1, but don't figure out yet how to do this...

Isn't this related to #136? Is there a way we can semantically encode this?

**Comment by Intelligent2013** [comment]
> 
> 
> > But I have to hide sections numbers from Annex 1, but don't figure out yet how to do this...
> 
> Isn't this related to #136? Is there a way we can semantically encode this?

no, #136 related to black square char, but in this ticket we need show section's number for some appendices only (and for some levels only). I.e. show for clause's titles with level=2 depth in Appendices 4 and 5, and hide in another cases. I don't see how to encode it semantically.

**Comment by ronaldtse** [comment]
@Intelligent2013 I think we have to encode the A1 titles not as section headers, but something else?

**Comment by Intelligent2013** [comment]
what if we'll add the attributes `number` like this:

```adoc
[number=1]
== The historical development of the realization of SI units ...
...
[number=2]
== The historical development of the International System...
...
[number=3]
== Historical perspective on the base units...
...
```
then in metanorma xml there will be the attributes `number`:
```xml
<clause id="_" number="1" obligation="normative">
	<title depth="2">A4.1.<tab/>The historical development of the realization of SI units ...
...
<clause id="_" number="2" obligation="normative">
	<title depth="2">A4.2.<tab/>The historical development of the International System...
<clause id="_" number="3" obligation="normative">
	<title depth="2">A4.3.<tab/>Historical perspective on the base units...
...
```
which xslt can use as 'indication' that section number should be displayed.

**Comment by ronaldtse** [comment]
Or `label=""` vs `label="A4.1."` ?

**Comment by Intelligent2013** [comment]
> Or `label=""` vs `label="A4.1."` ?

metanorma supports the attribute `number` already: https://www.metanorma.org/author/topics/document-format/sections/#numbering

There are two alternatives:
- if in adoc there is the attribute `number`, then create additional attribute `label` in xml, that contains section number (example `label="A4.1."`). Actually this attribute will repeat the value before `tab` in the element `<title depth="2">A4.1.<tab/>The historical development of the realization of SI units ...`
- add the processing of new attribute `label` in adoc (create additional attribute `label` in xml). In this case we should set two entities - appendix name (`A`) and clause number (`1.`) (vs. clause number only in case of 1st variant)

**Comment by opoudjis** [comment]
OK, Hold up. I need to understand the requirements here.

* When the title appears in the Table of Contents, it has one numbering
* When the title appears in the text, it has a different numbering. 

Right?

In that case, the solution is not to change the numbering of annex clauses, like I did. It is to keep the numbering of annex clauses as it was before, but to override it in the ToC clauses, as we'd already been doing. So, try:

````
== Part 1. The historical development of the realization of SI units index-range:realization_unit-3...

[.variant-title,type=toc]
A4.1 ++<tab/>++The historical development of the realization of SI units
```

**Comment by Intelligent2013** [comment]
@opoudjis currently:
adoc
```
== Part 1. The historical development of the realization of SI units index-range:realization_unit-3[(((realization of a unit)))] index:see[Système International d'Unités (SI),International System of Units]

Experimental methods used for the realization of units and which use equations of physics are known as primary methods. The essential characteristic of a primary method is that it allows a quantity to be measured in a particular unit directly from its definition by using only quantities and constants that themselves do not contain that unit.
```
PDF:
![image](https://user-images.githubusercontent.com/5559926/135722546-980f257c-dd71-4565-8272-f60a70ad9694.png)

Required (from https://github.com/metanorma/bipm-si-brochure/issues/156#issuecomment-918079683):
![image](https://user-images.githubusercontent.com/5559926/135722902-3ad37d25-9f1b-41ba-b364-900820077939.png)


I could use the value `A4.1` before tab:
```xml
<title depth="2">A4.1.<tab/>Part 1. The historical development of the realization of SI units ...
```
but Appendix 1 has similar markup:
```xml
<title depth="2">A1.5.<tab/>CIPM, 1946</title>
```
We shouldn't display `A1.x` numbers in Appendix 1. So I can't differentiate section's numbers between Appendix 1 and Appendices 4 and 5.

**Comment by opoudjis** [comment]
The way forward here is the `number` override of clause numbering, I just need to confirm that it works as required.

**Comment by ronaldtse** [comment]
@opoudjis 
> OK, Hold up. I need to understand the requirements here.
>
> When the title appears in the Table of Contents, it has one numbering
> When the title appears in the text, it has a different numbering.

No. In both cases the numbering is identical for Appendix 4 and 5. The only difference is in Appendix 1 the title numbering is not shown, where the titles are technically quoted titles.

**Comment by opoudjis** [comment]
So:

Appendix 1 ToC: manually supplied ToC, with no subclause numbering
Appendix 1 text: subclause titles with no subclause numbering

Appendix 4 ToC: A4.1 subclause numbering, no _Part 1_ or _1_
Appendix 4 text: A4.1 subclause numbering, no _Part 1_ or _1_

....

The ToC is manually supplied as explicit xrefs, so that's been dealt with; subclause numbers will arise.

Appendix 1 should be marked up as:

````
[[cgpm1st1889]]
[%unnumbered]
== 1st CGPM, 1889

[[cgpm1st1889sanction]]
[%unnumbered]
=== {blank}

[.variant-title,type=quoted]
*Sanction of the international prototypes of the metre and the ((kilogram))* (CR, 34-38)(((metre (stem:["unitsml(m)"]))))

````

The unnumbered subclauses of Appendix 1 will take care of there being no numbering in Appendix 1.

Having a blank unnumbered sub-subclause of Appendix 1, and a variant title of type "quoted", will ensure that there is no numbering of sub-subclauses, and the bulleted variant title is used instead.

If we now leave Appendix 4 and 5 as is, and delete Part 1 and 1, then A4.1 and A5.1 will number as we expect.

So

````
[appendix]
== First Appendix 

[[cgpm1st1889]]
[%unnumbered]
=== 1st CGPM, 1889

[[cgpm1st1889sanction]]
[%unnumbered]
==== {blank}

[.variant-title,type=quoted]
*Sanction of the international prototypes of the metre and the ((kilogram))* (CR, 34-38)(((metre (stem:["unitsml(m)"]))))

[appendix]
== Second Appendix 

[appendix]
== Third Appendix 

[appendix]
== Fourth Appendix 

=== The historical development of the realization of SI units
````

will generate the following PresentationXML:

````
<annex id="_first_appendix" obligation="normative" displayorder="3">
<title><strong>Annexe 1</strong>.<tab/><strong>First Appendix</strong></title>

<clause id="cgpm1st1889" unnumbered="true" obligation="normative">
<title>1st CGPM, 1889</title>
<clause id="cgpm1st1889sanction" unnumbered="true" obligation="normative">
<title type="quoted"><blacksquare/><strong>Sanction of the international prototypes of the metre and the kilogram<bookmark id="_583b9b22-351a-4a75-aef3-f3164955392a"/></strong> (CR, 34-38)<bookmark id="_d6ab0b08-42ca-4a6e-9af4-1dabaeba257e"/></title>
</clause>
</clause>
</annex>

<annex id="_second_appendix" obligation="normative" displayorder="4">
<title><strong>Annexe 2</strong>.<tab/><strong>Second Appendix</strong></title>
</annex>

<annex id="_third_appendix" obligation="normative" displayorder="5">
<title><strong>Annexe 3</strong>.<tab/><strong>Third Appendix</strong></title>
</annex>

<annex id="_fourth_appendix" obligation="normative" displayorder="6">
<title><strong>Annexe 4</strong>.<tab/><strong>Fourth Appendix</strong></title>

<clause id="_the_historical_development_of_the_realization_of_si_units" obligation="normative">
<title depth="2">A4.1.<tab/>The historical development of the realization of SI units</title>
</clause>
</annex>
````

@Intelligent2013 @ronaldtse I think this is all you need, right? If so, this is an editorial task.

**Comment by Intelligent2013** [comment]
@opoudjis thank you for the idea, I'll check it to prevent on side-effects.

**Comment by Intelligent2013** [comment]
@opoudjis it's working. But title rendering in xslt based on the attribute `depth`. I've noticed that when I put `[%unnumbered]`, then the attribute `depth` is missing in the `title`:
With `[%unnumbered]`:
```adoc
[[cgpm1st1889]]
[%unnumbered]
== 1st CGPM, 1889
```
xml:
```xml
<clause id="cgpm1st1889" unnumbered="true" obligation="normative">
<title>1st CGPM, 1889</title>
```

without `[%unnumbered]`:

```adoc
[[cgpm1st1889]]
== 1st CGPM, 1889
```

```xml
<clause id="cgpm1st1889" obligation="normative">
<title depth="2">A1.2.<tab/>1st CGPM, 1889</title>
```

It is possible to don't remove `depth` from `title`?

**Comment by opoudjis** [comment]
BIPM issue: I was aborting processing of unnumbered clauses in BIPM too quickly. Fixing.

**Comment by Intelligent2013** [comment]
@metanorma/editors @manuel489  could you update adocs as described in for https://github.com/metanorma/bipm-si-brochure/issues/156#issuecomment-933421169 ?
Additionally, please add `[%unnumbered]` for third-level titles like `Unit of time, second`, etc. to prevent numbering:
![image](https://user-images.githubusercontent.com/5559926/135878403-4c3a8e4a-2655-43ff-82dc-cc4a6266cd62.png)

**Comment by manuel489** [comment]
@Intelligent2013, I have raised a PR with the requested changes in https://github.com/metanorma/bipm-si-brochure/pull/161
Could you take a look, please?
Thanks!

**Comment by Intelligent2013** [comment]
@manuel489 generated PDF: [collection.zip](https://github.com/metanorma/bipm-si-brochure/files/7284119/collection.zip)

please delete 1. and 2. from Annex 5:
![image](https://user-images.githubusercontent.com/5559926/135987900-eb78fe2b-d254-4640-a9fe-4ec635f4e984.png)
![image](https://user-images.githubusercontent.com/5559926/135988193-2655ce53-51bd-42dc-901e-e3f136ee9147.png)
![image](https://user-images.githubusercontent.com/5559926/135988074-6120b33b-3dc3-470e-a526-915884321dd4.png)
![image](https://user-images.githubusercontent.com/5559926/135988123-aa099acb-4bd4-4af9-b689-c3157fa40b1b.png)

**Comment by manuel489** [comment]
> please delete 1. and 2. from Annex 5:

Done. Merged to master.

**Comment by Intelligent2013** [comment]
@manuel489 thank you!
