### ISSUE TITLE
Perform comparison between English and French documents to ensure their content structures are identical

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#16]
We need to ensure the content structure is identical between the two.

@manuel489 @anermina any of you do French? Thanks!

**Comment by anermina** [comment]
Documents have been compared and their structures match now. Changes have been made in #21 .

Additionally, I've noticed following differences between original documents:

1. Missing note in French version (section 5):

EN:
![image](https://user-images.githubusercontent.com/55683568/93719115-dd92ea00-fb80-11ea-896d-05cc6595e806.png)

FR:
![image](https://user-images.githubusercontent.com/55683568/93719130-e84d7f00-fb80-11ea-9f9a-49be9716424c.png)

2. Missing symbol omega in French version (section 5):

EN:
![image](https://user-images.githubusercontent.com/55683568/93719471-0e741e80-fb83-11ea-9d31-bef9caf65447.png)

FR:
![image](https://user-images.githubusercontent.com/55683568/93719448-e684bb00-fb82-11ea-9572-b02823e42ae3.png)

**Comment by ronaldtse** [comment]
Have sought clarification from BIPM and will revert here.

**Comment by ronaldtse** [comment]
From BIPM:

1. SI Brochure Section 5. The highlighted English note is missing in French.
 
> Proposed action: add a French note that matches the missing English note.
The note in the English version explains a particularity of English grammar. It is not needed for the French text.
 
English:
![image001](https://user-images.githubusercontent.com/11865/94299704-9cdd0b80-ff9a-11ea-8498-447c00910f77.png)

French:
![image002](https://user-images.githubusercontent.com/11865/94299716-a1a1bf80-ff9a-11ea-8146-8d7d58a8bf0f.png)


2. SI Brochure Section 5. Missing “Omega” in French.

Yes, an omega needs to be inserted in the French text. We have corrected this already a few days ago in the new version 1.08 which is now published, together with a small number of other editorial corrections. Once we have the final XML file and have learned the basics of XML we should be able to apply the same corrections in the XML file.

**Comment by anermina** [comment]
This has been solved. Closing.
