### ISSUE TITLE
Add watermark background on draft pages

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#164]
From BIPM:
> If this is not too complicated, one could also insert a watermark in the background of the document pages indicating ‘draft’.

**Comment by ronaldtse** [comment]
https://xmlgraphics.apache.org/fop/1.1/output.html

![image](https://user-images.githubusercontent.com/11865/143426388-4122792b-e643-4110-b520-60fad26bd833.png)

**Comment by Intelligent2013** [comment]
The word for draft watermark will be used from the resource `localized-string key="draft_label"`:
```
<localized-string key="draft_label" language="en">draft</localized-string>
```
```
<localized-string key="draft_label" language="fr">brouillon</localized-string>
```

The draft watermark will be displayed if:
- exists `..bibdata/version/draft` (example `<draft>v1.07</draft>`)
or
- `status/stage` contains `draft` or `projet` (fr)

**Comment by Intelligent2013** [comment]
Done:
![image](https://user-images.githubusercontent.com/5559926/143477202-6699e313-deaf-493a-8bc2-dc8d6eff79e6.png)
![image](https://user-images.githubusercontent.com/5559926/143477265-a222b0ba-ab53-4791-9066-49dccf056dc2.png)

[examples.zip](https://github.com/metanorma/bipm-si-brochure/files/7604367/examples.zip)

**Comment by ronaldtse** [comment]
> The word for draft watermark will be used from the resource `localized-string key="draft_label"`:
> 
> ```
> <localized-string key="draft_label" language="en">draft</localized-string>
> ```
> 
>  ```
> <localized-string key="draft_label" language="fr">brouillon</localized-string>
> ```
> 
> The draft watermark will be displayed if:
> 
> * exists `..bibdata/version/draft` (example `<draft>v1.07</draft>`)
>   or
> * `status/stage` contains `draft` or `projet` (fr)

@Intelligent2013 Do we need this to be set in Metanorma AsciiDoc? If so can you please help add a new issue? Thanks.

**Comment by Intelligent2013** [comment]
> Do we need this to be set in Metanorma AsciiDoc? If so can you please help add a new issue? Thanks.

@ronaldtse no need to change anything. These values are present already in xml.

**Comment by ronaldtse** [comment]
Thanks!
