### ISSUE TITLE
(URGENT) Broken GitHub Pages deployment

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#167]
<img width="958" alt="Screenshot 2022-01-18 at 7 17 49 PM" src="https://user-images.githubusercontent.com/11865/149927627-b41e3ae0-c6c5-4b16-9cb6-7c1804b922c6.png">

We want to deploy the contents of the `site/` directory, not to deploy the `site/` directory itself.

This is a bug since we updated the GHA workflows, and likely applies to all other mn-samples-* repositories.

**Comment by ronaldtse** [comment]
i.e. the gh-pages branch should contain an `index.html`.

**Comment by CAMOBAP** [comment]
waiting for CI

**Comment by ronaldtse** [comment]
It worked, thanks @CAMOBAP !
