### ISSUE TITLE
PDF: English index showing "BROUILLON" instead of English watermark "DRAFT"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#171]
English index showing "BROUILLON" instead of English watermark "DRAFT":
<img width="595" alt="Screenshot 2022-06-20 at 4 41 19 PM" src="https://user-images.githubusercontent.com/11865/174550161-bc0659fb-25b0-4f44-af4c-8ab97b410a4e.png">

_Originally posted by @ronaldtse in https://github.com/metanorma/bipm-si-brochure/issues/168#issuecomment-1160091985_

**Comment by Intelligent2013** [comment]
Confirmed. This issue occurs in the PDF for 'collection' only.
si-brochure-en.pdf is correct.

**Comment by Intelligent2013** [comment]
Issue fixed. BIPM xslt updated. But metanorma-bipm didn't update yet due the error https://github.com/metanorma/metanorma-bipm/runs/6969627023?check_suite_focus=true

**Comment by ronaldtse** [comment]
Confirmed. Closing. Build error is another issue that will be handled separately.

<img width="477" alt="Screenshot 2022-06-23 at 12 17 38 AM" src="https://user-images.githubusercontent.com/11865/175067493-3f17ce12-0cbb-4d67-abba-11ba3e760efc.png">
