### ISSUE TITLE
(URGENT) Meeting references are not being hidden and they don't contain any link to an external source

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#172]
> Meeting references are not being hidden and they don't contain any link to an external source, even when this link is present in the YAML file from relaton-data-bipm repository

The meeting references are still not hidden and are not linked:
<img width="561" alt="Screenshot 2022-06-20 at 5 40 09 PM" src="https://user-images.githubusercontent.com/11865/174561451-2f28712c-c702-4bea-ae37-e09e1b92b298.png">

_Originally posted by @ronaldtse in https://github.com/metanorma/bipm-si-brochure/issues/169#issuecomment-1160149566_

**Comment by ronaldtse** [comment]
> If you want references to contain parsable URIs that are used in citation

I think this is not the ask right now. I don't know why there is this interpretation. The point is clicking on a citation to the Meeting (in the content) should lead directly to the URL (if the bibliographic entry is hidden), which is provided in the Relaton data for the CIPM Meeting.

**Comment by opoudjis** [comment]
Ronald, I repeat, Metanorma is not magic. The citation only leads to the URL, because there is something in the bibliographic entry recognised as a resource URL. Shoving a URL in the title is not going to make it recognised as a resource URL.

**Comment by opoudjis** [comment]
> It is the Relaton item at CIPM Meeting 4 that provides the URL.

It clearly doesn't, since the bibitem **is not being fetched**:

````
<bibitem id="PV41_h" hidden="true">
  <formattedref format="application/x-isodoc+xml">CIPM: Proceedings of the 4th meeting (1879): <link target="https://www.bipm.org/documents/20126/56719035/CIPM4.pdf/47e647d4-26c2-d3d6-b367-e749fb22b261"/>. [CIPM Meeting 4] </formattedref>
  <docidentifier type="BIPM">CIPM Meeting 4</docidentifier>
  <docnumber>4</docnumber>
</bibitem>
````

`formattedref` is what happens when the bibitem is not fetched.

````
bundle exec relaton fetch "BIPM CIPM Meeting 4"
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Top level ::CompositeIO is deprecated, require 'multipart/post' and use `Multipart::Post::CompositeReadIO` instead!
Top level ::Parts is deprecated, require 'multipart/post' and use `Multipart::Post::Parts` instead!
No matching bibliographic entry found



01:52:16 * ~/Documents/Arbeit/upwork/ribose/metanorma-standoc/spec/metanorma[main] $ bundle exec relaton fetch "BIPM CIPM Meeting 41"
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Top level ::CompositeIO is deprecated, require 'multipart/post' and use `Multipart::Post::CompositeReadIO` instead!
Top level ::Parts is deprecated, require 'multipart/post' and use `Multipart::Post::Parts` instead!
[relaton-bipm] ("BIPM CIPM Meeting 41") fetching...
[relaton-bipm] ("BIPM CIPM Meeting 41") found CIPM Meeting 41
<bibitem id="CIPMMeeting41">
  <fetched>2022-06-23</fetched>
  <title format="text/plain" language="en" script="Latn">41st meeting of the CIPM (1945, 1946)</title>
  <title format="text/plain" language="fr" script="Latn">41e réunion du CIPM (1945, 1946)</title>
  <uri type="src">https://www.bipm.org/en/committees/ci/cipm/41-1946</uri>
  <uri type="src">https://raw.githubusercontent.com/metanorma/bipm-data-outcomes/main/cipm/meetings-en/meeting-41.yml</uri>
  <uri type="src">https://raw.githubusercontent.com/metanorma/bipm-data-outcomes/main/cipm/meetings-fr/meeting-41.yml</uri>
  <docidentifier type="BIPM" primary="true">CIPM Meeting 41</docidentifier>
  <docnumber>CIPM Meeting 41</docnumber>
  <date type="published">
    <on>1946-10-29</on>
  </date>
  <contributor>
    <role type="publisher"/>
    <organization>
      <name>Bureau International des Poids et Mesures</name>
      <abbreviation>BIPM</abbreviation>
      <uri>www.bipm.org</uri>
    </organization>
  </contributor>
  <language>en</language>
  <language>fr</language>
  <script>Latn</script>
</bibitem>

````

**Comment by ronaldtse** [comment]
I'm confused.
* In the screenshot they are CGPM Meetings 9 and 14, CIPM Meeting 41.
* In the list you are seeking for CIPM Meeting 4, 43 and 51.

Can you elaborate?

**Comment by opoudjis** [comment]
Do 

````
bundle exec relaton fetch "BIPM CIPM Meeting 41"
````

It works.

Do 

````
bundle exec relaton fetch "BIPM CIPM Meeting 4"
````

It returns nothing.

The broken meetings are:

CIPM Meeting 4
CIPM Meeting 43
CIPM Meeting 51

**Comment by ronaldtse** [comment]
You could have been more specific... The problem is due to these lines:

```adoc
// CIPM Meeting 43 - Hand-crafted
* [[[PV22_h, hidden(CIPM Meeting (1950))]]], CIPM: Proceedings of the 43rd meeting (1950): https://www.bipm.org/documents/20126/56719035/CIPM43.pdf/172ac044-091b-4162-f9b4-f2b095d0b173.

// CIPM Meeting 51 - Hand-crafted
* [[[PV30_h, hidden(CIPM Meeting (1962))]]], CIPM: Proceedings of the 51st meeting (1962): https://www.bipm.org/documents/20126/56719035/CIPM51.pdf/deb1a820-e301-a5af-1630-f970118d972c.

// CIPM Meeting  4 - Hand-crafted
* [[[PV41_h, hidden(CIPM Meeting 4)]]], CIPM: Proceedings of the 4th meeting (1879): https://www.bipm.org/documents/20126/56719035/CIPM4.pdf/47e647d4-26c2-d3d6-b367-e749fb22b261.
```

These lines were necessary because the Relaton database doesn't have these entries.

The Relaton database does not have these entries because they are not entered at the BIPM's website:
https://www.bipm.org/en/committees/ci/cipm/meetings

Meetings 4, 43 and 51 are not provided.
<img width="1067" alt="Screenshot 2022-06-23 at 1 05 57 AM" src="https://user-images.githubusercontent.com/11865/175079828-53d0ca1c-be15-4ba6-82c6-c9c0b0f2bb3b.png">

In this case I believe we should use AsciiBib to fill in the details.

@opoudjis are you okay if @metanorma/editors go ahead and perform this change?

**Comment by ronaldtse** [comment]
Confirmed that the Meeting bibliography items are no longer showing.
