### ISSUE TITLE
Update MEP documents to latest editions

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#173]
The file sources/mep-kilogram-definition-en.adoc has a date of 2020-08-04 and is no longer current.

The latest version is 2021-07-07:
https://www.bipm.org/documents/20126/41489673/SI-App2-kilogram.pdf/5881b6b5-668d-5d2b-f12a-0ef8ca437176

We should keep the old mep-kilogram-definition-en.adoc in a separate location, i.e. under sources/archive/

**Comment by manuelfuenmayor** [comment]
Task is merged, closing.
