### ISSUE TITLE
Replace AsciiBib encoding of CIPM meetings 4, 43 and 51 with parsed entries

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#178]
https://github.com/metanorma/bipm-data-outcomes/issues/14

The CIPM meetings 4, 43 and 51 used to be missing from the BIPM website but they have now entered them upon our request.

Once metanorma/bipm-data-outcomes#14 is complete, relaton-data-bipm should be updated, and then we can remove the AsciiBib encodings from the SI Brochure, then all the CIPM meetings will be automatically fetched.

**Comment by andrew2net** [comment]
The relaton-data-bipm autoupdated daily now. There is also "Run workflow" button for the `fetch_data` workflow to update it as you need.

**Comment by ronaldtse** [comment]
Actually we need to replace the asciibib in this repo. Reopening.

**Comment by ronaldtse** [comment]
PR created in metanorma/bipm-si-brochure#179
