### ISSUE TITLE
When compiled in a bilingual collection, the English version should not be showing the French SI Brochure reference

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#181]
The French version is showing an empty bibliography. When there are no items to show, the bibliography should not be shown.

<img width="594" alt="Screenshot 2022-07-05 at 10 31 50 PM" src="https://user-images.githubusercontent.com/11865/177339730-7339e9af-69b8-4a26-9c0e-706c393a3e8a.png">

The English version is showing the French document as its sole bibliography item.

<img width="597" alt="Screenshot 2022-07-05 at 10 31 39 PM" src="https://user-images.githubusercontent.com/11865/177339693-485ef837-ca7f-4654-ad8c-370051f1ec80.png">

The French version has the English version in the bibliography as:
```adoc
[bibliography]
== Bibliography

* [[[english-doc,repo:(current-metanorma-collection/si-brochure-en)]]], Bureau International des Poids et Mesures. _SI Brochure_. Édition 9.
```

The English version has the French version in the bibliography as:
```adoc
[bibliography]
== Bibliography

* [[[french-doc,dropid(repo:(current-metanorma-collection/si-brochure-fr))]]] Bureau International des Poids et Mesures. _Brochure sur le SI_. Edition 9.
```

Issues:
1. Notice there is a difference in the `dropid` behavior.
2. If a referenced item is part of the current Metanorma collection, it should not be shown within the collection itself. i.e. If part of the same collection, the English reference should not be shown in the French version, and the French reference should not be shown in the English version

**Comment by opoudjis** [comment]
dropid is indeed preventing metanorma from recognising current-metanorma-collection/si-brochure-en as a repository identifier.

**Comment by opoudjis** [comment]
the order of processing the nested prefixes of document identifiers in standoc is the wrong way around.
