### ISSUE TITLE
When collection omits all bibliographic items, the empty bibliography should not be rendered

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#182]
(This is a follow up from #181 )

collection_en.pdf:

<img width="487" alt="image" src="https://user-images.githubusercontent.com/11865/177437518-c8fba865-c9d5-410c-8477-743cab7a733c.png">

collection_fr.pdf:
<img width="494" alt="Screenshot 2022-07-06 at 9 23 02 AM" src="https://user-images.githubusercontent.com/11865/177437557-e9a567b0-d2fe-4da3-887b-a53ea1ba7ac5.png">

collection.pdf:
French:
<img width="489" alt="image" src="https://user-images.githubusercontent.com/11865/177437599-b38b6175-7abb-478e-8be0-6c20fb7b5e97.png">

English:
<img width="487" alt="image" src="https://user-images.githubusercontent.com/11865/177437630-f4cab3dc-f1e3-4879-b5a2-c3ee6942b435.png">

**Comment by opoudjis** [comment]
I could have sworn I already had code to do this automatically, but I can't find it, so I'll reintroduce it.

**Comment by ronaldtse** [comment]
Reopening to track progress.

## Using `main` branch with latest released gems

The French bibliography is empty and it shows.
<img width="610" alt="Screenshot 2022-07-12 at 2 22 12 AM" src="https://user-images.githubusercontent.com/11865/178322024-a0a91403-3761-4c77-9732-827265c0d0f9.png">


The English bibliography is not empty (regression of #181 ):

<img width="621" alt="Screenshot 2022-07-12 at 2 22 21 AM" src="https://user-images.githubusercontent.com/11865/178322050-8e0c77f4-286e-4ac7-8b4b-648909095393.png">

## Using git gems

Blocked by https://github.com/metanorma/metanorma-bipm/issues/182

**Comment by opoudjis** [comment]
Released gem does not include this commit. Rereleasing.

**Comment by opoudjis** [comment]
No, not rereleasing. That code was authored after release.

Ronald, pull isodoc from github. I did confirm this my side last week. And spurious bug reports are an abuse of my limited time.

**Comment by ronaldtse** [comment]
Well, this is half fixed.

The "bibliography" sections are gone, but the pages for bibliography still exist:

<img width="482" alt="image" src="https://user-images.githubusercontent.com/11865/178403202-b6d7b4eb-cb67-43c5-a620-809575d39cc2.png">
<img width="478" alt="Screenshot 2022-07-12 at 12 36 42 PM" src="https://user-images.githubusercontent.com/11865/178403236-89ed5b93-ac7b-4603-bf83-9bd0a9f70ab6.png">

Apparently this is a PDF issue? @Intelligent2013 can you help check? Thanks.

**Comment by Intelligent2013** [comment]
@ronaldtse yes, the empty bibliography should be ignored.  Will fix.

**Comment by Intelligent2013** [comment]
@ronaldtse BIPM xslt updated, but doesn't updated in metanorma-bipm due the error:
`Error: The format of 'metanorma-ci' is not a valid email address with display name` (https://github.com/metanorma/mn-native-pdf/runs/7295258351?check_suite_focus=true)

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 , @CAMOBAP is now investigating the action failures at mn-native-pdf

**Comment by ronaldtse** [comment]
@CAMOBAP @Intelligent2013 confirm this is completed. Thank you!
