### ISSUE TITLE
BIPM final review: content errors to be fixed

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#189]
To @metanorma/editors 

BIPM has performed their final review and discovered the following issues. Most of the issues concern the French version (this is the first time the French version was reviewed).

The Excel file is provided here and also reproduced below for convenience:
[20220915-bipm-si-brochure-final-review.xlsx](https://github.com/metanorma/bipm-si-brochure/files/9573309/20220915-bipm-si-brochure-final-review.xlsx)

NOTE: The equations don't look right on GitHub, you need to check the Excel file.

Number | Page | Clause/paragraph | Comment |  
-- | -- | -- | -- | --
1 | 12 | 1.1, first paragraph, last line | remove "Convention du Mètre mètre (m); should read :  « Le BIPM et la Convention du Mètre » (page 5). |  
2 | 17 | side note | Replace "chapître" by "chapitre" (regular i) |  
3 | 19 | 2. paragraph below ampere equations | insert missing closing bracket after "magnétique" |  
4 | 19 | 2. paragraph above kelvin | replace "1/μ0c2" with "1/μ0c2" |  
5 | 21 | last paragraph on mole | insert missing closing bracket after "mole" |  
6 | 23 | equation | space to be removed between Θ and  ɛ (or is this related to the somewhat special character Θ ?) |  
7 | 24 | fourth paragraph | Replace "chapître" by "chapitre", two times |  
8 | 32 | Table 8 | In the 4. column, the number 1 is missing at the beginning of the line for the angle units  minute and the second: "1' = (1/60)° …" and "1'' = (1/60)'…" |  
9 | 32 | Table 8 | replace "neper" by "néper" |  
10 | 32 | Table 8 | replace "decibel" by "décibel" |  
11 | 33 | 2. last paragraph | insert space between "10" and "lg" |  
12 | 35 | 5.4.1, 1. paragraph | replace "cm,V" with "cm,V", "V" in italics |  
13 | 35 | 5.3, third paragraph | Replace "chapître" by "chapitre" |  
14 | 37 | 5.4.3, 1. paragraph | insert "minute" in "… pour le degré, la minute et la seconde d’angle plan" |  
15 | 37 | 5.4.4, example 1 | remove space in "-0, 234" |  
16 | 38 | 5.4.4, example 2: | replace "43.279.168.29" with "43.279,168.29" |  
17 | 38 | 5.4.4, example 3: | replace "3279.1683" with "3279,1683" |  
18 | 40 | first line | no accent on the second e: réel |  
19 | 46 | 6th section | In title, add a space and a colon after SI: "Unités en usage avec le SI : un exemple, le litre" |  
20 | 46 | 6th section , first line | Replace by "d'1 kg d'eau" (was also wrong in BIPM Brochure) |  
21 | 48 | list item 2 | the first "poids" and "force" should be in italics |  
23 | 53 | CIPM, 1956, Res. 1 | "seconde" bold in title |  
24 | 58 | CIPM 1967 | "CIPM recommandation 2" should be replaced by "Recommandation 2 du CIPM" | general rule, to be applied systematically
25 | 60 | Resolution 7 | closing brackets missing in title  after "nouvelle" |  
26 | 60 | side note (1) | anomalous reference, also in English text |  
27 | 61 | CCDS 1970 | "CCTF Recommandation 2" should be replaced by "Recommandation 2 du CCTF" | general rule, to be applied systematically
28 | 64 | second paragraph after "décide" | closing brackets missing in title  after "nouvelle" |  
29 | 73 | last side note | "25" should be in bold |  
30 | 80 | fourth bullet after "recommande" | the F in 2F7/2 should not be initalics |  
31 | 81 | 5. bullet point | replace "1re réunion" with "1re réunion" |  
32 | 85 | 5. bullet point | replace "4f 136s2" with "4f13 6s2", the 13 shall be attached to 4f, not to 6s (was also wrong in original) |  
33 | 86 | 1. bullet point | replace "5d 106s 2S1/2 - 5d 96s2 2D5/2" with "5d10 6s 2S1/2 - 5d9 6s22D5/2" (also wrong in original) |  
34 | 87 | last bullet | Add a space before the opening bracket et replace "octopôle" by "octupole" |  
35 | 88 | first bullet | replace "quadrupôle" by "quadrupole" |  
36 | 88 | second last paragraph | replace "df" by "d/f" |  
37 | 89 | list of constants, 3. entry | replace "J/s" with "J s" |  
38 | 107 | entry unité(s), en dehors du | replace by "en dehors du SI" |  
39 | 125 | 1. line | add space in  "or electric" |  
40 | 133 | foot note (b) | remove links to Wikipedia |  
41 | 144 | example 1 | V in Vmax not in italics |  
42 | 159 | table, third entry "cubic metre" | replace m2 by m3 |  
43 | 165 | side notes | First and second side notes are identical, delete one |  
44 | 166 | Res.3, 1. bullet point | replace "°" with "deg" |  
45 | 169 | 14th CGPM,Pascal and siemens | wrong link, should point to "CGPM Declaration  1971" https://www.bipm.org/en/committees/cg/cgpm/14-1971/resolution- |  
46 | 169 | SI unit of amount of substance | link to wrong resolution. Should be CGPM Resolution 3 (1971) https://www.bipm.org/en/committees/cg/cgpm/14-1971/resolution-3 |  
47 | 183 | Rec. 3, last bullet point | replace νn with νn , number as subscript |  
48 | 187 | 4. bullet point after recommends | "F" in 2F7/2 not in italics |  
49 | 192 | 3. bullet point | replace "4f 136s2" with "4f13 6s2", the 13 is attached to 4f, not to 6s (was also wrong in original) |  
50 | 192 | 5. bullet point | replace "5d 106s 2S1/2 - 5d 96s2 2D5/2" with "5d10 6s 2S1/2 - 5d9 6s22D5/2" (also wrong in original) |  
51 | 193 | CIPM 2015 | reference is CIPM Recommendation 2 (2015), not Recommendation 1 |  
52 | 197 | 2. bullet point | insert space in "fixed numerical" |  
53 | 200 | A4.1 | The text in A4.1 belongs to A4.2 and the text in A4.2 belongs to A4.3. The text for A4.1 is missing |  

Some issues may affect software operations, for those could you please help file separate issues?

Thanks!

**Comment by manuelfuenmayor** [comment]
> 2 | 17 | side note | Replace "chapître" by "chapitre" (regular i) | 
> 7 | 24 | fourth paragraph | Replace "chapître" by "chapitre", two times |  

[Delegated](https://github.com/metanorma/metanorma-bipm/issues/193)

> 15 | 37 | 5.4.4, example 1 | remove space in "-0, 234" |  

[Delegated](https://github.com/metanorma/metanorma-bipm/issues/194)

> 24 | 58 | CIPM 1967 | "CIPM recommandation 2" should be replaced by "Recommandation 2 du CIPM" | general rule, to be applied systematically
> 27 | 61 | CCDS 1970 | "CCTF Recommandation 2" should be replaced by "Recommandation 2 du CCTF" | general rule, to be applied systematically

[Delegated](https://github.com/metanorma/metanorma-bipm/issues/195)

> 26 | 60 | side note (1) | anomalous reference, also in English text |  

[Delegated](https://github.com/metanorma/metanorma-bipm/issues/196)


All other issues has been fixed in [markup](https://github.com/metanorma/bipm-si-brochure/pull/196).

**Comment by ronaldtse** [comment]
Fixed in #196. Remaining issues have been posted by @manuelfuenmayor .

**Comment by manuelfuenmayor** [comment]
> 6 | 23 | equation | space to be removed between Θ and  ɛ (or is this related to the somewhat special character Θ ?) |  

Yes, the additional space is (particularly) added by the Theta (Θ) special character.

**Comment by ronaldtse** [comment]
* [ ] https://github.com/metanorma/metanorma-bipm/issues/193
* [ ] https://github.com/metanorma/metanorma-bipm/issues/194
* [ ] https://github.com/metanorma/metanorma-bipm/issues/195
* [ ] https://github.com/metanorma/metanorma-bipm/issues/196
