### ISSUE TITLE
Brochure: Clarification about BIPM request

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/bipm-si-brochure#199]
From https://github.com/metanorma/bipm-si-brochure/issues/190, BIPM is requesting to address this:

<html>
<body>

49 | 140 | footnote (d) | Add hyperlinks to Metrologia citations.Reference should be "16th CGPM (1979, Resolution 6)
-- | -- | -- | --

</body>
</html>

Being the source of the issue, this part:
![issue49-3](https://user-images.githubusercontent.com/33627611/190872417-5edd3c3e-2f42-48aa-833c-ec80b5061255.PNG)

I find this request a little bit confusing. Because, first we are told to *"Add hyperlinks to Metrologia citations"*,
and after that, to change the whole reference to *"(1979, Resolution 6)"*. Which implies deleting the Metrologia reference.

Am I missing something?

**Comment by opoudjis** [comment]
I think this is poorly worded, and that the change request applies only to the first instance: "1979, Resolution 6" is cited twice ("1979, Resolution 6" and "CGPM Resolution 6 (1979)" ---the first is intended as a  discursive explanation of the the reference, the second as the actual citation. I think the intent here is to drop the second.

The hyperlinks should be automated for Metrologia, as we've discussed in chat.

So I interpret this as:

````
was adopted by the 16th CGPM (<<BIPM CGPM Resolution 1979-06,1979, Resolution 6>> and <<BIPM Metrologia 16 55,_Metrologia_, 1980, **16**, 56--57>>)
````

Note that "News from the BIPM" is pp 55-61, so this is citing an extent within the article: "`,%page=56-57`". I have no interest in this stage in generating the "_Metrologia_, 1980, **16**, 56--57" citation automatically, but that can be done much, much later.

**Comment by manuelfuenmayor** [comment]
Thanks @opoudjis, I'm taking your approach.
