### ISSUE TITLE
BIPM XSLT: Remove colons insertions

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/bipm-si-brochure#202]
From issue: https://github.com/metanorma/bipm-si-brochure/issues/191#issuecomment-1257158689

To do:
> remove your colon insertion, so that I can insert it with appropriate localisation in Presentation XML instead.

**Comment by opoudjis** [comment]
I'm not going to get this done before tomorrow's release, so please don't push anything before Tuesday.

**Comment by Intelligent2013** [comment]
For independent Appendixes need use both `type="part"` and `type="part-with-numbering"`:
```xml
<title language="en" format="text/plain" type="part">Mise en pratique for the definition of the kelvin in the SI</title>
<title language="en" format="text/plain" type="part-with-numbering">Part 2: Mise en pratique for the definition of the kelvin in the SI</title>
```
First title on the cover page, second one on 3rd page.

**Comment by Intelligent2013** [comment]
BIPM XSLT update.
Done in https://github.com/metanorma/metanorma-bipm/pull/211.
