### ISSUE TITLE
Indentation of table title

### ISSUE THREAD

**Issue by anermina** [metanorma/bipm-si-brochure#204]
Titles of tables and figures are indented if they span multiple rows. However, I'm not sure if the current output is correct, since the original MEP document doesn't have the titles indented at all.

Example (original is on the left and the generated document is on the right):
![image](https://user-images.githubusercontent.com/55683568/192147825-2d7bb48e-fb35-4725-b581-de4dbb28a1de.png)

**Comment by ronaldtse** [comment]
I think we need to decide on the proper representation of the table caption, whether it is inline like the left or in a table form like the right.

**Comment by Intelligent2013** [comment]
Initially, BIPM XSLT was developed for BIPM SI Brochure.

Original PDF From https://www.bipm.org/en/publications/si-brochure:
![image](https://user-images.githubusercontent.com/5559926/192225832-4b7fc94f-298b-4573-a8d1-67d6c9d7adfd.png)

Currently rendered PDF by BIPM XSLT:
![image](https://user-images.githubusercontent.com/5559926/192225310-99584350-5586-4fc7-8772-e7fd5e3b4809.png)

Any rendered PDF by BIPM XSLT will have these styles. There aren't any differentiations between BIPM Brochure and independent appendixes.

Question: should I add one more style for table title for independent appendixes?

**Comment by ronaldtse** [comment]
No, we should only have one style. BIPM will only use the same style across documents, starting from the SI Brochure.

However, it seems that the caption in @anermina 's screenshot is too much indented towards the right side?

**Comment by Intelligent2013** [comment]
> However, it seems that the caption in @anermina 's screenshot is too much indented towards the right side?

This occurs due the difference length `Tableau` (fr) and `Table` (en). I'll fix this issue (change the paragraph layout with indentation to the list with one item, or non-bordered table with one row).

**Comment by ronaldtse** [comment]
Thanks!

**Comment by Intelligent2013** [comment]
BIPM XSLT updated in https://github.com/metanorma/metanorma-bipm/pull/211:

![image](https://user-images.githubusercontent.com/5559926/192822679-783b6814-2618-477b-ba17-dbd886fc87fe.png)

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 !
