### ISSUE TITLE
BIPM: Initials vs. list items issue

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/bipm-si-brochure#205]
From https://github.com/metanorma/bipm-si-brochure/issues/191#issuecomment-1257269763:

`00-preface.adoc` changed in https://github.com/metanorma/bipm-si-brochure/commit/8acfc07f13e388945fc0c3c3b0cd715be064bbe6#diff-e71d3792f85922d11579c041ba90b3aa12e272669aa164e473cb33130c1f68cf:
![image](https://user-images.githubusercontent.com/5559926/192163080-b6761ea1-a502-4d81-9bdb-f6f4da192046.png)

and in XML there aren't `B.` and `J.` before last names now:
```xml
<td align="center" valign="top">
	<ol id="_7fcac708-d0af-4b30-85e9-616cd5b1bfe3" type="upperalpha">
		<li>
			<p id="_8b56e097-159d-363a-25e9-ff7392921eaf">Inglis
                                    <br/>Président du CIPM</p>
		</li>
	</ol>
</td>
<td align="center" valign="top">
	<ol id="_276917e4-1d26-3d0f-0985-80cfaec695be" type="upperalpha">
		<li>
			<p id="_f6e5f388-8dc3-25d9-d73e-e858106095e0">Ullrich
                                    <br/>Président du CCU</p>
		</li>
	</ol>
</td>
```

Previous XML:
```xml
<td align="center" valign="top">
	<p id="_4ec62cb2-9b52-5fda-779a-19faaa9d9448">B.Inglis
                            <br/>Président du CIPM</p>
</td>
<td align="center" valign="top">
	<p id="_a6879263-38a2-d9e9-49a0-94931039e56e">J.Ullrich
                            <br/>Président du CCU</p>
</td>
```

From: https://github.com/metanorma/bipm-si-brochure/issues/191#issuecomment-1258862279

> Asciidoctor is interpreting "B. " and "J. " at the beginning of a paragraph as ordered list ordinals. 
> Your workaround is to replace the space with `&#xa0;` (NBSP), which you should be doing anyway.

@manuelfuenmayor could you update the adoc, and check another last changes (I've saw this issue in the this table, but may be there are another places...)

**Comment by manuelfuenmayor** [comment]
@Intelligent2013, I have inserted `&#xa0;` only in table environments which I think is what we need.
Thanks!

**Comment by Intelligent2013** [comment]
@manuelfuenmayor thanks!
