### ISSUE TITLE
Fix build

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#211]
Build needs to be fixed after the recent changes at actions-mn.

**Comment by CAMOBAP** [comment]
Fixed

**Comment by ronaldtse** [comment]
@CAMOBAP is it pushed? It's not fixed yet...

**Comment by ronaldtse** [comment]
@CAMOBAP how about we use Metanorma Docker instead of Metanorma Snap?

**Comment by CAMOBAP** [comment]
I think we have both workflows for this repo
