### ISSUE TITLE
BIPM requested fixes 3: bibliography problem with the processing of Declarations

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#223]
From Michael Stock:

In the bibliography there seems to be a problem with the processing of Declarations – see for example references [65E/64F] and [74E/73F] – which are missing the format DECN as well as their details.

**Comment by opoudjis** [comment]
@anermina Many of these issues are going to need to be escalated to @andrew2net or myself, but you get to diagnose that first.

**Comment by anermina** [comment]
I do not see any issues with either Declarations or Decisions.

French:
![image](https://github.com/user-attachments/assets/afd011be-437a-4e96-8d22-b365e33a3298)
![image](https://github.com/user-attachments/assets/ae082dc2-289b-479f-a750-13a8cbb3e8c8)
![image](https://github.com/user-attachments/assets/5ae6300e-41ef-4605-bd22-2aca2b7fc83d)
![image](https://github.com/user-attachments/assets/03691600-8705-4171-87a1-daec56b54393)

English:
![image](https://github.com/user-attachments/assets/1310a04c-5fbe-4298-9d05-3394e6b54606)
![image](https://github.com/user-attachments/assets/783a10f6-51c4-4dc8-9941-d196e437f2c7)
![image](https://github.com/user-attachments/assets/8c6e721e-3626-4b44-ba5c-38330a0b79e9)
![image](https://github.com/user-attachments/assets/fa1eb4df-ef63-4a0a-ab0c-2bd940160b00)

@ronaldtse could you please confirm this is the expected output?

**Comment by manuelfuenmayor** [comment]
Ping @ronaldtse, on this issue.

**Comment by ronaldtse** [comment]
Closing issue and keeping new issue separate.
