### ISSUE TITLE
BIPM requested fixes 5: references to Metrologia

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#225]
From Michael Stock:

There seems to be a problem with the form of the references to Metrologia. In both the English and French versions (e.g. p.107 [E] p.112 [F])  the information is repeated several times:
![image002](https://github.com/metanorma/bipm-si-brochure/assets/11865/c4672e72-46a3-4ffd-ba57-d9f8fcf0931a)

Here I would have written simply:

“J Terrien (1972) Metrologia 8(1) 32-36. doi 10.1088/0026-1394/8/1/006 “

**Comment by anermina** [comment]
I do not get the exact same output, but there is a duplication:
![image](https://github.com/metanorma/bipm-si-brochure/assets/55683568/ee7f3577-4277-4e8b-a7e2-3d2bb007e78c)

This is how the reference is fetched:
````
[relaton-bipm] (BIPM Metrologia 8 1 32) Fetching from Relaton repository ...
[relaton-bipm] Downloaded index from https://raw.githubusercontent.com/relaton/relaton-data-bipm/master/index2.zip
[relaton-bipm] (BIPM Metrologia 8 1 32) Found: `Metrologia 8 1 32`
<bibdata type="article" schema-version="v1.2.8">
  <fetched>2024-04-08</fetched>
  <title format="text/plain" language="en" script="Latn">News from the Bureau International des Poids et Mesures</title>
  <uri type="src">https://doi.org/10.1088/0026-1394/8/1/006</uri>
  <uri type="doi">https://doi.org/10.1088/0026-1394/8/1/006</uri>
  <docidentifier type="BIPM" primary="true">Metrologia 8 1 32</docidentifier>
  <docidentifier type="doi">10.1088/0026-1394/8/1/006</docidentifier>
  <date type="published">
    <on>1972-01-01</on>
  </date>
  <contributor>
    <role type="author"/>
    <person>
      <name>
        <surname language="en" script="Latn">J Terrien</surname>
      </name>
    </person>
  </contributor>
  <copyright>
    <from>1972</from>
    <owner>
      <organization>
        <name>Published under licence by IOP Publishing Ltd</name>
      </organization>
    </owner>
  </copyright>
  <relation type="hasManifestation">
    <bibitem>
      <title format="text/plain" language="en" script="Latn">News from the Bureau International des Poids et Mesures</title>
      <date type="ppub">
        <on>1972-01-01</on>
      </date>
      <medium>
        <carrier>print</carrier>
      </medium>
    </bibitem>
  </relation>
  <series>
    <title format="text/plain" language="en" script="Latn">Metrologia</title>
  </series>
  <extent>
    <locality type="volume">
      <referenceFrom>8</referenceFrom>
    </locality>
  </extent>
  <extent>
    <locality type="issue">
      <referenceFrom>1</referenceFrom>
    </locality>
  </extent>
  <extent>
    <locality type="page">
      <referenceFrom>32</referenceFrom>
      <referenceTo>36</referenceTo>
    </locality>
  </extent>
  <ext schema-version="v1.0.0">
    <doctype>article</doctype>
  </ext>
</bibdata>
````

@andrew2net could you please check why this is happening?

**Comment by anermina** [comment]
This issue is still present. 
![image](https://github.com/user-attachments/assets/21f06134-c53f-40db-a93b-838a492f18e0)
![image](https://github.com/user-attachments/assets/a604a142-d521-41fd-ad23-46841df96a96)

@opoudjis could you please take a look?

**Comment by ronaldtse** [comment]
@opoudjis this is urgent, thanks.

**Comment by ronaldtse** [comment]
> @anermina the output is rendered by Metanorma, I can't handle it in Relaton. We need to ask @opoudjis

Is this a relation-render issue?

**Comment by opoudjis** [comment]
Arguably. Metanorma thinks that `<docidentifier type="BIPM" primary="true">Metrologia 8 1 32</docidentifier>` is the DOI-style authoritative identifier of the reference, and is providing it like it would for a DOI. Nothing is telling it not to. There is also a bug of repeating the authoritative identifier.

The real thing to do here is to reject any notion that journal articles have BIPM primary identifiers in references. We may refer to this journal article as "Metrologia 8 1 32", but that identifier should not appear anywhere in references. And rather than argue with Relaton on when to display or not display BIPM identifiers for journal articles, I'll just suppress them. This will luckily not take long.

**Comment by opoudjis** [comment]
and given how this release has been completely blown up, including but not limited to Nokogiri, there will be plenty of time to get this in before it is finalised. :-|

**Comment by opoudjis** [comment]
I will add this as a test case to ensure correct rendering, this is one that took me unawares, because I didn't realise we were treating "Metrologia 8 1 32" as an authoritative identifier. (Which it is, but not for rendering purposes.)

**Comment by opoudjis** [comment]
Just to confirm, we are not doing author-date references for these, right?

**Comment by opoudjis** [comment]
Actually, I can exclude the BIPM identifiers point-blank for any journal article, because ISBN ISSN DOI are other-identifier, not  authoritative-identifier.

**Comment by opoudjis** [comment]
I've got it rendering correctly, but the semicolons in the extent should not be there: 8; (1); 32-36 are being parsed as discontinuous extents. That, I'm afraid, is an error in the Relaton:

````
  <extent>
    <locality type="volume">
      <referenceFrom>8</referenceFrom>
    </locality>
  </extent>
  <extent>
    <locality type="issue">
      <referenceFrom>1</referenceFrom>
    </locality>
  </extent>
  <extent>
    <locality type="page">
      <referenceFrom>32</referenceFrom>
      <referenceTo>36</referenceTo>
    </locality>
  </extent>
````

should be:

````
  <extent>
    <locality type="volume">
      <referenceFrom>8</referenceFrom>
    </locality>
    <locality type="issue">
      <referenceFrom>1</referenceFrom>
    </locality>
    <locality type="page">
      <referenceFrom>32</referenceFrom>
      <referenceTo>36</referenceTo>
    </locality>
  </extent>
````

—a single extent. Raising as issue.

**Comment by opoudjis** [comment]
This is what I'm now getting:

![Screenshot 2024-12-10 at 21 37 23](https://github.com/user-attachments/assets/16d6f9a2-a071-4f24-ada6-74664795ecaf)

The semicolons will go away once the encoding of extent is fixed.
