### ISSUE TITLE
BIPM requested fixes 6: problem with the reference to the CIPM Declaration 1971-00

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#226]
From Michael Stock:

There is a problem with the reference to the CIPM Declaration 1971-00 in the section on the 14th CGPM 1971 in the French version (p. 61) . As a consequence, this reference is missing in the French bibliography, whereas it is included as [14] in the English bibliography. Therefore, the French bibliograph has 111 entries, whereas the English has 112.

**Comment by anermina** [comment]
Fixed in https://github.com/metanorma/bipm-si-brochure/pull/231. Closing.
