### ISSUE TITLE
BIPM requested fixes 9: Is there a reason why the links to Metrologia in the Bibliography have not been made active?

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#229]
From Michael Stock:

Is there a reason why the links to Metrologia in the Bibliography have not been made active?

**Comment by anermina** [comment]
The reason for this should be that the `uri` is not fetched.

Example:
````
bundle exec relaton fetch "BIPM Metrologia 52 1 155"
[relaton-bipm] (BIPM Metrologia 52 1 155) Fetching from Relaton repository ...
[relaton-bipm] (BIPM Metrologia 52 1 155) Found: `Metrologia 52 1 155`
<bibdata type="article" schema-version="v1.2.8">
  <fetched>2024-02-22</fetched>
  <title format="text/plain" script="Latn">News from the BIPM laboratories: 2014</title>
  <docidentifier type="BIPM" primary="true">Metrologia 52 1 155</docidentifier>
  <docidentifier type="doi">10.1088/0026-1394/52/1/155</docidentifier>
  <date type="published">
    <on>2015-01-30</on>
  </date>
  <contributor>
    <role type="author"/>
    <person>
      <name>
        <forename language="en" script="Latn">Jos</forename>
        <forename language="en" script="Latn">Maria</forename>
        <surname language="en" script="Latn">Los Arcos</surname>
      </name>
      <affiliation>
        <organization>
          <name/>
        </organization>
      </affiliation>
    </person>
  </contributor>
  <contributor>
    <role type="author"/>
    <person>
      <name>
        <forename language="en" script="Latn">Michael</forename>
        <surname language="en" script="Latn">Stock</surname>
      </name>
      <affiliation>
        <organization>
          <name/>
        </organization>
      </affiliation>
    </person>
  </contributor>
  <contributor>
    <role type="author"/>
    <person>
      <name>
        <forename language="en" script="Latn">Robert</forename>
        <surname language="en" script="Latn">Wielgosz</surname>
      </name>
      <affiliation>
        <organization>
          <name/>
        </organization>
      </affiliation>
    </person>
  </contributor>
  <contributor>
    <role type="author"/>
    <person>
      <name>
        <forename language="en" script="Latn">Felicitas</forename>
        <surname language="en" script="Latn">Arias</surname>
      </name>
      <affiliation>
        <organization>
          <name/>
        </organization>
      </affiliation>
    </person>
  </contributor>
  <contributor>
    <role type="author"/>
    <person>
      <name>
        <forename language="en" script="Latn">Martin</forename>
        <surname language="en" script="Latn">Milton</surname>
      </name>
      <affiliation>
        <organization>
          <name/>
        </organization>
      </affiliation>
    </person>
  </contributor>
  <copyright>
    <from>2015</from>
    <owner>
      <organization>
      </organization>
    </owner>
    <owner>
      <organization>
        <name>IOP Publishing Ltd</name>
      </organization>
    </owner>
  </copyright>
  <relation type="hasManifestation">
    <bibitem>
      <title format="text/plain" script="Latn">News from the BIPM laboratories: 2014</title>
      <date type="ppub">
        <on>2015-02-01</on>
      </date>
      <medium>
        <carrier>print</carrier>
      </medium>
    </bibitem>
  </relation>
  <relation type="hasManifestation">
    <bibitem>
      <title format="text/plain" script="Latn">News from the BIPM laboratories: 2014</title>
      <date type="epub">
        <on>2015-01-30</on>
      </date>
      <medium>
        <carrier>online</carrier>
      </medium>
    </bibitem>
  </relation>
  <series>
    <title format="text/plain" language="en" script="Latn">Metrologia</title>
  </series>
  <extent>
    <locality type="volume">
      <referenceFrom>52</referenceFrom>
    </locality>
  </extent>
  <extent>
    <locality type="issue">
      <referenceFrom>1</referenceFrom>
    </locality>
  </extent>
  <extent>
    <locality type="page">
      <referenceFrom>155</referenceFrom>
      <referenceTo>162</referenceTo>
    </locality>
  </extent>
  <ext schema-version="v1.0.0">
    <doctype>article</doctype>
  </ext>
</bibdata>
````

@andrew2net could you please check?

**Comment by andrew2net** [comment]
@ronaldtse there is no any link in the source dataset
https://github.com/relaton/rawdata-bipm-metrologia/blob/2b00a1fdee81f4ead472a99794e5608a843fd360/data/2022-04-05T10_55_52_content/0026-1394/0026-1394_52/0026-1394_52_1/0026-1394_52_1_155/met_52_1_155.xml

There is an element `<self-uri content-type="pdf" xlink:href="met_52_1_155.pdf" xlink:type="simple"/>` but I didn't find a way to create a link form it.
The "BIPM Metrologia 52 1 155" on https://iopscience.iop.org has URL https://iopscience.iop.org/article/10.1088/0026-1394/52/1/155. It looks like we can build links form value, issue, and article numbers.

**Comment by ronaldtse** [comment]
@andrew2net we cannot do anything with the IOP website. The XML data provided by IOP is what we can work on. If the URL isn’t provided we have to report back to BIPM.

**Comment by ronaldtse** [comment]
@jmilesBIPM @MStock78120 is it possible for IOP to provide the URL for access to Metrologia articles in the XML data? Thanks!

**Comment by jmilesBIPM** [comment]
Before I contact IOP…
The URL to access the article would be https://doi.org/[DOI<https://doi.org/%5bDOI>]

Is the [DOI] not given in the XML data?

Thanks, Janet

**Comment by ronaldtse** [comment]
@jmilesBIPM the DOI is provided in the XML https://github.com/relaton/rawdata-bipm-metrologia/blob/2b00a1fdee81f4ead472a99794e5608a843fd360/data/2022-04-05T10_55_52_content/0026-1394/0026-1394_52/0026-1394_52_1/0026-1394_52_1_155/met_52_1_155.xml#L21

So should we use this DOI as the authoritative URL?

**Comment by ronaldtse** [comment]
@jmilesBIPM @MStock78120 I’ve added both of you to the organization that contains the Metrologia data since it’s private.

**Comment by andrew2net** [comment]
@ronaldtse I've tried https://doi.org/10.1088/0026-1394/52/1/155 and it's redirected to https://iopscience.iop.org/article/10.1088/0026-1394/52/1/155

**Comment by ronaldtse** [comment]
@andrew2net in this case let's generate the URL (in relaton-data-bipm) using the DOI.

**Comment by jmilesBIPM** [comment]
Great! Please use the “doi” version, which should of course be permanent.
(The place it redirects to can change with time, as the publisher updates its system…)

Do you confirm that there’s no need for me to contact IOP to change the XML files?

**Comment by jmilesBIPM** [comment]
In case I didn’t answer before…
Yes please! The DOI is the authoritative URL.

**Comment by ronaldtse** [comment]
Thank you @jmilesBIPM !

@andrew2net can you help create the URL from the DOI? Thanks.

**Comment by jmilesBIPM** [comment]
URL = https://doi.org/ + doi

e.g. for
<article-id pub-id-type="doi">10.1088/0026-1394/52/1/155</article-id>

URL = https://doi.org/10.1088/0026-1394/52/1/155

**Comment by andrew2net** [comment]
@ronaldtse what type should the new links have? `doi` or `src`?

**Comment by ronaldtse** [comment]
@andrew2net
* `doi` points to `10.1088/0026-1394/52/1/155`
* `src` points to `https://doi.org/10.1088/0026-1394/52/1/155`

**Comment by andrew2net** [comment]
> * `doi` points to `10.1088/0026-1394/52/1/155`

@ronaldtse Do I understand correctly? We must create a link with `10.1088/0026-1394/52/1/155` content, right? It doesn't look like a link.

**Comment by ronaldtse** [comment]
Yes. They can be the same links.
