### ISSUE TITLE
SI Brochure: Encode 1.08

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#234]
The changes from 1.07 (now) to 1.08 are:

<img width="1148" alt="Screenshot 2024-12-10 at 12 14 03 AM" src="https://github.com/user-attachments/assets/52578f47-63ab-4622-9a8c-b766e71a02d5">

**Comment by manuelfuenmayor** [comment]
These modifications are already covered in main branch version. @anermina could you confirm?

**Comment by ronaldtse** [comment]
OK, if we start from 1.08 or whatever version, it is also fine! As long as we have at least 2 versions so the BIPM (@MStock78120 @jmilesBIPM ) can follow on how to version new documents.

**Comment by anermina** [comment]
> These modifications are already covered in main branch version. @anermina could you confirm?

Yes, as confirmed in https://github.com/metanorma/bipm-si-brochure/pull/237#issuecomment-2532324251.
