### ISSUE TITLE
"No has been processed for..." several IDs

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/bipm-si-brochure#243]
Compilation of version 2.01 shows these messages:

```
Process si-brochure-fr.html: 17:33:36
No label has been processed for ID _0847aea8-14de-151d-dc4d-044cd659cb00_si-brochure-fr
No label has been processed for ID _ff18426a-210d-3671-67e6-0360e3d8125e_si-brochure-fr

Process si-brochure-en.html: 17:35:48
No label has been processed for ID _bde3f679-cd19-9c55-5479-8348ba9b8047_si-brochure-en
No label has been processed for ID _3451b6bf-403f-0b7e-bf6d-a9b8045a7445_si-brochure-en
No label has been processed for ID _bde3f679-cd19-9c55-5479-8348ba9b8047_si-brochure-en
No label has been processed for ID _3451b6bf-403f-0b7e-bf6d-a9b8045a7445_si-brochure-en
```

These IDs are seemingly not coming from anchors.

To reproduce the issue, run:
```
bundle exec metanorma collection sources/si-brochure/2.01/collection.yml
```

Related files: [brochure-2.01.zip](https://github.com/user-attachments/files/18103701/brochure-2.01.zip)

**Comment by opoudjis** [comment]
These are anchors in the boilerplate of the documents, which are meant not to be pointed to by anything, and the error report is only meant to be happening if something does point to them. Moreover, the errors are generated from the processing of the collection, not of the standalone documents.

**Comment by opoudjis** [comment]
No, the conditions for complaining are that I haven't explicitly set the warning flag to off when I assign the anchor. That's wrong, it should only be happening when autopopulating an xref. I'll change the default behaviour.
