### ISSUE TITLE
How to interpret collection metadata YAML / how are collections built?

### ISSUE THREAD

**Issue by strogonoff** [metanorma/bipm-si-brochure#258]
I want to start testing Firelight MN HTML renderer on these documents. I may have related questions, should I group them under one issue?

Right now the question I have is in the subject.

I see two collection.yml versions:

1. In the root where docref/fileref link to XML files that are not versioned in the repo https://github.com/metanorma/bipm-si-brochure/blob/main/collection.yml#L51-L52

2. Under individual standards, where it links to adoc files (and these ones do in fact exist): https://github.com/metanorma/bipm-si-brochure/blob/e1880fd573e3ff62fed0ddcf9e2c79d1a9ce0b27/sources/si-brochure/2.01/collection.yml#L48-L49

- In case of (1), I see that XML is generated during build. So, source YAML links to the future build artifact? 
- Does this mean collection YAML can link to either XML or AsciiDoc? It seems counter intuitive. How does it get resolved, generally speaking?

I am building per README, but it takes a while so I decided to ask in meantime.

**Comment by ronaldtse** [comment]
1. Is obsolete. We should delete it.
2. Yes, collection YAML supports both XML and AsciiDoc. Technically a collection is built from XML. i.e. when the file specified is AsciiDoc, Metanorma compiles it into XML first and passes it to the collection process.
