### ISSUE TITLE
Dash too large in unordered list items

### ISSUE THREAD

**Issue by manuel489** [metanorma/bipm-si-brochure#26]
*From https://github.com/metanorma/bipm-si-brochure/issues/24*

In second level of unordered list, the dashes look exaggerated compared with the original version.

*Generated*
![issue12-generated](https://user-images.githubusercontent.com/33627611/95933511-beacff80-0d9c-11eb-94be-3994fe578ae2.PNG)

*Original*
![issue12-original](https://user-images.githubusercontent.com/33627611/95933492-b3f26a80-0d9c-11eb-8ca9-b7b783c17da3.PNG)

**Comment by Intelligent2013** [comment]
Fixed:
![изображение](https://user-images.githubusercontent.com/5559926/96008956-c2965b80-0e48-11eb-8659-8db28a76b419.png)
