### ISSUE TITLE
(URGENT) PDFs missing titles

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#263]
The first is the generated collection PDF. You can see the tab missing a title. The second tab is an older English version which has a title.

It seems that even the single-language versions now have no title in PDF?

Collection:

<img width="1392" alt="Screenshot 2024-12-18 at 8 20 35 PM" src="https://github.com/user-attachments/assets/040befed-cbdd-4b74-a42e-bd921f347303" />
<img width="724" alt="Screenshot 2024-12-18 at 8 21 59 PM" src="https://github.com/user-attachments/assets/55472c56-dff2-475c-aeb5-31fcb493c89a" />

English single-language:

<img width="1268" alt="Screenshot 2024-12-18 at 8 22 16 PM" src="https://github.com/user-attachments/assets/657ef610-9317-446d-8627-33c932b13fae" />

**Comment by ronaldtse** [comment]
Older PDF from 2023-05:

<img width="724" alt="Screenshot 2024-12-18 at 8 22 50 PM" src="https://github.com/user-attachments/assets/fba4dc40-f9d4-4dc0-8ed8-97b1bf0e0346" />

**Comment by Intelligent2013** [comment]
New Presentation XML:
```xml
<bipm-standard xmlns="https://www.metanorma.org/ns/bipm" type="presentation" version="2.5.8" schema-version="v1.4.1" document_suffix="si-brochure-fr">
	<bibdata type="standard">
		<title language="en" format="text/plain" type="title-main">The International System of Units</title>
		<title language="en" format="text/plain" type="title-cover">The International System of Units (SI)</title>
		<title language="fr" format="text/plain" type="title-main">Le Système international d’unités</title>
		<title language="fr" format="text/plain" type="title-cover">Le Système international d’unités (SI)</title>
```

Old Presentation XML (May, 2023):
```xml
<bipm-standard xmlns="https://www.metanorma.org/ns/bipm" type="presentation" version="2.1.7">
	<bibdata type="standard">
		<title language="en" format="text/plain" type="main">The International System of Units</title>
		<title language="en" format="text/plain" type="cover">The International System of Units (SI)</title>
		<title language="fr" format="text/plain" type="main">Le Syst&#xE8;me international d&#x2019;unit&#xE9;s</title>
		<title language="fr" format="text/plain" type="cover">Le Syst&#xE8;me international d&#x2019;unit&#xE9;s (SI)</title>
```

I've update BIPM XSLT in https://github.com/metanorma/metanorma-bipm/issues/340, but looks like forget to update common.xsl for bookmarks. I'll fix it.

**Comment by Intelligent2013** [comment]
BIPM XSLT fixed:
![image](https://github.com/user-attachments/assets/58ca46d2-9046-407a-b95d-e35816437818)

**Comment by ronaldtse** [comment]
Confirm fixed. Thank you!

<img width="724" alt="Screenshot 2024-12-20 at 12 39 49 PM" src="https://github.com/user-attachments/assets/38984841-a028-4525-bf14-d3ffad888e6d" />
