### ISSUE TITLE
(URGENT) CIPM Declaration from CIPM meeting 90 shows mistaken `#` character in title

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#264]
As you can see there is an issue with a `#` inserted into the declaration's description here:
<img width="620" alt="Screenshot 2024-12-18 at 8 34 10 PM" src="https://github.com/user-attachments/assets/0bb20392-1742-4502-b27d-b13e64b1bc4a" />

The particular line originates from here:
* https://github.com/metanorma/bipm-data-outcomes/blob/eafca5cf19d3e19f63386d009e1a6a3cc0f40a35/cipm/meetings-fr/meeting-90.yml#L84

Then in relaton-data-bipm here:
* https://github.com/relaton/relaton-data-bipm/blob/9affdaf0d71dcc758666fe8a9ab9631f2b36f542/data/cipm/meeting/declaration/2001-00.yaml#L11

And it seems that it is actually a normal white space, so I don't know why it became a `#` (which typically indicates a missing glyph).

Ping @Intelligent2013 @andrew2net to fix this.

_Originally posted by @ronaldtse in https://github.com/metanorma/bipm-si-brochure/issues/223#issuecomment-2551221070_

**Comment by andrew2net** [comment]
@ronaldtse there is no "#" in relaton-data-bipm, right? So we need to check renderer.

**Comment by ronaldtse** [comment]
Yes it seems like a rendering problem. However can you help double check that the space in your data is a normal space? Thanks.

**Comment by andrew2net** [comment]
Just checked, they are normal 32 code space

**Comment by Intelligent2013** [comment]
In the PDF generated on my machine (Win10) there isn't `#`:
![image](https://github.com/user-attachments/assets/7d55dfe8-2127-4e57-b847-0dc5084c2bc1)

The font `Times New Roman Italic` is using for the text rendering:
![image](https://github.com/user-attachments/assets/f7f51394-f31b-468f-b154-17402e939abb)

The difference between your and my PDF means that some 'space' character is missing in your font instance (may be old). Some years we have the similar issues. If you need I can find, but in any case the new font should be used.

In the Presentation XML there are two spaces between `«`  and `unités` :
- space `0x202F` `Narrow No-Break Space`
- space `0x20`

![image](https://github.com/user-attachments/assets/f53bbe1e-5c59-4c63-bfbd-7a5a3fc73f4d)

![image](https://github.com/user-attachments/assets/bcc16939-c1b8-4a37-9dca-d6baf7b3b786)

My `Times New Roman` font instance contains `0x202F` character:
![image](https://github.com/user-attachments/assets/b8c77e73-0e7a-40c1-a348-9d7b4c9526c8)


In the semantic XML only one space:
![image](https://github.com/user-attachments/assets/2a9bc3e4-3939-4d9b-9690-bcf78a50d056)


In `meeting-90.yml` and `2001-00.yaml` only one space `0x20`:
![image](https://github.com/user-attachments/assets/4b1a0e38-9a3c-4961-9684-f9bde63653f4)

@opoudjis could you take a look at the reason why `0x202F` appears in the Presentation XML?

**Comment by andrew2net** [comment]
@ronaldtse maybe the problem is not in spaces. The "«" is not an UTF-8 symbol
```ruby
>  "« unités SI » et « unités du SI »"[0].ord
=> 171

> 171.chr
 => "\xAB"

> puts 171.chr
(irb):190:in `write': "\xAB" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
```

**Comment by opoudjis** [comment]
tested with `* [[[PV57_5, CIPM RES (1948, F)]]]`: I'm currently unable to fetch `* [[[PV69, CIPM Declaration (2001)]]]`. Confirmed that it is no longer inserting extra 202f:

````
<bibitem id="PV57_5" type="proceedings" schema-version="v1.2.9">
<formattedref>Comité International des Poids et Mesures (1948) 
<em>Adoption de « degré Celsius »</em> (Paris : Bureau international des poids et mesures) 
````

**Comment by manuelfuenmayor** [comment]
Fix confirmed:
![fix-ref](https://github.com/user-attachments/assets/ba2f4acf-5f99-4108-afa3-de131c850f9f)
