### ISSUE TITLE
CGPM Resolution 1889, 1901-01 and 1901-02 show "NO INFORMATION AVAILABLE"

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/bipm-si-brochure#270]
From recent build:
<img src="https://github.com/user-attachments/assets/3a2feade-4120-4fac-b153-c3c830d670a0" width="600" height="150">

This is how these references looked before, in a build from 2023:
<img src="https://github.com/user-attachments/assets/ef8027e3-d0bc-4aee-a56b-efecf2810e9c" width="600" height="350">

**Comment by ronaldtse** [comment]
This was fixed in my latest PR. If you pull it should work.

**Comment by manuelfuenmayor** [comment]
Yes, it is fixed. Closing.
