### ISSUE TITLE
PDF: Newline on "http://" DOI Link in Metrologia references

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/bipm-si-brochure#271]
Recent build on PDF:
![metrologia-http](https://github.com/user-attachments/assets/9a621cca-2417-4d93-8442-f5a5c3e5f4e3)

Metrologia references are not covering the whole margin of the page.

I suggest applying the newline before the "http://".

**Comment by Intelligent2013** [comment]
I can repeat the issue, but on another bibliographic items. My instance looks differently:
![image](https://github.com/user-attachments/assets/561e0384-675b-498d-bd77-e2c11add965d)

Ok, in any case, I'll try to add the zero width space after each `/` (and after last `/` in the sequence `//`) to break the line.

@manuelfuenmayor There are gaps in the numbering - `[92]`, `[94]`, `[96]` are missing. Is it ok?

**Comment by Intelligent2013** [comment]
Done:
![image](https://github.com/user-attachments/assets/e22f3137-e4eb-412a-9e7e-70cc7531f284)

**Comment by ronaldtse** [comment]
Thank you @Intelligent2013 !
