### ISSUE TITLE
BIPM brochure: break in list

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/bipm-si-brochure#38]
In https://github.com/metanorma/bipm-si-brochure/blob/master/sources/sections-a1-en/04-cipm-1946.adoc (and in fr part also) `[upperalpha]` list breaks into two:

```
[upperalpha]
.. Definitions of the mechanical units which enter the definitions of electric units:
...
[upperalpha]
.. Definitions of electric units. The Comité International des Poids et Mesures (CIPM) accepts the following propositions which define the theoretical value of the electric units:
```

In the resulted PDF it renders as:
![изображение](https://user-images.githubusercontent.com/5559926/97299609-421f2400-1866-11eb-8976-baaa26ac14e5.png)

But second should be `B` as in source PDF:

![изображение](https://user-images.githubusercontent.com/5559926/97299816-9c1fe980-1866-11eb-89d0-cdc757d8fd22.png)

**Comment by manuel489** [comment]
Thanks @Intelligent2013! Fxed in https://github.com/metanorma/bipm-si-brochure/commit/8c668403329d6444145cef00db194fa7cf387ff7. Closing.
