### ISSUE TITLE
French SI Brochure feedback from BIPM (full, and may need to fix English)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#39]
There are nearly 200 comments. I will post them in separate issues, linked from here. We will need to fix all of these issues and also fix the English counterpart if the issues exist there, too.

1. https://github.com/metanorma/bipm-si-brochure/issues/40
2. https://github.com/metanorma/bipm-si-brochure/issues/41
3. https://github.com/metanorma/bipm-si-brochure/issues/42
4. https://github.com/metanorma/bipm-si-brochure/issues/43
5. https://github.com/metanorma/bipm-si-brochure/issues/44

**Comment by Intelligent2013** [comment]
Resulted PDF (26 Oct):
[collection.presentation_fr.pdf](https://github.com/metanorma/bipm-si-brochure/files/5469207/collection.presentation_fr.pdf)

**Comment by opoudjis** [comment]
Updated PDF: https://github.com/metanorma/bipm-si-brochure/issues/24#issuecomment-723920534
