### ISSUE TITLE
BIPM SI brochure (French): review

### ISSUE THREAD

**Issue by anermina** [metanorma/bipm-si-brochure#47]
------------------------
Issues:
------------------------

1. Stem expressions are not generated at all. The first example is shown in the following captures, where alpha and gamma are missing.

Original:
![image](https://user-images.githubusercontent.com/55683568/98718074-3c5d2e80-238e-11eb-8891-6cd843810546.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/98718112-4848f080-238e-11eb-9692-5ecc09148c86.png)

Source ADOC:
`(Rayons x et stem:[gamma], électrons), Section II (Mesure des radionucléides), Section III (Mesures neutroniques), Section IV (Étalons d’énergie stem:[alpha])`

2. Cross-referencing should be fixed. I recall BIPM asked for adding the corresponding pages in cross-references, which is probably the reason why we have them in some places where they are not included in the original document. 

However, I can see the word `voir` is showing in more than one place, due to markup + automatic addition of page numbers. Moreover, BIPM used keyword `section` in some places, `chapitre` in the others, while sometimes they didn't use any keyword. So my question is whether we should keep `voir` and/or `section`/ `chapitre` in the markup, or we agreed with BIPM on some standard which will be applied in all cases. 

Original:
![image](https://user-images.githubusercontent.com/55683568/98723173-539e1b00-2392-11eb-8919-45ae4a19a446.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/98723229-6153a080-2392-11eb-9669-92927b2fe508.png)

From ADOC source:
`_obligatoires_ (voir <<chapter5>>).`

Original:
![image](https://user-images.githubusercontent.com/55683568/98724987-d32ce980-2394-11eb-9c72-edf25ae1205b.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/98725009-dc1dbb00-2394-11eb-98fa-547ab7e9233e.png)

From ADOC source:
`(voir <<cls-236>>)`

When the same ADOC syntax was used in the Introduction, page number was not included. I have already changed markup here because I thought it was wrong before seeing the other cross-references. Please let me know if I should revert the changes.

Original:
![image](https://user-images.githubusercontent.com/55683568/98721050-f6ee3080-2390-11eb-87ae-2642143269c2.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/98720790-e3db6080-2390-11eb-9ba0-bfd6e60d4441.png)

I changed markup here to:
`dans le texte «&nbsp;<<le_bipm_et_la_cdm>>&nbsp;» (page <<le_bipm_et_la_cdm,pagenumber%>>).`

Another example where page number is not included in neither original nor generated PDF is shown below.

Original:
![image](https://user-images.githubusercontent.com/55683568/98726109-5a2e9180-2396-11eb-9f38-a9a7a34e6c67.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/98726123-60bd0900-2396-11eb-9e28-2a00ea954a47.png)

From source ADOC:
`(voir <<scls541>> pour une explication de la notation utilisée ici).`

Moreover, should "voir" be italicized or not? Example from Appendix 1 of the original document is below. As far as I could see, "voir" was always italicized in Appendix 1, while that was not the rule in the rest of the brochure.

Original:
![image](https://user-images.githubusercontent.com/55683568/98739483-b7800e00-23a9-11eb-92bd-548a595e35f3.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/98739497-bfd84900-23a9-11eb-8d44-7e83d48a4f50.png)

3. Heading row of the ToC table in Appendix 1 is repeating at each page, probably because there was a blank line between it and the next table row. I removed that blank row. However, we still need word "page" to appear at the beginning of each new page.

Original:
![image](https://user-images.githubusercontent.com/55683568/98739264-56f0d100-23a9-11eb-9ba2-424dbbed8948.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/98739303-61ab6600-23a9-11eb-9171-5c35bb8b6e78.png)

Note: I've already changed capital P to small p in "page" and made it boldfaced.

------------------------
Questions/possible issues
------------------------

1. Should we have the first line in the generated ToC?

Original:
![image](https://user-images.githubusercontent.com/55683568/98718648-fc4a7b80-238e-11eb-9854-061854f0aada.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/98718556-e0df7080-238e-11eb-9b77-52886fc0e65b.png)

2. Do we need to show subsections for annexes in ToC? Do we need to add a dot after annex number?

Original:
![image](https://user-images.githubusercontent.com/55683568/98718875-4b90ac00-238f-11eb-8f98-c8f31abfc4e7.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/98718789-2ef47400-238f-11eb-9566-57285a87dd39.png)

3. This was probably agreed with BIPM, but in order to double-check: should this example be a part of the main text, or it should be shown on the right margin, as in the original (ignore the fact that math expressions are not shown in generated PDF):

Original:
![image](https://user-images.githubusercontent.com/55683568/98727872-eb9f0300-2398-11eb-8326-32f3ff21e279.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/98727834-df1aaa80-2398-11eb-889d-c4116dbadc7d.png)

4. Is there some reason why yellow-highlighted part was excluded?

Original:
![image](https://user-images.githubusercontent.com/55683568/98740183-f2367600-23aa-11eb-996e-b2ffb1a07d28.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/98740212-fcf10b00-23aa-11eb-9495-3e20de721d90.png)

5. Titles are always boldfaced in our case. However, BIPM uses some kind of referencing in the titles, which applies the style which is generally used for papers of that type. I'm just noticing this as a difference, but don't know if that is a problem for BIPM team.

Original:
![image](https://user-images.githubusercontent.com/55683568/98741419-e64bb380-23ac-11eb-9a57-7b391c6faa88.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/98741367-cb793f00-23ac-11eb-9e9a-d29371716bdd.png)

6. Are we supposed to be using Greek letters for second level of items list?

Original:
![image](https://user-images.githubusercontent.com/55683568/98741709-6bcf6380-23ad-11eb-87df-b4f7809593fe.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/98741683-61ad6500-23ad-11eb-8915-2431676dcd69.png)

Note: Markup fixes are applied in https://github.com/metanorma/bipm-si-brochure/pull/48.

**Comment by manuel489** [comment]
> Stem expressions are not generated at all. The first example is shown in the following captures, where alpha and gamma are missing.

Confirmed. I'm getting this result on generated PDF.

> Moreover, should "voir" be italicized or not? Example from Appendix 1 of the original document is below. As far as I could see, "voir" was always italicized in Appendix 1, while that was not the rule in the rest of the brochure.

I agree, in my view, it should be italicized.

> This was probably agreed with BIPM, but in order to double-check: should this example be a part of the main text, or it should be shown on the right margin, as in the original (ignore the fact that math expressions are not shown in generated PDF):

This happens because the text is enclosed in  an example block. I believe we would have to change it to a note block in order to place it at the right margin. But we need confirmation for that. @ronaldtse?

> Are we supposed to be using Greek letters for second level of items list?

In my view, this is clearly a bug.

**Comment by Intelligent2013** [comment]
In Acrobat Reader there is an error after a few seconds after I opened PDF:
![изображение](https://user-images.githubusercontent.com/5559926/98781989-4a4f9580-2408-11eb-8c98-a842a12844bc.png)

PDF is corrupted. @opoudjis  could you attach a log of mn2pdf processing, please?

**Comment by ronaldtse** [comment]
Ping @opoudjis

**Comment by opoudjis** [comment]
OK:

The Stem rendering issue has been resolved, although I'm not happy with how we ended up resolving it—by having to upgrade Java. We are including STIX in fontist, and that may be a smoother resolution of this issue. I have regenerated the PDF, and @Intelligent2013 confirms he is not getting the errors in opening the PDF.

I am attaching the latest compilation of the PDF.

[collection.pdf](https://github.com/metanorma/bipm-si-brochure/files/5553985/collection.pdf)

**Comment by opoudjis** [comment]
"2." The intention is that chapître refers to clauses (e.g. Chapître 5), and section to subclauses (e.g. section 2.3.6). If that isn't happening, that's a bug on my side.

**Comment by anermina** [comment]
"1" is solved.

"2" can be split into several issues and questions:

2.1 Cross-referencing keywords.
`chapître` should refer to clauses, and `section` to subclauses. (I confirm it is currently not happening.)

2.2 Adding page numbers in cross-references.
In which cases should the page number be added as a part of the cross-reference? I didn't manage to find a rule in neither original nor generated PDF.

Note: BIPM requested adding page number for "Introduction" section, where it wasn't generated and where I don't see how it can be automatically generated to produce the desired output (due to usage of `« »` for the title). So I changed markup there to:
`dans le texte «&nbsp;<<le_bipm_et_la_cdm>>&nbsp;» (page <<le_bipm_et_la_cdm,pagenumber%>>).`

2.3 Source of the word `voir`.
Should the word `voir` before the cross-reference be added automatically, or via markup?

2.4 Duplication of the word `voir` when page numbers are added.
In case page number is added, we currently have repetition of the word `voir`, as in the following example:
`voir 2.3.6, voir p. 30`

2.5 Italicizing the word `voir`.
Should it be italicized? As far as I could see, `voir` was always italicized in Appendix 1 of the original document, while that was not the rule in the rest of the brochure.

"3" Conclusion remains the same - after changing .adoc source, we lost the word `page` at the beginning of each new page. For some reason, the first row is not boldfaced now.

The rest of the initially written issues remain the same.

**Comment by ronaldtse** [comment]
> The Stem rendering issue has been resolved, although I'm not happy with how we ended up resolving it—by having to upgrade Java

No one uses Java 8 anymore...

**Comment by opoudjis** [comment]
> No one uses Java 8 anymore...

Given your aspirations to have all this running in an app, this is still your problem. People who are not developers in Java have the default OS version of Java lying around, and OS versions of programming languages are always antiquated...

**Comment by ronaldtse** [comment]
In fact, we already stopped supporting Mojave a while ago as the single-binary version doesn't support it. Keeping one's computer up to date using system utilities is the responsibility of the user. As application developers we are not expected to keep the execution runtimes updated.

**Comment by opoudjis** [comment]
> 2.1 Cross-referencing keywords.
> chapître should refer to clauses, and section to subclauses. (I confirm it is currently not happening.)

Was fixed in #40, but I had a typo: fixed now.

**Comment by opoudjis** [comment]
And as for your Issues, separately numbered:

> 1. Should we have the first line in the generated ToC?

No opinion.

> 2. Do we need to show subsections for annexes in ToC? 

I believe @ronaldtse has already extracted the concession from BIPM that we don't: this would have been an idiosyncratic limit to the ToC.

> 2. Do we need to add a dot after annex number?

Yes, and that needs to be done inline in PDF.

> 3. This was probably agreed with BIPM, but in order to double-check: should this example be a part of the main text, or it should be shown on the right margin, as in the original 

No opinion, I defer to @Intelligent2013 

> 4. Is there some reason why yellow-highlighted part was excluded?

The text was there in sections-a1-fr/a1-decisions.adoc, which is presumably the older document that was chopped up into the various constituent resolutions. You'd have to ask @manuel489, but "see below" tends to be bad news for auto-formatted documents in general, because it's vague, and you don't know where below the referent is going to end up. 

> 5. Titles are always boldfaced in our case. However, BIPM uses some kind of referencing in the titles, which applies the style which is generally used for papers of that type. I'm just noticing this as a difference, but don't know if that is a problem for BIPM team.

It will be unpleasant to fix this, won't do so unless they ask for it.

> 6. Are we supposed to be using Greek letters for second level of items list?

Specific to PDF, HTML has normal a).

**Comment by opoudjis** [comment]
Any remaining issues in my opinion do not involve me, so I am putting this issue on my on-hold list.

**Comment by Intelligent2013** [comment]
> 2.2 Adding page numbers in cross-references.
> Note: BIPM requested adding page number for "Introduction" section, where it wasn't generated and where I don't see how it can be automatically generated to produce the desired output (due to usage of « » for the title). So I changed markup there to:
dans le texte «&nbsp;<<le_bipm_et_la_cdm>>&nbsp;» (page <<le_bipm_et_la_cdm,pagenumber%>>).

It should be workable solution. The similar markup I've processed yet for ToC in Appendix:
```xml
<xref target="cgpm24th2011r1" pagenumber="true">Appendix 1.38.1</xref>
```

But, because page numbers in ToC are bold, then please add bold markup into adoc for Appendix 1 Toc (00-toc.adoc) for both languages.

> 2.5 Italicizing the word voir.
> Should it be italicized? As far as I could see, voir was always italicized in Appendix 1 of the original document, while that was not the rule in the rest of the brochure.

I've fixed xslt for:
- if voir/see in main text - it isn't italized,
- if voir/see in side notes - it is italized.


> 1. Should we have the first line in the generated ToC?

I think no, because this section before ToC, removed in xslt.

> 2. Do we need to add a dot after annex number?

Yes. xslt fixed.


> 3. This was probably agreed with BIPM, but in order to double-check: should this example be a part of the main text, or it should be shown on the right margin, as in the original

In the original PDF there isn't common approach for examples.
Page 143:
![изображение](https://user-images.githubusercontent.com/5559926/100108116-7f81cc00-2e7b-11eb-990a-3f5e13621a6d.png)

Page 150:
![изображение](https://user-images.githubusercontent.com/5559926/100108218-988a7d00-2e7b-11eb-901a-f5b3c5a74e3e.png)

There are a few solutions:
- markup second example as note, then it'll show on the right margin (changes in adoc)
- displays both examples in main text (no need changes)
- display both examples on the right margin (xslt need to change)
- markup both examples as `example`, but for second add some indication in markup (for show this example on the right margin) (rb need to change).

**Comment by anermina** [comment]
> But you are right that 2.4 requires an exception to be made. With some feeling of revulsion at the kludginess of it all, I am going to introduce markup in xrefs, to signal to the PDF that any voir/see is to be suppressed.

In accordance to https://github.com/metanorma/metanorma-bipm/issues/75#issue-749599079, I added `%nosee` to the cross-references where duplication of "voir/see" could be seen in the latest generated PDF.

> But, because page numbers in ToC are bold, then please add bold markup into adoc for Appendix 1 Toc (00-toc.adoc) for both languages.

Done.

> In the original PDF there isn't common approach for examples.

Lets leave these examples as a part of the main text then. In case BIPM says they would prefer them to be shown on the right margin, I'll mark the second example as a note.

> Is there some reason why yellow-highlighted part was excluded?
> The text was there in sections-a1-fr/a1-decisions.adoc, which is presumably the older document that was chopped up into the various constituent resolutions. You'd have to ask @manuel489, but "see below" tends to be bad news for auto-formatted documents in general, because it's vague, and you don't know where below the referent is going to end up.

@manuel489, could you please check? It seems to me this part of the text was intentionally modified, but it would be good to have a confirmation.

**Comment by manuel489** [comment]
> @manuel489, could you please check? It seems to me this part of the text was intentionally modified, but it would be good to have a confirmation.

@anermina, yes, I intentionally removed that piece of text for the same reason that @opoudjis provides [above](https://github.com/metanorma/bipm-si-brochure/issues/47#issuecomment-732870302).  Basically, "voir ci-dessous" translates "see below", and it's kind of a vague reference. And, at that time, I wasn't sure if such referenced notes were going to be placed in such a way that they were actually "below" (e.g. what if a page-break happens just after the reference calling?). BUT, looking at the generated PDF, they seem to be in the correct position. So I guess we can rollback that change after all?

**Comment by manuel489** [comment]
I have put back the text.

**Comment by anermina** [comment]
Corrections are made. Closing.
