### ISSUE TITLE
Formatting of values (as italics) vs units (as upright)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#54]
From BIPM:

> The largest number of comments is related to the use if italic or upright font. (in #50 #51 #52 #53)
> In general, symbols for quantities are printed in italics, whereas symbols for units are in upright font.

Is it possible to textually encode some text in `stem:[_v_ "ms"^{-2}]` blocks so that the `_v_` bit becomes italic?

**Comment by opoudjis** [comment]
This is what we hoped to have the Ascii-based units formatting language address, but I guess we're not going to wait for that.

Your requirement is backwards: it is the upright, not the italics, which is the exception. I doubt this can be done directly at all, and what will be necessary is some ad hoc postprocessing, where formatting is passed through in the AsciiMath parse, and then processed before moving on to MathML; something like `stem:[5 !m^{-2}]`, where we agree that `!` makes the following character upright.

Proccessing Asciidoctor markup is a non-starter. Treating units as text in AsciiMath is also a non-starter. That is not how you're going to get the markup you want.

Will need to experiment with this.

**Comment by opoudjis** [comment]
Recall: by default in MathML, two-character variables are upright, single-character variables are italic. 

Asciimath gem decomposes two-character variables into single-character variables. So everything turns into italics. The real solution to that is going to have to be true units markup. But before we get there:

Asciimath applies font shifts to its arguments: so

`stem:[v bb(ms)^{-2}]`

renders as:

````
<math xmlns="http://www.w3.org/1998/Math/MathML">
<mi>v</mi>
<msup><mrow>
<mstyle mathvariant="bold"><mrow><mi>m</mi><mi>s</mi></mrow></mstyle>
</mrow><mrow><mrow><mo>−</mo><mn>2</mn></mrow></mrow></msup>
</math>
````

That won't be the desired `<mi  mathvariant="bold">m</mi>`, but if we want proper semantic markup, we should be using a real units markup scheme anyway.

So we could address this for now, at least for rendering, by changing the markup to `stem:[v rm(ms)^{-2}]`. The problem with that is, `rm` is not supported by most Asciimath implementations. Am requesting it to be implemented in Asciimath gem.

**Comment by anermina** [comment]
> So we could address this for now, at least for rendering, by changing the markup to `stem:[v rm(ms)^{-2}]`. The problem with that is, `rm` is not supported by most Asciimath implementations. Am requesting it to be implemented in Asciimath gem.

I applied `rm(...)` syntax to all units in `stem` expressions of BIPM SI Brochure EN/FR (#56 ).

**Comment by opoudjis** [comment]
@Intelligent2013, unassigning you, there is nothing for you to do.

There is a task to do units in UnitsML properly: https://github.com/metanorma/metanorma-bipm/issues/3 . This interim solution is working, so closing ticket.
