### ISSUE TITLE
BIPM SI brochure (English): review

### ISSUE THREAD

**Issue by anermina** [metanorma/bipm-si-brochure#57]
1. Frontpage: Capital letters are used in the original EN document. 
Original French document uses the same format as generated (EN and FR), so this is probably an inconsistency in BIPM, but "Bureau International des Poids et Mesures" seems right to me for both versions. @ronaldtse ?

Original:
![image](https://user-images.githubusercontent.com/55683568/99902072-66322180-2cbb-11eb-9bf6-3030a3777b1d.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/99902079-6e8a5c80-2cbb-11eb-81bd-6153b84cfd5e.png)

2. Cross-reference to table is written with capital T in the original EN document.
French uses small letters.

Original:
![image](https://user-images.githubusercontent.com/55683568/99902482-74357180-2cbe-11eb-85c4-badf155e1f99.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/99902490-7d264300-2cbe-11eb-84f9-6139f157e1ea.png)

3. Decimal dots should be used in EN version instead of decimal commas which are used in FR version.

4. We need the word "page" at the beginning of each new page for ToC of Appendix 1. (Reported in #47 as well.)

Original:
![image](https://user-images.githubusercontent.com/55683568/99903147-d55f4400-2cc2-11eb-8f36-69cb50c33d58.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/99903140-cd070900-2cc2-11eb-99b0-94ea08e7bb9e.png)

5. Both levels of items list are numbered with Greek letters in the generated PDF. (Similar reported in #47.)

Original:
![image](https://user-images.githubusercontent.com/55683568/99903184-1bb4a300-2cc3-11eb-8e7e-6b437956047f.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/99903180-15262b80-2cc3-11eb-9a6d-b2d66278513b.png)

6. Zeros are truncated when they shouldn't be.

Original:
![image](https://user-images.githubusercontent.com/55683568/99903330-fc6a4580-2cc3-11eb-94ff-c2fc3de35c7b.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/99903325-f4aaa100-2cc3-11eb-91cb-b1d1bfd540c1.png)

7. Second note in 24th CGPM is appearing at the beginning of the text, and it should be lower.

Original:
![image](https://user-images.githubusercontent.com/55683568/99903914-c62ec500-2cc7-11eb-8679-ec8ec66573ec.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/99903911-be6f2080-2cc7-11eb-837c-dfe4b372310d.png)

8.  The same comments regarding ToC as in #47 apply here as well.
> Should we have the first line in the generated ToC?
> Do we need to show subsections for annexes in ToC? Do we need to add a dot after annex number? -> (Appendices instead of Annexes in this case.)
 
9. The same comments regarding cross-referencing sections with/without corresponding page numbers as in #47 apply here as well.
> In which cases should the page number be added as a part of the cross-reference?
> Should the word `see` before the cross-reference be added automatically, or via markup?
> In case page number is added, we currently have repetition of the word `see`, as in the following example: `see 2.3.6, see p. 30`.

**Comment by Intelligent2013** [comment]
> 4. We need the word "page" at the beginning of each new page for ToC of Appendix 1. (Reported in #47 as well.)

To repeat 'page' on each page, please move 'page' into table header.

> 5. Both levels of items list are numbered with Greek letters in the generated PDF. (Similar reported in #47.)

Very strange rendering, I can't figure out the reason of it. Could you put a link to reviewed pdf, please?

> 7. Second note in 24th CGPM is appearing at the beginning of the text, and it should be lower.

This issue was discussed earlier, and current solution is not ideally, but accepted. If we move it lower, then we'll get a vertical spaces/gaps sometimes.

**Comment by opoudjis** [comment]
> 2. Cross-reference to table is written with capital T in the original EN document. French uses small letters.

I'd assumed consistency. Forcing English labels to be uppercase. (In fact, I'm removing the YAML English localisation, so they can inherit the default capitalised labels from isodoc.)

**Comment by opoudjis** [comment]
> 3. Decimal dots should be used in EN version instead of decimal commas which are used in FR version.

Has been fixed.

> 6. Zeros are truncated when they shouldn't be.

Has been fixed.

**Comment by anermina** [comment]
> To repeat 'page' on each page, please move 'page' into table header.

This requested a minor modification of the initial table appearence, but the difference is not significant, so I think it won't be a problem. Done.

> Very strange rendering, I can't figure out the reason of it. Could you put a link to reviewed pdf, please?

@Intelligent2013 I used PDF attached in https://github.com/metanorma/bipm-si-brochure/issues/47#issuecomment-728957663.

**Comment by opoudjis** [comment]
> 1. Frontpage: Capital letters are used in the original EN document.
> Original French document uses the same format as generated (EN and FR), so this is probably an inconsistency in BIPM, but "Bureau International des Poids et Mesures" seems right to me for both versions.

The English and French brochures capitalise the French title of the organisation differently. They are using French and English capitalisation conventions respectively on the French title.

I should be able to deal with this, by making _Bureau International des Poids et Mesures_ the English-language title of the organisation (seriously!) and _Bureau International des poids et mesures_ the French title.

... Mind blown.

**Comment by opoudjis** [comment]
Can this issue be closed?

**Comment by anermina** [comment]
Yes, closing.
