### ISSUE TITLE
BIPM: Indexing for SI Brochure

### ISSUE THREAD

**Issue by anermina** [metanorma/bipm-si-brochure#60]
This ticket addresses remaining issues in BIPM SI brochure. When enhancements are implemented, we'll check outputs for BIPM files.

| Issue | Ticket which addresses the issue
| -- | --
| Table 6: increase width of first two columns so that there are less linebreaks | metanorma/metanorma-standoc#251
| The index is missing | metanorma/metanorma-bipm#67

**Comment by opoudjis** [comment]
https://github.com/metanorma/metanorma-standoc/issues/251 implemented, so you should be able to review now

Index: I will complete implementation mid-week, expect to get this some time next week.

**Comment by anermina** [comment]
Table 6 looks good to me now.

**Comment by ronaldtse** [comment]
Index functionality has been completed according to @opoudjis . This is the only remaining issue for the SI Brochure.

@metanorma/editors can you help create the index? Thanks!

**Comment by ronaldtse** [comment]
@manuel489 and @anermina has completed the index in #76.

@opoudjis @Intelligent2013 this is ready to go for indexing. Can we have a render of the index for checking? Thanks!

**Comment by opoudjis** [comment]
Have rendered, will reindex when finalised.

**Comment by opoudjis** [comment]
This task is done.
