### ISSUE TITLE
BIPM: Remaining issues

### ISSUE THREAD

**Issue by anermina** [metanorma/bipm-si-brochure#62]
MEP-3 (guide-ccl-GD-MeP-3-en.adoc)
---------------------------
1.  I added `nosee%` in the meanwhile, but there is no need for adding page number in this cross-reference, since the figure is right below the text, on the same page. The same applies to several other figures in this document and the table below.

![image](https://user-images.githubusercontent.com/55683568/102276885-c5382e80-3f27-11eb-86e9-3e58d5e7a6c0.png)

![image](https://user-images.githubusercontent.com/55683568/102278334-ed289180-3f29-11eb-853c-a0c8d3baf839.png)

MEP candela rapport (mep-candela-rapport.adoc)
---------------------------
1.  In case section is marked with `[heading=terms and definitions]` attribute, default intro text is used. However, here we have some non-generic intro in the original document. It can also be seen that the subsections for terms are not generated as usually (they don't differentiate from the rest of the text).
Should we just remove this attribute? 

Original:
![image](https://user-images.githubusercontent.com/55683568/102282267-9ecac100-3f30-11eb-8be7-e6e1cbba6764.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/102282363-ca4dab80-3f30-11eb-8189-fda56e1aee44.png)

2. Colon and blank space are missing after "Note x to entry".

![image](https://user-images.githubusercontent.com/55683568/102282535-0b45c000-3f31-11eb-9076-040162d65d12.png)

BIPM brochure (FR)
---------------------------
1. There is an extra page with "Références" title in header. @Intelligent2013 could you please check?

**Comment by opoudjis** [comment]
BIPM brochure (FR)
---------------------------
> There is an extra page with "Références" title in header. @Intelligent2013 could you please check?

That was because the anchor reference to the English example was not formatted correctly, as an anchor, and therefore did not end up hidden. I have corrected the markup, so this should render correctly next time.

**Comment by Intelligent2013** [comment]
### > Colon and blank space are missing after "Note x to entry".

Fixed:
![изображение](https://user-images.githubusercontent.com/5559926/102357788-c321ae80-3fbf-11eb-949a-ea8b2468257d.png)

**Comment by opoudjis** [comment]
MEP-3 (guide-ccl-GD-MeP-3-en.adoc)
---------------------------
> 1.  I added `nosee%` in the meanwhile, but there is no need for adding page number in this cross-reference, since the figure is right below the text, on the same page. The same applies to several other figures in this document and the table below.

To my disgust, I anticipate that I am going to have to address this with yet another optional attribute, telling the PDF not to insert a page reference at all, instead of merely dropping the "see"...

**Comment by opoudjis** [comment]
Yes, adding nopage% to xref markup. @anermina You will end up replacing nosee% with nopage%.

@Intelligent2013 The attribute `xref/@nopage` is a counterpart to `xref/@nosee`. Where `@nosee` indicates that the word for "see" is not added in PDF rendering, just the page number—`@nopage` indicates that neither is to be added.

**Comment by anermina** [comment]
Thank you. `nopage%` added for `guide-ccl-GD-MeP-3-en.adoc`.

**Comment by opoudjis** [comment]
@anermina Can this issue be closed?

**Comment by anermina** [comment]
@opoudjis Can you please check this part?

> ## MEP candela rapport (mep-candela-rapport.adoc)
> 1. In case section is marked with `[heading=terms and definitions]` attribute, default intro text is used. However, here we have some non-generic intro in the original document. It can also be seen that the subsections for terms are not generated as usually (they don't differentiate from the rest of the text).
>    Should we just remove this attribute?
> 
> Original:
> ![image](https://user-images.githubusercontent.com/55683568/102282267-9ecac100-3f30-11eb-8be7-e6e1cbba6764.png)
> 
> Generated:
> ![image](https://user-images.githubusercontent.com/55683568/102282363-ca4dab80-3f30-11eb-8189-fda56e1aee44.png)

**Comment by opoudjis** [comment]
Oddly enough, Nermina, that issue has just been addressed: the default terms boilerpalte ("for the purposes of this document..." can be overriden by a subclause tagged as `[.boilerplate]`, which will not be displayed with a clause header.

So, use:

````
[heading=terms and definitions]
== Photometric quantities

[.boilerplate]
=== {blank}
The photometric quantities generally used are....
````

There is also the abillity to just type text after the Terms & Definitions, and have it appended after the default boilerplate, and I can define the default boilerplate for BIPM to be empty. But that should work immediately.

**Comment by anermina** [comment]
Corrected in https://github.com/metanorma/bipm-si-brochure/pull/73. Closing.
