### ISSUE TITLE
BIPM: Remaining issues (continues #62)

### ISSUE THREAD

**Issue by anermina** [metanorma/bipm-si-brochure#63]
MEP Candela Rapport (mep-candela-rapport.adoc)
----------------------

1. `bar` is barely noticeable, especially when it is used on some capital letter in the `stem` expression, at least in Acrobat Reader in Widows OS.

Generated (200%):
![image](https://user-images.githubusercontent.com/55683568/102373952-0cbec900-3fc1-11eb-8bcf-32da2ff670a4.png)
![image](https://user-images.githubusercontent.com/55683568/102377556-1fd39800-3fc5-11eb-8ba5-4d3925c345cc.png)

Original (200%):
![image](https://user-images.githubusercontent.com/55683568/102374126-42fc4880-3fc1-11eb-94b2-da1073cad596.png)

2. Too small space reserved for the terms in definition lists causes overlapping with definition.

![image](https://user-images.githubusercontent.com/55683568/102374996-447a4080-3fc2-11eb-986e-292e19390c40.png)

3. Following note is not generated in chapter 5.1:

`NOTE: The descriptor "`photopic`" is used only when quantities other than photopic are reported or discussed in the same document and there is a possibility of confusion.`

Recommended values (https://github.com/metanorma/bipm-si-brochure/tree/bipm_corrections/sources/rec-values repo)
---------------------
1. Too many blank pages are generated at the beginning of the documents.

**Comment by Intelligent2013** [comment]
#### > 1. `bar` is barely noticeable, especially when it is used on some capital letter in the `stem` expression, at least in Acrobat Reader in Widows OS.

It seems jEuclid issue.

In case of xml (example from jEuclid package):
```xml
<math> 
   <mrow> 
    <mover accent="true"> 
     <mrow> 
      <mi> x </mi> 
      <mo> + </mo> 
      <mi> y </mi> 
      <mo> + </mo> 
      <mi> z </mi> 
     </mrow> 
     <mo>¯</mo> 
    </mover> 
   </mrow> 
</math>
```
it displays as:
![изображение](https://user-images.githubusercontent.com/5559926/102485620-eb211880-4078-11eb-8a87-0c2e81670f19.png)

In we add `sub`:
```xml
<math> 
  <msub>
   <mrow> 
    <mover accent="true"> 
     <mrow> 
      <mi> x </mi> 
      <mo> + </mo> 
      <mi> y </mi> 
      <mo> + </mo> 
      <mi> z </mi> 
     </mrow> 
     <mo>¯</mo> 
    </mover> 
   </mrow> 
   <mrow>
   <mtext>v</mtext>
  </mrow>
 </msub>
</math>
```

it shows as:
![изображение](https://user-images.githubusercontent.com/5559926/102485804-27547900-4079-11eb-9798-d905b03b7de2.png)

MathJax shows ok:
![изображение](https://user-images.githubusercontent.com/5559926/102486142-a6e24800-4079-11eb-93bc-f953785991ff.png)


If we remove subscript from source xml:
```
<math xmlns="http://www.w3.org/1998/Math/MathML">
	<mrow>
		<mover accent="true">
			<mrow>
				<mstyle mathvariant="italic">
					<mi>I</mi>
				</mstyle>
			</mrow>
			<mo>¯</mo>
		</mover>
	</mrow>
</math>
```
then bar shows ok:
![изображение](https://user-images.githubusercontent.com/5559926/102484687-acd72980-4077-11eb-98cb-d9c1ed9913d7.png)

I've asked here https://stackoverflow.com/questions/65340714/jeuclid-how-to-show-bar-in-formule-with-subscript.

**Comment by Intelligent2013** [comment]
#### > 2. Too small space reserved for the terms in definition lists causes overlapping with definition.
Fixed:
![изображение](https://user-images.githubusercontent.com/5559926/102496128-0fd0bc80-4088-11eb-9d61-cdb0334555f9.png)

**Comment by Intelligent2013** [comment]
#### > 3. Following note is not generated in chapter 5.1

Fixed:
![изображение](https://user-images.githubusercontent.com/5559926/102546601-f308a900-40c8-11eb-9b0e-25f8236a58ad.png)

**Comment by Intelligent2013** [comment]
### > Recommended values (https://github.com/metanorma/bipm-si-brochure/tree/bipm_corrections/sources/rec-values repo)

#### 1. Too many blank pages are generated at the beginning of the documents.

Fixed.

Example resulted PDF: [115In_1267THz.presentation.pdf](https://github.com/metanorma/bipm-si-brochure/files/5712388/115In_1267THz.presentation.pdf)

**Comment by Intelligent2013** [comment]
#### >  1. bar is barely noticeable, especially when it is used on some capital letter in the stem expression, at least in Acrobat Reader in Widows OS.

I've found a workaround solution. First `mrow` in `msub` should be enclosed in `mstyle`:
```xml
<math xmlns="http://www.w3.org/1998/Math/MathML">
 <msub>
  <mstyle>
   <mrow>
    <mover accent="true">
     <mrow>
      <mi>x</mi>
     </mrow>
     <mo>¯</mo>
    </mover>
   </mrow>
  </mstyle>
  <mrow>
   <mn>10</mn>
  </mrow>
 </msub>
 <mfenced open="(" close=")">
  <mrow>
   <mstyle mathvariant="italic">
    <mi>λ</mi>
   </mstyle>
  </mrow>
 </mfenced>
</math>
```

![изображение](https://user-images.githubusercontent.com/5559926/103102672-25b52300-462e-11eb-896d-590bd076ac50.png)

![изображение](https://user-images.githubusercontent.com/5559926/103102734-690f9180-462e-11eb-8447-dfea1a558fbf.png)

**Comment by Intelligent2013** [comment]
I'll modify xslt to do it on-fly.

**Comment by Intelligent2013** [comment]
#### > 1. bar is barely noticeable, especially when it is used on some capital letter in the stem expression, at least in Acrobat Reader in Widows OS.

Issue fixed.
Resulted PDF (please note that xml isn't latest): [mep-candela-rapport.presentation.pdf](https://github.com/metanorma/bipm-si-brochure/files/5741999/mep-candela-rapport.presentation.pdf)

**Comment by anermina** [comment]
Thanks @Intelligent2013 ! Closing this issue.
