### ISSUE TITLE
BIPM feedback: French: Page 61, last side note: wrong reference, should be Page 61 (the same page)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#67]
Original:
<img width="953" alt="Screen Shot 2021-01-02 at 12 01 58 AM" src="https://user-images.githubusercontent.com/11865/103442082-f33ea200-4c8d-11eb-94df-0e50d9140c12.png">

Generated:
<img width="881" alt="Screen Shot 2021-01-02 at 12 02 02 AM" src="https://user-images.githubusercontent.com/11865/103442083-f76abf80-4c8d-11eb-9f55-59af9e969bf4.png">

The generated version is missing the page number.

**Comment by ronaldtse** [comment]
The current encoding is:

```adoc
. de donner une définition du Temps atomique international; footnote:[
La définition du TAI a été donnée par le CCDS en 1970 (maintenant renommé CCTF), 
_voir_ <<ccds-tai-definition_s2,Recommandation S 2>>]
```

I believe the correct output would be "_voir_ Recommandation S 2, p. 61".

**Comment by Intelligent2013** [comment]
Source xml:
```xml
<p id="_cb88753a-61a8-4add-861e-4e6639adcd40">La définition du TAI a été donnée par le CCDS en 1970 (maintenant renommé CCTF), <em>voir</em>
	<xref target="ccds-tai-definition_s2">Recommandation S 2</xref>
</p>
```

Xslt inserts page number in these cases:
- if attribute `pagenumber='true'` - displays just page number (without `p.`) and without text content of xref,
- if next char after xref is `)`  and there aren't `nopage=true` and `nosee=true` attributes - displays `text content of xref` + `, see/voir p. N`.


So as there isn't `)`  after xref in this case, then to display `voir Recommandation S 2, p. 61`:
- markup as `_voir_ Recommandation S 2, p. <<ccds-tai-definition_s2,pagenumber%>>`
or if you need as in original doc `voir p. 61`:
- markup as  `_voir_  p. <<ccds-tai-definition_s2,pagenumber%>>

**Comment by ronaldtse** [comment]
Now marked up as:
```adoc
footnote:[La définition du TAI a été donnée par le CCDS en 1970
(maintenant renommé CCTF), _voir_ Recommandation S 2 (<<ccds-tai-definition_s2>>)]
```
