### ISSUE TITLE
BIPM Feedback: French page 36, sectio 5.4.2, last side note: spaces not correct, compare with original

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#69]
This is to do with math formula variables spacing inside side notes. Notice in the sidebar the variables seem to be spaced out ("justified" spacing?).

i.e. these seem to be spaced out
- "U_max"
- "V_max"
- "W(Cu)"

Original:

<img width="939" alt="Screen Shot 2021-01-02 at 1 29 00 AM" src="https://user-images.githubusercontent.com/11865/103443398-e58f1980-4c99-11eb-852b-50922ba95449.png">

Generated:

<img width="946" alt="Screen Shot 2021-01-02 at 1 28 44 AM" src="https://user-images.githubusercontent.com/11865/103443389-ddcf7500-4c99-11eb-8570-b3bc75a7d8b8.png">

Originally reported in #41 .

**Comment by Intelligent2013** [comment]
I've just rendered PDF in my environment:
![изображение](https://user-images.githubusercontent.com/5559926/103459045-588da400-4d1d-11eb-9021-ca97ba8b719b.png)

`max` after `U` and `V` looks ok, but `W(Cu)` looks with spaces.

jEuclid doesn't use justification.

Original source mathml:
```
<math xmlns="http://www.w3.org/1998/Math/MathML">
	<mi>w</mi>
	<mfenced open="(" close=")">
		<mrow>
			<mtext>Cu</mtext>
		</mrow>
	</mfenced>
	<mo>=</mo>
	<mn>1,3</mn>
	<mo>×</mo>
	<msup>
		<mrow>
			<mn>10</mn>
		</mrow>
		<mrow>
			<mrow>
				<mo>−</mo>
				<mn>6</mn>
			</mrow>
		</mrow>
	</msup>
</math>
```
jEuclid renders as:
![изображение](https://user-images.githubusercontent.com/5559926/103459140-f7b29b80-4d1d-11eb-8d71-4f6d5b9b3bd6.png)

If we move  `mfenced open="(" close=")"` into nested `mtext`, i.e.:
```
<mrow>
	<mtext>(Cu)</mtext>
</mrow>
```
then we get a bit compact view:
![изображение](https://user-images.githubusercontent.com/5559926/103459182-45c79f00-4d1e-11eb-97c1-02fecfef2c4c.png)

Looks like jEuclid adds some space for `mfenced`.

In any case  isn't looks as original (there isn't distance between `w` and `(`:
![изображение](https://user-images.githubusercontent.com/5559926/103459244-d8683e00-4d1e-11eb-8be3-fc7da3f2fb73.png)

In the original docx, this equation typed as normal text (not Equation object in Word). If we insert it as Equation, then we get the distance between `w` and `(`:
![изображение](https://user-images.githubusercontent.com/5559926/103459445-86281c80-4d20-11eb-9120-280516ae28fb.png)

My proposal  - move `mfenced` attributes into nested element  in xslt on-fly.

**Comment by ronaldtse** [comment]
I think the concern is about "Vmax" looking like "V m a x". The space between the parentheses is acceptable. Thanks!

**Comment by Intelligent2013** [comment]
BIPM xslt updated for decreasing space between `(` and `)`.
It affects on these equations: [si-brochure-fr.presentation.mathml.pdf](https://github.com/metanorma/bipm-si-brochure/files/5803531/si-brochure-fr.presentation.mathml.pdf)

**Comment by ronaldtse** [comment]
Thank you @Intelligent2013 ! Can we close this now?

**Comment by Intelligent2013** [comment]
Done.

**Comment by ronaldtse** [comment]
Need confirmation. In the latest provided `si-brochure-fr.presentation.mathml.pdf` file, line 226 is this:

<img width="1004" alt="Screen Shot 2021-01-15 at 9 37 35 PM" src="https://user-images.githubusercontent.com/11865/104733596-e46dea00-5779-11eb-8f44-f2dbe233d4ad.png">

BIPM pointed out that:
> There is still an error in item 226: the index ‘12’ before the C for carbon, should be a superscript, not a subscript: 12C. 

But it is encoded correctly in source

```adoc
[stem%unnumbered]
++++
ii(M)("X") = ii(A)_"r" ("X") [ii(M)(""^{12}"C")//12] = ii(A)_"r" ("X") ii(M)_{rm(u)}
++++
```

And also rendered correctly in the currently released version:
<img width="582" alt="Screen Shot 2021-01-15 at 9 38 23 PM" src="https://user-images.githubusercontent.com/11865/104733667-00718b80-577a-11eb-8af9-ecd0de18adc8.png">

@Intelligent2013 could you help confirm the latest stylesheet is correct? Thanks!

**Comment by Intelligent2013** [comment]
Yes, the latest stylesheet (in mn-native-pdf/xslt_src) is correct and renders so:
![изображение](https://user-images.githubusercontent.com/5559926/104734378-351d1d00-5751-11eb-959f-4d809341f007.png)

si-brochure-fr.presentation.mathml.pdf shows only difference between source mathml markup and mfenced processing, but not all another mathml markup as preceding superscript, superscript one-level alignment, etc.)

**Comment by ronaldtse** [comment]
Thank you!
