### ISSUE TITLE
PDF: Table header cell underlining issue in 2 MEP files

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#74]
The table header cells seem to be have both a top line and also a bottom line, but we only want the top line if it's the first row. 

1. https://www.bipm.org/utils/common/pdf/mep/M-e-P_I2_532.pdf

https://github.com/metanorma/bipm-si-brochure/blob/master/sources/rec-values/mep-wgfs-nm532-I2.adoc

Original:
(a)
<img width="742" alt="Screen Shot 2021-01-07 at 2 23 29 PM" src="https://user-images.githubusercontent.com/11865/103858785-eab5f380-50f3-11eb-8157-4d36c7fcd056.png">

```adoc
Output:
<img width="575" alt="Screen Shot 2021-01-07 at 3 02 15 PM" src="https://user-images.githubusercontent.com/11865/103862050-58185300-50f9-11eb-9772-e8a16e67bbc9.png">

[%unnumbered]
|===
| line no | transition h| comp. 2+h| stem:[f_(xy) = [ f(y , x) – f(a_(10), R(56) 32-0) \] // rm(kHz)]
| h| stem:[x] h| stem:[y] h| stem:[f_(xy)] h| stem:[u_c // rm(kHz)]
```

(b)
<img width="710" alt="Screen Shot 2021-01-07 at 2 23 45 PM" src="https://user-images.githubusercontent.com/11865/103858807-f6091f00-50f3-11eb-9a2c-1d303b7e2f4e.png">

Output:
<img width="569" alt="Screen Shot 2021-01-07 at 3 02 32 PM" src="https://user-images.githubusercontent.com/11865/103862067-61092480-50f9-11eb-8384-5c3881a66101.png">

```adoc
[%unnumbered]
|===
| transition | comp. 2+h| stem:[f_(xy) = [ f(y , x) – f(a_(10), "R(56) 32-0") \] // " "rm(kHz)] h| Ref.
h| stem:[x] h| stem:[y] h| stem:[f_(xy)] h| stem:[u_c // rm(kHz)] h|
```

(c)
<img width="933" alt="Screen Shot 2021-01-07 at 2 23 57 PM" src="https://user-images.githubusercontent.com/11865/103858818-fbff0000-50f3-11eb-8d05-582eb7c3096d.png">

Output:
<img width="577" alt="Screen Shot 2021-01-07 at 3 02 52 PM" src="https://user-images.githubusercontent.com/11865/103862094-6c5c5000-50f9-11eb-8bec-028869ac9e89.png">

```adoc
[%unnumbered]
|===
| line no | transition | comp. 6+h| stem:[[ f(y , x) – f(a_(10)," R(56) 32-0)"\] // " "rm(kHz)]
h| h| stem:[x] h| stem:[y] h| <<ye1999>> h| <<zhang>> h| <<holzwarth>> h| <<nevsky>> h| unw. mean h| stem:[u // rm(kHz)]
```

2. https://www.bipm.org/utils/common/pdf/mep/M-e-P_OsO4_10.3.pdf

Original:
<img width="688" alt="Screen Shot 2021-01-07 at 2 23 07 PM" src="https://user-images.githubusercontent.com/11865/103858761-de319b00-50f3-11eb-81d7-96f12a7eb926.png">

Output:
<img width="612" alt="Screen Shot 2021-01-07 at 3 03 39 PM" src="https://user-images.githubusercontent.com/11865/103862155-87c75b00-50f9-11eb-8f5c-942398dda241.png">

```adoc
[%unnumbered]
.stem:[ii(lambda) ~~ 10.3" "mu rm(m)" OsO"_4]
|===
| h| stem:[""^12 "C"^{16} "O"_2] 2+h| stem:[rm(OsO)_4] h| | | |
h| stem:[n] h| laser line h| line h| [isotope] h| [stem:[f_n − f {R(10)}] stem:[//rm(kHz)]] h| stem:[u_c] stem:[//rm(kHz)] h| [stem:[ f (rm(OsO)_{4})] stem:[−f (rm(CO)_{2}) //rm(kHz)]] h| stem:[u_c] stem:[//rm(kHz)]
```

**Comment by Intelligent2013** [comment]
@ronaldtse yes, you're right, for `th` both borders top and bootom were set. Now, only bottom. So top border for first row - is border for table, and you have to set `h` prefix only for cels which should have bottom border.

Issue fixed in commit https://github.com/metanorma/mn-native-pdf/commit/bafe641d047404381d06a5606eb4c226768541cc

**Comment by ronaldtse** [comment]
This works with the latest version! Thanks!

<img width="711" alt="Screen Shot 2021-01-15 at 9 57 35 PM" src="https://user-images.githubusercontent.com/11865/104735554-af16cb80-577c-11eb-9f6c-4babbd0fddbb.png">
