### ISSUE TITLE
Spacing of math surrounding parenthesis inside index too long

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#78]
@manuel489 reported that:
> The space between parenthesis and math symbol is a little bit longer than usual.

![issue7-generated](https://user-images.githubusercontent.com/11865/105621949-dbe77480-5e47-11eb-8393-7edc99563fdc.PNG)

@Intelligent2013 could you have a look? Thanks.

**Comment by Intelligent2013** [comment]
Fixed:
![изображение](https://user-images.githubusercontent.com/5559926/105628978-5799ef00-5e51-11eb-821a-42bd3326c4b1.png)

**Comment by ronaldtse** [comment]
Thanks!
