### ISSUE TITLE
BIPM: French text formatting issues

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#80]
From BIPM on the French text:

> - there should always be an unbreakable space in front of “double” punctation marks, i.e : ; ! and ?
> - there are a few places where there is a space in front of a comma, which should not be there

**Comment by manuel489** [comment]
Working on it.

**Comment by ronaldtse** [comment]
Thanks!

**Comment by manuel489** [comment]
Pull request added..
