### ISSUE TITLE
BIPM documents review

### ISSUE THREAD

**Issue by anermina** [metanorma/bipm-si-brochure#87]
While reviewing BIPM documents, I noticed several issues, listed below.

1. Titles with `unitsml` in `stem` expressions are not generated correctly.

Example from mep-wgfs-cm4_4-Rb_6-835GHz.adoc:
![image](https://user-images.githubusercontent.com/55683568/110827863-c4006e80-8296-11eb-908a-137356c7a01c.png)
![image](https://user-images.githubusercontent.com/55683568/110828448-543eb380-8297-11eb-97d6-f076339ce27d.png)

From source .adoc
`:title-part-en: Rubidium 87 Atom (stem:[f ~~ 6.835"unitsml(GHz)"])`
`:title-part-fr: Rubidium 87 Atom (stem:[f ~~ 6.835"unitsml(GHz)"])`

2. Unnumbered tables still have "Table" label, which looks odd without a number.

![image](https://user-images.githubusercontent.com/55683568/110832163-4ab74a80-829b-11eb-99d9-ab48f23f7023.png)

3. For some reason, these values (from mep-wgfs-nm467-171Yb_642THz.adoc)
![image](https://user-images.githubusercontent.com/55683568/110834656-18f3b300-829e-11eb-8523-a141f62e727b.png)

are being generated incorrectly (decimal points are wrong):
![image](https://user-images.githubusercontent.com/55683568/110834869-5eb07b80-829e-11eb-91a9-0df92e0d3106.png)

4. Micron is generated as `u` in case it precedes some unit, e.g. micrometer written as `"unitsml(um)"` is generated as `um`.

![image](https://user-images.githubusercontent.com/55683568/110838621-f87a2780-82a2-11eb-9f44-f984bc5bfdac.png)

From source .adoc:
`stem:[ii(lambda) ~~ 3.39 "unitsml(um)"]`

5. In mep-candela-rapport-en, terms after section marked with `[heading=terms and definitions]` attribute are not generated as subsections, rather regular text.

Generated:
![image](https://user-images.githubusercontent.com/55683568/110862851-26ba3000-82c0-11eb-99fb-22fbc736d155.png)

Original:
![image](https://user-images.githubusercontent.com/55683568/110862823-1d30c800-82c0-11eb-9002-3e7144543ab0.png)

6. Can we expand margins for tables a little bit? I know wider space was left due to the side-notes, but we have overlapping numbers in mep-candela-rapport-en (ping @Intelligent2013).

![image](https://user-images.githubusercontent.com/55683568/110864043-de9c0d00-82c1-11eb-9bba-dd6d0e77e05f.png)

**Comment by anermina** [comment]
Two separate tickets are opened to address the following issues:

7. Generating part title and "subtitle" in rec-values documents (#89)
8. Generating space before units (https://github.com/metanorma/metanorma-standoc/issues/441) @opoudjis , I couldn't assign you this ticket because I don't have those privileges in metanorma-standoc.

**Comment by opoudjis** [comment]
4. has been addressed in https://github.com/plurimath/asciimath2unitsml/issues/18

**Comment by opoudjis** [comment]
3. The numbers are so long that their decimal components are being truncated when they are converted from string to floating point. BigDecimal() will deal with those numbers correctly, but BigDecimal is not supported in twitter-cldr.

**Comment by opoudjis** [comment]
twitter_cldr/formatters/numbers/number_formatter.rb :

````
number = "%.#{precision}f" % round_to(number, precision, rounding).abs
````

Will need to provide a BigDecimal equivalent to this floating point calculation, and submit a PR to twitter-cldr.

**Comment by opoudjis** [comment]
Monkey patched twitter-cldr localisation of numbers to extend to BigDecimal. The numbers in `<mn>` are all parsed as BigDecimal, to allow arbitrary precision, whether as integers or floating point.

**Comment by opoudjis** [comment]
Created https://github.com/twitter/twitter-cldr-rb/pull/240 to reflect this update in twitter-cldr-rb

**Comment by opoudjis** [comment]
> 2. Unnumbered tables still have "Table" label, which looks odd without a number.

They do, because of the period. Removing the prefix for unnumbered tables.

**Comment by opoudjis** [comment]
> 1. Titles with unitsml in stem expressions are not generated correctly.

stem macros in general are not being processed properly in titles.

That is because the metanorma-utils generic method asciidoc_sub() is invoking the HTML asciidoctor converter, not the metanorma converter; so it is inserting the HTML AsciiMath delimiters `\$` instead of generating a Metanorma `<stem>` tag. The metanorma-utils converter needs to be at least standoc aware, if not aware of the specific flavour.

**Comment by opoudjis** [comment]
> 5. In mep-candela-rapport-en, terms after section marked with [heading=terms and definitions] attribute are not generated as subsections, rather regular text.

The text is correctly marked up as terms in the generated XML, and are correctly marked up as `<h2 class="TermNum">` in the HTML. Therefore, this is a PDF issue.

@Intelligent2013, 

````
<term id="cls-2-1"><name>2.1.</name><preferred>luminous flux</preferred>
````

in BIPM needs to be rendered up as a subclause , and not as generic text.

**Comment by Intelligent2013** [comment]
> 5. In mep-candela-rapport-en, terms after section marked with [heading=terms and definitions] attribute are not generated as subsections, rather regular text.

Fixed:
![изображение](https://user-images.githubusercontent.com/5559926/111182471-fd4f1c00-85bf-11eb-846b-d376e3f72586.png)

**Comment by opoudjis** [comment]
Change incorporated into twitter-cldr: https://github.com/twitter/twitter-cldr-rb/pull/240
