### ISSUE TITLE
Brochure review: very unbalanced columns width in tables

### ISSUE THREAD

**Issue by manuel489** [metanorma/bipm-si-brochure#88]
*In relation to https://github.com/metanorma/bipm-si-brochure/issues/87*

In latest compilation of the brochure, several tables show a very unbalanced columns width

Example

*Generated:*
![issue1-generated](https://user-images.githubusercontent.com/33627611/110903587-0c8f4a80-82de-11eb-9afe-bb498a855cd2.PNG)

*Original:*
![issue1-original](https://user-images.githubusercontent.com/33627611/110903610-16b14900-82de-11eb-8da7-e34600c9034d.PNG)

Another example

*Generated:*
![issue1_2-generated](https://user-images.githubusercontent.com/33627611/110903628-1c0e9380-82de-11eb-80df-ccb6bb7a83e2.PNG)

*Original:*
![issue1_2-original](https://user-images.githubusercontent.com/33627611/110903641-20d34780-82de-11eb-91e2-ff083f353681.PNG)

**Comment by Intelligent2013** [comment]
@manuel489 I can't repeat this issue. Here is my result:
![изображение](https://user-images.githubusercontent.com/5559926/110957362-97af2580-835c-11eb-90c8-206ed76de02d.png)

Could you attach a presentation xml, please?

**Comment by manuel489** [comment]
@Intelligent2013, sure. This output comes from Nick's latest build.
Here is the xml file:  [si-brochure-en.zip](https://github.com/metanorma/bipm-si-brochure/files/6131109/si-brochure-en.zip)

**Comment by Intelligent2013** [comment]
@manuel489 sorry, but I need si-brochure-en.presentation.xml, not si-brochure-en.xml. Thank you.

**Comment by manuel489** [comment]
@Intelligent2013 no worries, I should have sent you the complete information:
[bilingual-brochure.zip](https://github.com/metanorma/bipm-si-brochure/files/6131199/bilingual-brochure.zip)
👍

**Comment by Intelligent2013** [comment]
@opoudjis presentation xml contains additional UnitsML markup. Which MathML markup should I use for rendering?
- stem/math in any case and ignore unit tags
- stem/math/unit/unitsymbol[@type="MathML"]/math when it presents
- something another case(s)...

```xml
<td valign="top" align="left">
	<stem type="MathML">
		<math xmlns="http://www.w3.org/1998/Math/MathML">
			<mrow xref="U_J/kg">
				<mi mathvariant="normal">J</mi>
				<mo>/</mo>
				<mi mathvariant="normal">kg</mi>
			</mrow>
			<unit xmlns="http://unitsml.nist.gov/2005" dimensionurl="#D_L2M0T-2" xml:id="U_NISTu13.u27p10">
				<unitsystem name="SI" type="SI_derived" xml:lang="en-US"/>
				<unitname xml:lang="en">joule per kilogram</unitname>
				<unitsymbol type="HTML">J&#160;kg<sup>&#8722;1</sup>
				</unitsymbol>
				<unitsymbol type="MathML">
					<math xmlns="http://www.w3.org/1998/Math/MathML">
						<mrow>
							<mi mathvariant="normal">J</mi>
							<mo rspace="thickmathspace">&#8290;</mo>
							<msup>
								<mrow>
									<mi mathvariant="normal">kg</mi>
								</mrow>
								<mrow>
									<mo>&#8722;</mo>
									<mn>1</mn>
								</mrow>
							</msup>
						</mrow>
					</math>
				</unitsymbol>
				<rootunits>
					<enumeratedrootunit unit="joule"/>
					<enumeratedrootunit unit="gram" prefix="k" powernumerator="-1"/>
				</rootunits>
			</unit>
			<prefix xmlns="http://unitsml.nist.gov/2005" prefixbase="10" prefixpower="3" xml:id="NISTp10_3">
				<prefixname xml:lang="en">kilo</prefixname>
				<prefixsymbol type="ASCII">k</prefixsymbol>
				<prefixsymbol type="unicode">k</prefixsymbol>
				<prefixsymbol type="LaTeX">k</prefixsymbol>
				<prefixsymbol type="HTML">k</prefixsymbol>
			</prefix>
			<dimension xmlns="http://unitsml.nist.gov/2005" xml:id="NISTd25">
				<length symbol="L" powernumerator="2"/>
				<time symbol="T" powernumerator="-2"/>
			</dimension>
			<dimension xmlns="http://unitsml.nist.gov/2005" xml:id="D_L2M0T-2">
				<length symbol="L" powernumerator="2"/>
				<mass symbol="M" powernumerator="0"/>
				<time symbol="T" powernumerator="-2"/>
			</dimension>
			<quantity xmlns="http://unitsml.nist.gov/2005" dimensionurl="#NISTd25" quantitytype="base" xml:id="NISTq65">
				<quantityname xml:lang="en-US">specific energy</quantityname>
			</quantity>
		</math>
	</stem>
</td>
```

**Comment by opoudjis** [comment]
> stem/math in any case and ignore unit tags. 

The unit tags do contain the canonical markup of the unit, but we are allowing that to be overridden in the MathML itself (e.g. division instead of multiplication with inverse exponent, m/s instead of m*s^-1.)

**Comment by Intelligent2013** [comment]
Issue fixed.
![изображение](https://user-images.githubusercontent.com/5559926/111030398-14044000-8413-11eb-9de9-28e8ea922ea2.png)

![изображение](https://user-images.githubusercontent.com/5559926/111030408-20889880-8413-11eb-8b56-6186d7f1f9fd.png)

**Comment by manuel489** [comment]
Thank you!
