### ISSUE TITLE
UnitsML rendering crashes

### ISSUE THREAD

**Issue by manuel489** [metanorma/bipm-si-brochure#90]
*In relation with https://github.com/metanorma/bipm-si-brochure/issues/87*

In SI Brochure, there are several cases where UnitsML instance crashes.
Following are the captures where it happens:

Case 1: `stem:["unitsml(kg*m^2*s^(-1))"]`

*Generated:*
![issue2-generated](https://user-images.githubusercontent.com/33627611/110913593-c04b0700-82eb-11eb-8545-19183d8aa502.PNG)

*Original:*
![issue2-original](https://user-images.githubusercontent.com/33627611/110913611-c345f780-82eb-11eb-96fb-0a152f0f6211.PNG)

Case 2: `stem:["unitsml(J/kg)"]`

*Generated:*
![issue2_2-generated](https://user-images.githubusercontent.com/33627611/110913642-cccf5f80-82eb-11eb-9a1a-3d3b3a721f7a.PNG)

*Original:*
![issue2_2-original](https://user-images.githubusercontent.com/33627611/110913661-cfca5000-82eb-11eb-9200-8b29e4753b1a.PNG)

Case 3: `stem:["unitsml(kg*m^(-3))"]` and `stem:["unitsml(kg*m^(-2))"]`

*Generated:*
![issue2_3-generated](https://user-images.githubusercontent.com/33627611/110913682-d48f0400-82eb-11eb-8789-43ba16d76879.PNG)

*Original:*
![issue2_3-original](https://user-images.githubusercontent.com/33627611/110913702-d8228b00-82eb-11eb-9ab4-c5f40122f9f7.PNG)

Case 4: `stem:["unitsml(J*kg^(-1))"]`

*Generated:*
![issue2_4-generated](https://user-images.githubusercontent.com/33627611/110913721-dc4ea880-82eb-11eb-8761-f89d3e969a45.PNG)

*Original:*
![issue2_4-original](https://user-images.githubusercontent.com/33627611/110913748-e375b680-82eb-11eb-8415-f4b5241d0981.PNG)

Case 5: `stem:["unitsml(C*kg^(-1))"]`

*Generated:*
![issue2_5-generated](https://user-images.githubusercontent.com/33627611/110913805-f5575980-82eb-11eb-96fb-22209a4a22c5.PNG)

*Original:*
![issue2_5-original](https://user-images.githubusercontent.com/33627611/110913821-f9837700-82eb-11eb-8cf9-369f0b267a84.PNG)

Case 6: `stem:["unitsml(u-)"]`

*Generated:*
![issue2_6-generated](https://user-images.githubusercontent.com/33627611/110913832-fdaf9480-82eb-11eb-9e51-57b0d9440e5f.PNG)

*Original:*
![issue2_6-original](https://user-images.githubusercontent.com/33627611/110913846-01431b80-82ec-11eb-8587-cf67ad697b25.PNG)

Case 7: `stem:["unitsml(kg//m^3)"]`

*Generated:*
![issue2_7-generated](https://user-images.githubusercontent.com/33627611/110913863-06a06600-82ec-11eb-9fbd-8990a2a314c8.PNG)

*Original:*
![issue2_7-original](https://user-images.githubusercontent.com/33627611/110913887-0f913780-82ec-11eb-9a3a-6dd1d1da1f0e.PNG)

**Comment by opoudjis** [comment]
Malformed MathML is being formed; as a result, the unitsml tags are in lowercase, and are not being stripped from the expression as required. This is not happening consistently, and need to work out what the trigger is.

**Comment by opoudjis** [comment]
First culprit is kg, whose ID in unitsdb, `U_NISTu27p10'3`, is not XML-safe. Will sanitise it when used in document reference.

**Comment by opoudjis** [comment]
Second culprit is `stem:["unitsml(u-)"]`. HTML entity &micro; seems to be confusing ID generator.

**Comment by opoudjis** [comment]
I cannot allow HTML escapes into UnitsML: they are breaking Nokogiri, as Nokogiri::XML does not understand them. They are being output to XML hexadecimal escapes.
