### ISSUE TITLE
Brochure review: footnotes are being rendered as side-notes in MeP documents

### ISSUE THREAD

**Issue by manuel489** [metanorma/bipm-si-brochure#91]
*In relation to https://github.com/metanorma/bipm-si-brochure/issues/87*

Apparently, all the footnotes in MeP documents are being rendered as side-notes.

Example from *mep-kilogram-definition-en.pdf*:

*Generated:*
![issue1-generated](https://user-images.githubusercontent.com/33627611/110972582-851ff680-8332-11eb-90bf-5b044b8d8d8d.PNG)

*Original:*
![issue1-original](https://user-images.githubusercontent.com/33627611/110972590-87825080-8332-11eb-9acd-3d37251fbb53.PNG)

Related files:  [mep-kilogram-definition-en.zip](https://github.com/metanorma/bipm-si-brochure/files/6131686/mep-kilogram-definition-en.zip)

**Comment by ronaldtse** [comment]
BIPM's decision is to use the same layout of the SI Brochure for all MEP documents. I don't clearly remember but in the SI Brochure all footnotes are rendered as side notes? If that is the case then this is intended.

Maybe @opoudjis @Intelligent2013 will remember...

**Comment by Intelligent2013** [comment]
Yes, all footnotes (except footnotes for table cells that render after a table) are rendered as side notes.

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 for the confirmation, closing.
