### ISSUE TITLE
Brochure review: Overlapping text in front page

### ISSUE THREAD

**Issue by manuel489** [metanorma/bipm-si-brochure#92]
*In relation to https://github.com/metanorma/bipm-si-brochure/issues/87*

In almost all MeP documents there is overlapping text in front page.

For example, from *mep-candela-definition-en.pdf*:

![overlapping-candela](https://user-images.githubusercontent.com/33627611/111008005-8b2fca80-8366-11eb-8297-96c89d53acf9.PNG)

Files related: [mep-candela-definition-en.zip](https://github.com/metanorma/bipm-si-brochure/files/6133559/mep-candela-definition-en.zip)

**Comment by Intelligent2013** [comment]
Fixed.
![изображение](https://user-images.githubusercontent.com/5559926/111035372-4f126d80-842b-11eb-88c4-b57a37103ed1.png)

**Comment by manuel489** [comment]
Thanks!
