### ISSUE TITLE
Brochure review: Unexpected brackets appearing

### ISSUE THREAD

**Issue by manuel489** [metanorma/bipm-si-brochure#93]
*In relation to https://github.com/metanorma/bipm-si-brochure/issues/87*

In math environment, there are cases where brackets are rendered instead of parentheses. Being this latter meant to appear.
Apparently, the XML file contains the proper content.
I saw this happen in *mep-kelvin-absolute-uncertainty-en.pdf* and *mep-mole-definition-en.pdf*

From *mep-kelvin-absolute-uncertainty-en.pdf*:

*Generated:*
![issue5-generated](https://user-images.githubusercontent.com/33627611/111008989-c6cb9400-8368-11eb-94f5-561645e886e0.PNG)

*Original:*
![issue5-original](https://user-images.githubusercontent.com/33627611/111008991-ca5f1b00-8368-11eb-9ff2-574f97373903.PNG)

Files related:  [mep-kelvin-absolute-uncertainty-en.zip](https://github.com/metanorma/bipm-si-brochure/files/6133629/mep-kelvin-absolute-uncertainty-en.zip)

**Comment by Intelligent2013** [comment]
Fixed. It was a side effect of fixing another issue.

![изображение](https://user-images.githubusercontent.com/5559926/111035890-871ab000-842d-11eb-8916-cf8f63e0bf31.png)

**Comment by manuel489** [comment]
Thanks! Closing.
