### ISSUE TITLE
Brochure review: big array of equations overlapping its number tag

### ISSUE THREAD

**Issue by manuel489** [metanorma/bipm-si-brochure#94]
*In relation https://github.com/metanorma/bipm-si-brochure/issues/87*

In *mep-kelvin-absolute-uncertainty-en.pdf*, there is a case where a "big" array of equation overlaps its number tag.

*Generated:*
![issue6-generated](https://user-images.githubusercontent.com/33627611/111009703-c502d000-836a-11eb-918f-2be9540a95ea.PNG)

*Original:*
![issue6-original](https://user-images.githubusercontent.com/33627611/111009710-c7fdc080-836a-11eb-8a09-7ce5964cc1a3.PNG)

Is there a way to avoid this to happen?

**Comment by Intelligent2013** [comment]
I've found a solution. If formula doesn't fit, then it scales down (font-size also scales down respectively):

![изображение](https://user-images.githubusercontent.com/5559926/111036712-aadff500-8431-11eb-9b3d-8c67e18a46e9.png)

Xslt updated.

**Comment by manuel489** [comment]
Awesome! Thanks.
