### ISSUE TITLE
Brochure review: Division symbol (/) too small

### ISSUE THREAD

**Issue by manuel489** [metanorma/bipm-si-brochure#95]
*In relation https://github.com/metanorma/bipm-si-brochure/issues/87*

From *mep-kelvin-absolute-uncertainty-en.pdf*.
The division symbol is showing up too small in this case.

*Generated:*
![issue4-generated](https://user-images.githubusercontent.com/33627611/111009862-1ca13b80-836b-11eb-916e-74f63c0eac05.PNG)

*Original:*
![issue4-original](https://user-images.githubusercontent.com/33627611/111009866-1f9c2c00-836b-11eb-96c0-d1fa5162bc76.PNG)

**Comment by Intelligent2013** [comment]
This is side effect from issue https://github.com/metanorma/mn2pdf/issues/58.
Issue fixed. Now it renders:
![изображение](https://user-images.githubusercontent.com/5559926/111038896-52fabb80-843c-11eb-9504-d61dc6f136bd.png)

And I don't figure out how to decrease a height of `/` for 2.9 and 2.11.

**Comment by manuel489** [comment]
Thanks!
