### ISSUE TITLE
Brochure review: document control table badly arranged

### ISSUE THREAD

**Issue by manuel489** [metanorma/bipm-si-brochure#97]
*In relation to https://github.com/metanorma/bipm-si-brochure/issues/87*

The cells of *Document control* table from MeP documents like *guide-ccl-metre-realization-3-en* are wrongly arranged. There are missing information as well:

*Generated (HTML):*
![issue3-generated](https://user-images.githubusercontent.com/33627611/111408159-3a440d00-86ab-11eb-8641-cd9eaf885d25.PNG)

*Original:*
![issue3-original](https://user-images.githubusercontent.com/33627611/111408179-416b1b00-86ab-11eb-91d9-c1fbcf5c0312.PNG)

In addition, this table doesn't appear in PDF output, only in HTML. Ping @Intelligent2013.

Files related: [guide-ccl-metre-realization-3-en.zip](https://github.com/metanorma/bipm-si-brochure/files/6153465/guide-ccl-metre-realization-3-en.zip)

Thanks!

**Comment by ronaldtse** [comment]
@manuel489 is this a markup problem that you can fix?

**Comment by manuel489** [comment]
@ronaldtse I don't think so. This seems to be automatically generated from the attributes.

**Comment by opoudjis** [comment]
It is, it's on me. I probably forgot to propagate it into the Presentation XML.

**Comment by opoudjis** [comment]
No, @Intelligent2013 : there is a document control table appended to the end of some BIPM documents, with a top level tag `doccontrol`. This needs to be rendered.

**Comment by Intelligent2013** [comment]
@opoudjis ok, I see.

**Comment by opoudjis** [comment]
Done from my side. The "Version 1.0" and date is missing; it is expected to be supplied as a second superseded date. (We may need to debug it further, unsure right now.)

**Comment by opoudjis** [comment]
Fixed table my side.

**Comment by Intelligent2013** [comment]
XSLT updated.

**Comment by manuel489** [comment]
@Intelligent2013, the document control table is looking a little strange (to me):

**Comment by manuel489** [comment]
As requested by @Intelligent2013,
Files related:  [guide-ccl-metre-realization-3-en.zip](https://github.com/metanorma/bipm-si-brochure/files/6164599/guide-ccl-metre-realization-3-en.zip)

**Comment by Intelligent2013** [comment]
BIPM XSLT updated. Now it renders for source XML:
```xml
<doccontrol>
  <title>Document Control</title>
  <table unnumbered="true">
    <tbody>
      <tr>
        <th>Authors:</th>
        <td/>
        <td>Ludger Koenders (PTB), Ingo Busch (PTB), J&#248;rgen Garn&#230;s (DFM) and Andrew Yacoot (NPL)</td>
      </tr>
      <tr>
        <td>Draft 1.0 </td>
        <td>2018-06-11</td>
        <td>WG-N co-chairs: Ronald Dixson (NIST) and Harald Bosse (PTB)</td>
      </tr>
      <tr>
        <td/>
        <td/>
        <td>WG-N chair: Andrew Yacoot (NPL)</td>
      </tr>
    </tbody>
  </table>
</doccontrol>
```
as
![изображение](https://user-images.githubusercontent.com/5559926/111640133-f1a46500-880c-11eb-9ed0-8fe7e4105c72.png)

To set table column width I use the same algorithm as for all xslts.

**Comment by manuel489** [comment]
This fixed now, thanks!
