### ISSUE TITLE
Brochure review: landscape mode not present in PDF output

### ISSUE THREAD

**Issue by manuel489** [metanorma/bipm-si-brochure#98]
*In relation to https://github.com/metanorma/bipm-si-brochure/issues/87*

From *guide-ccm-kilogram-dissemination-en.pdf*,
landscape mode is not activated for table 1 as expected from the markup:

````
[%landscape]
<<<

[[table-1]]
[cols=7*^.^,options="header"]
.The four phases necessary for the reliable transition from the IPK to independent NMI realizations of the unit of mass
|===
h| Phase
h| Time scale
h| Description
h| Source of traceability
h| Uncertainty of BIPM mass calibrations

...

[%portrait]
<<<
````

*Original:*
![issue2-generated](https://user-images.githubusercontent.com/33627611/111409411-46c96500-86ad-11eb-9b91-8b20726272e4.PNG)

In addition, in the unit symbol: `stem:["unitsml(ug)"]`, "mu" and "g" seem to be a little bit more separated than normal:

![issue1-generated](https://user-images.githubusercontent.com/33627611/111409794-fef70d80-86ad-11eb-9f2d-b7dfc719e889.PNG)

However, this is not happening in table environment. Check  `10 "unitsml(ug)"` from table 1 in the first image above.
(Ok, maybe this is not a big deal after all 😄 )

Files related: 
[guide-ccm-kilogram-dissemination-en.zip](https://github.com/metanorma/bipm-si-brochure/files/6153511/guide-ccm-kilogram-dissemination-en.zip)

**Comment by Intelligent2013** [comment]
I need a fully refactoring of bipm xslt. Page orientation changing means closing current page sequence and start a new on with another orientation. We have page structure oriented for side notes, and changing page orientation is big challege actually.

**Comment by opoudjis** [comment]
I am not convinced we should proceed with this. @ronaldtse ?

**Comment by Intelligent2013** [comment]
> In addition, in the unit symbol: `stem:["unitsml(ug)"]`, "mu" and "g" seem to be a little bit more separated than normal:
> However, this is not happening in table environment. Check `10 "unitsml(ug)"` from table 1 in the first image above.

Looks like this is a FOP or Batik issue or something else. The distance between chars in SVG depends on font size. In table we use ~85% font-size than normal text.

And It even depends on Java version:

PDF from attachment:
![изображение](https://user-images.githubusercontent.com/5559926/111480326-ed137a00-8742-11eb-8679-56928659947e.png)

Oracle Java 1.8.0_271:
![изображение](https://user-images.githubusercontent.com/5559926/111480548-2f3cbb80-8743-11eb-874a-66559252f47a.png)

AdoptOpenJDK (build 14.0.1+7):
![изображение](https://user-images.githubusercontent.com/5559926/111481174-c1dd5a80-8743-11eb-9f26-33fdd6dcf95a.png)

I don't figure out how to catch the reason of it.

**Comment by Intelligent2013** [comment]
BIPM xslt updated for landscape page orientation processing:

![изображение](https://user-images.githubusercontent.com/5559926/111662085-ab590100-8820-11eb-8500-5c0d1042cff7.png)

**Comment by manuel489** [comment]
This is fixed. Thank you!
